export default {
    "buttons": {
        "filter": "Filter",
        "select_all": "Select All",
        "deselect_all": "Deselect All",
        "close": "",
        "move_left": "",
        "move_right": ""
    },
    "tabs": {
        "by_category": "Category",
        "by_item": "Item",
        "by_search": "Search",
        "resource_list": "Resources",
        "setting": "Settings",
        "user_data": "User Data",
        "quick_setting": "Quick Settings",
        "quick_setting_fuel_loot": "Fuel Loot",
        "quick_setting_resource": "Resource",
        "quick_setting_bus_route": "Monster Bus",
        "area": "Areas",
        "treasure": "Treasures",
        "monster": "Explore",
        "collection": "Collection",
        "hint": "Hint",
        "logged": "Data",
        "guest": "Login",
        "oneclick_delete_enable": "OneClick",
        "oneclick_delete_disable": "Disable",
        "oneclick_delete_badge": "In OneClick mode",
        "oneclick_delete_hint1": "After turning it on, clicking on a marker will no longer display a pop-up window, but will directly delete or undelete the marker.",
        "oneclick_delete_enable_hint": "OneClick deletion mode is enabled",
        "oneclick_delete_disable_hint": "OneClick deletion mode is disabled",
        "oneclick_delete_dialog_title": "Warning",
        "oneclick_delete_dialog_content": "After turning on the one-click deletion mode, no pop-up window will appear when you click a marker on the map. Instead, the marker will be directly deleted or undelete. Do you want to continue turning it on?",
        "oneclick_delete_dialog_close": "Close",
        "oneclick_delete_dialog_confirm": "Confirm",
        "batch_editing_enable": "Batch",
        "batch_editing_disable": "Disable",
        "batch_editing_hint": "You can batch delete or undelete all markers of one category. You need to log in to use it.",
        "setting_btn_hint": "Map related settings",
        "login_btn_hint": "Manage my data",
        "back_to_categories": "Back to Categories",
        "display_area": "Area Filter",
        "select_item_category": "Select",
        "related_items": "Related Items",
        "locate_item": "Click on item to locate",
        "search_resources": "Search Resources",
        "input_resource_name": "Input name",
        "locate": "Locate",
        // Miscellaneous UI strings
        "any_name": "currently only support Chinese",
        "locations": "Locations",
        "locate_point": "Click to center the Location",
        "input_item": "Please enter a Location Name",
        "related_item": "Items",
        "related_makers": "Markers",
        "locate_marker": "Click to center the Marker",
        "input_marker": "Please enter a Marker Name",
        "related_resources": "Resources",
        "locate_resource": "Click to center the Resource",
        "input_resource_for_searching": "Please enter a Resource Name",
        "follow_xingchuan": "Follow Xingchuan",
        "bilibili": "BiliBili",
        "tiktok": "TikTok",
        "ad": "Ad",
        "jd": "Ad is not available in English version",
        "login_warring": "Please get the text from Discord Server bot first.",
    },
    "floor_text": {
        "roof": "( Roof )",
        "at_floor": "( Floor {floor} )",
        "underground": "( Floor {floor} Underground )"
    },
    "settings": {
        "has_video": "Video Marker",
        "deleted_marker": "Deleted Marker",
        "map_area_style": "Map Area Style",
        "monster_bus_route": "Monster Bus Route",
        "marker_text": "Marker Text",
        "resource_area": "Resource Area",
        "last_updated_datetime": "Marker Updated Time",
        "icon_drawing_method": "Icon Drawing Method (Canvas is Recommended when the icon is broken)",
        "dark_mode": "Dark Mode",
        "language": "Language",
        "auto_query": "Query when the Categories Change",
        "auto_draw_marker_after_search": "Display the Search Result on the Map",
        "show": "Show",
        "hide": "Hide",
        "line_style": "Line Style",
        "area_style": "Fill Style",
        "wasm": "Wasm (Best Performance)",
        "canvas": "Canvas (Best Compatibility)",
        "on": "On",
        "off": "Off"
    },
    "user_data": {
        "local_storage": "Local Data",
        "count": "no records | {count} record | {count} records",
        "local_storage_tutorial": "Tutorial",
        "backup": "Backup & Restore",
        "local_storage_text": "You can delete any marker without login. But the data will only storage at current browser. You can backup the data and transfer to another web browser.",
        "backup_placeholder": "Datas",
        "backup_button": "Backup",
        "restore_button": "Restore",
        "cloud_storage": "Cloud Data",
        "clear_all_data": "Delete All Data",
        "restore_hint": "Tip: This operation will merge local data with imported data. If you are logged in, the data will also be synchronized to the cloud. Do you want to continue?",
        "delete_hint": "Are you sure you want to delete all data? If you are already logged in, the cloud data will also be cleared. Do you want to continue?",
        "wechat_login": "Wechat",
        "wechat_mp_login": "Wechat2",
        "discord_login": "Discord",
        "login_tutorial": "Tutorial",
        "login_tutorial_text": "After logging in, the local and cloud data will be automatically synchronized, and you can continue to use it on any browser and device. You can also use it normally without logging in, but the data can only be stored in the local browser.",
        "not_login": "Not logged in",
        "login_success": "You have successfully logged in",
        "data_is_syncing": "Data is Syncing",
        "last_syncing_time": "Last Syncing Time: ",
        "logout": "Log out",
    },
    "marker_dialog": {
        "no_marker_img": "No Images",
        "delete_markder": "Delete Marker",
        "undelete": "Undo Delete",
        "delete_only": "Delete Only",
        "hide_category": "Hide {category}",
        "no_update_time": "No update time",
        "rewards": "Rewards",
        "close": "Close",
        "detail": "Detail",
        "operation": "Operation",
        "timer_title": "Reset Timer",
        "timer_title_not_login": "(Need Login) Reset Timer",
        "to_login": "Login to Unlock Timer Feature",
        "comment": "Comments",
        "auto_set_timer": "Auto Set Timer",
        "auto_set_timer_not_login": "(Need Login) Auto Set Timer",
        "timer_tutorial": "Timer Tutorial",
        "sharing": "Sharing",
        "session_script": "Currently available at: ",
        "hint": "[ Hint ]",
        "sharing_hint": "The shared link will automatically display the marker when opened.",
        "download_qr_code": "Download",
        "sharing_link": "Link",
        "copy": "Copy",
        "update": "Updated",
        "guide": "Guide",
        "donate": "Donate",
        "auto_reset_help_title": "Help",
        "auto_reset_help_text": "The fixed refresh time for weapon crates and gear crates starts at 00:00:00 and refreshes every 4 hours on the hour. If you still can't open the crates when you reach the refresh time, just log in again.",
        "auto_reset_help_ok": "OK"
    },
    "donate": {
        "payment": "Please scan the QR code using WeChat",
        "text": "Your support can help the website continue to operate and update more features",
        "warning": "Minors are prohibited from donating"
    },
    "categories": {
        // Areas
        "传送塔": "Teleporter",
        "巨楔": "Monolith",
        "主城": "Settlement",
        "研究所": "Lab",
        "大型资源点": "Town",
        "小型资源点": "Village",
        "收容井": "Securement Silo",
        "位面锚": "Rift Anchor",
        // Treasures
        "神秘宝藏": "Mysterious Chest",
        "武器箱": "Weapon Crate",
        "装备箱": "Gear Crate",
        "隐藏宝箱": "Hidden Crate",
        "宝箱怪": "Morphic Crate",
        "储物箱": "Storage Crate",
        // Explore
        "精英怪": "Elite",
        "迷雾区域": "Fog Event",
        "防守工坊": "Workshop",
        "移动房屋": "Moving House",
        "限时事件": "Red Event",
        // Collection
        "武器配件": "Attachment", // "Weapon Attachments" is too long and breaks the UI
        "食谱": "Recipe",
        "收容物": "Deviant",
        "诡谲画作": "Mysterious Painting",
        "矿物点": "Mineral",
        "采集点": "Plant",
        // PvP
        "回响石": "Echo Stone",
        // Hint
        "留言": "Hint",
        "隐藏任务": "Side Quest",
        "商人": "Merchant",
        "宜居地点": "Livable Location",
        // Regions
        "代顿湿地": "Dayton Wetlands",
        "破碎三角洲": "Broken Delta",
        "垩峰山": "Chalk Peak",
        "铁锈河": "Iron River",
        "孤狼荒原": "Red Sands",
        "黑心地带": "Blackheart",
        // Routes
        // No need to translate the fuel count number.
        "怪物巴士路线": "Monster Bus",
        "便携混合燃油": "Portable Mixed Fuel",
        // Areas
        "污染区": "Contaminated Area",
        // Teleporters - 传送塔
        "猎犬岛传送塔": "Teleportation Tower",
        "望岛镇传送塔": "Teleportation Tower",
        "离岸广场传送塔": "Teleportation Tower",
        "临溪东部传送塔": "Teleportation Tower",
        "贪欲巨楔传送塔": "Monolith of Greed Teleportation Tower",
        "代顿检查点传送塔": "Teleportation Tower",
        "高岸南部传送塔": "Teleportation Tower",
        "西格玛传送塔": "Teleportation Tower",
        "暖阳中部传送塔": "Teleportation Tower",
        "三角洲南部传送塔": "Teleportation Tower",
        "盖亚山区传送塔": "Teleportation Tower",
        "盖亚巨楔传送塔": "Gaia Cliff Monolith Teleportation Tower",
        "代顿北部传送塔": "Teleportation Tower",
        "高地西部传送塔": "Teleportation Tower",
        "盖亚西部传送塔": "Teleportation Tower",
        "朽鞍镇传送塔": "Teleportation Tower",
        "银滩北部传送塔": "Teleportation Tower",
        "翠湖南部传送塔": "Teleportation Tower",
        "翠湖北部传送塔": "Teleportation Tower",
        "阿尔法传送塔": "Teleportation Tower",
        "月湖传送塔": "Teleportation Tower",
        "庄园东部传送塔": "Teleportation Tower",
        "尖牙巨楔传送塔": "Monolith of Thirst Teleportation Tower",
        "蜿蜒山区传送塔": "Teleportation Tower",
        "波光北部传送塔": "Teleportation Tower",
        "黯梦巨楔传送塔": "Mirage Monolith Teleportation Tower",
        "风角边境传送塔": "Teleportation Tower",
        "谷地南部传送塔": "Teleportation Tower",
        "西塔传送塔": "Teleportation Tower",
        "黑原中部传送塔": "Teleportation Tower",
        "遗忘巨楔传送塔": "Forsaken Monolith Teleportation Tower",
        "悬巢北部传送塔": "Teleportation Tower",
        "悬巢南部传送塔": "Teleportation Tower",
        "内部传送塔": "Teleportation Tower",
        "巨人阶梯传送塔": "Teleportation Tower",
        "黑心内弯传送塔": "Blackheart's Bay Teleportation Tower",
        // Monoliths - 巨楔
        "贪欲巨楔": "Monolith of Greed",
        "盖亚巨楔": "Gaia Cliff Monolith",
        "黯梦巨楔": "Mirage Monolith",
        "尖牙巨楔": "Monolith of Thirst",
        "遗忘巨楔": "Forsaken Monolith",
        // Settlements - 主城
        "旅人营地": "Deadsville",
        "迈尔集市": "Meyer's Market",
        "秽水营地": "Greywater Camp",
        "深草旅店": "Tall Grass Inn",
        "黑原镇": "Blackfell",
        // Labs - 研究所
        "生命进化研究所": "HP Evolution Institute",
        // Towns - 大型资源点
        "中途镇": "Throughville",
        "腐烂庄园": "Rotten Manor",
        "橘子镇": "Citrus County",
        "望岛镇": "Overlook Town",
        "苏德兰果园": "Sutherland Family Orchard",
        "离岸广场": "Coastside Plaza",
        "临溪": "Brookham",
        "代顿医院": "Dayton Hospital",
        "贪欲巨楔警戒区": "Monolith of Greed Danger Zone",
        "赫斯特工业": "Hearst Industries",
        "海港镇": "Harborside",
        "猎犬岛哨站": "Wild Dog Isle Outpost",
        "暖阳中学": "Sunbury Middle School",
        "暖阳镇": "Sunbury",
        "苏德兰化工厂": "Sutherland Chemical Plant",
        "高岸镇": "High Banks",
        "废弃货场": "Junkyard",
        "盖亚研究所遗址": "Gaia Research Center Ruins",
        "东部铁路枢纽": "Eastern Railway Junction",
        "盖亚巨楔警戒区": "Gaia Cliff Monolith Danger Zone",
        "高地": "Highland",
        "冶炼厂污染点": "Refinery Pollution Plant",
        "秽水工业区": "Greywater Industrial Zone",
        "阿卡尔克镇": "Alkirk",
        "东黑原枢纽": "East Blackfell Junction",
        "波光镇": "Rippleby",
        "里奇收容点": "Ricci Securement Point",
        "黯梦巨楔警戒区": "Mirage Monolith Danger Zone",
        "盖亚军事基地": "Gaia Military Base",
        "朽鞍镇": "Rotten Saddle",
        "银滩度假区": "Silvershore Resort",
        "碧湖山镇": "Greenlake Hill",
        "霍特镇": "Holt Town",
        "熔炉巢穴": "Furnace Lair",
        "常青藤酒庄": "Evergreen Vineyard",
        "阿尔法研究所": "Alpha Institute",
        "尖牙巨楔警戒区": "Monolith of Thirst Danger Zone",
        "交错现实研究所": "Alternative Reality Research Institute",
        "黑原油田": "Blackfell Oil Fields",
        "黑原陷落区": "Blackfell Fallen Zone",
        "绿荫镇": "Evergreen",
        "悬巢": "Fort Eyrie",
        "73号源质分离点": "73 Source Extraction Point",
        "太阳农场": "Sunshine Farm",
        "白崖基地": "White Cliff",
        // Villages
        "中途镇变电站": "Throughville Substation",
        "检测点3771": "Inspection Point 3771",
        "翻车鱼岛游客中心": "Mola Island Visitor Center",
        "海岬庄园": "Cape Manor",
        "小码头": "Petit Harbor",
        "艾尔汽修店": "Aiden's Auto Repair",
        "艾尔的隐蔽所": "Aiden's Hideout",
        "检测点7802": "Inspection Point 7802",
        "临溪警戒所": "Brookham Guardhouse",
        "代顿货栈": "Dayton Warehouse",
        "崖下营地": "Cliffside Camp",
        "北岸营地": "North Shore Camp",
        "赫斯特": "Hearst",
        "赫斯特滩涂": "Hearst Mudflats",
        "湖心野营地": "Lakeheart Camp",
        "迈尔": "Meyer",
        "高岸巢穴": "Highbank Nest",
        "废弃隐蔽所": "Abandoned Hideout",
        "骑士修车店": "Knight Vehicle Repairs",
        "山脊中转站": "Ridge Transfer Station",
        "山脊营地": "Ridge Camp",
        "暖阳农庄": "Sunbury Farm",
        "瀑布广场": "Waterfall Plaza",
        "沉船坟场": "Ship Graveyard",
        "沉没宅院": "Sunken House",
        "检测点024": "Inspection Point 024",
        "检测点9043": "Inspection Point 9043",
        "TAB-6A营地": "Tab-6A Camp",
        "高地居住区": "Highland Residential Zone",
        "洗劫一空的营地": "Ransacked Camp",
        "远眺伐木场": "Overlook Lumberyard",
        "污染检测点77": "Pollution Inspection Point 77",
        "河心码头": "Riverhart Harbor",
        "河畔纪念品店": "Riverside Souvenirs",
        "枯竭油井": "Depleted Oil Well",
        "蜿蜒山种植园": "Winding Ridge Farmland",
        "浅滩公园": "Shoal Park",
        "波光镇集市": "Rippleby Market",
        "风车阵列": "Wind Farm",
        "秘港": "Secret Harbor",
        "检测点023": "Inspection Point 023",
        "克里夫顿": "Clifton",
        "海风疗养地": "Breezy Shores Resort",
        "诺顿农场": "Norton Farm",
        "高岸检测点": "Highbank Inspection Point",
        "私酿庄园": "Brewery Estate",
        "老大的乐园": "The Boss's Playground",
        "霍特电站": "Holt Power Station",
        "帕斯利广场": "Paisley Plaza",
        "山麓别墅": "Hilly Homestead",
        "盖亚通讯阵列": "Gaia Communication Array",
        "检测点266": "Inspection Point 266",
        "狂热信徒聚落": "Believer Colony",
        "戴维斯角": "Davis Point",
        "鞍前营地": "Saddlefront Camp",
        "渔人码头": "Fisherman Wharf",
        "格尔峰电站": "Mount Guel Power",
        "检测点091": "Inspection Point 091",
        "妮娜奶奶的水果餐吧": "Grandma Nina's Diner",
        "检测点384": "Inspection Point 384",
        "矿镇": "Mining Town",
        "翠湖游客中心": "Greenlake Visitor Center",
        // Securement Silos - 收容井
        "收容井-西格玛": "Securement Silo - Sigma",
        "收容井-斐": "Securement Silo - Phi",
        "收容井-暗狱": "Securement Silo EX1",
        "收容井-阿尔法": "Securement Silo - Alpha",
        "收容井-寒境": "Securement Silo - Psi",
        "收容井-西塔": "Securement Silo - Theta",
        // Rift Anchors - 位面锚
            // has no individual names yet in chinese
        // Mysterious Chests - 神秘宝藏
            // has no individual names
        // Weapon Crates - 武器箱
            // has no individual names
        "武器箱【剧情箱子】": "Weapon Crate【Story】",
        // Gear Crates - 装备箱
            // has no individual names
        // Hidden Crates - 隐藏宝箱
            // has no individual names
        // Morphic Crates - 宝箱怪
            // has no individual names
        // Storage Crates - 储物箱
            // has no individual names
        // Elites - 精英怪
        "暴食狂": "Glutton",
        "屠夫": "Arbiter",
        "裁决者": "Arbiter",
        "星尘簇": "Star Walker",
        "门徒": "Disciple",
        "雨壳": "Rainfall Reaper",
        "腐坏眼虫": "Claw Machine", // Chagas Weevil
        "娃娃机": "Claw Machine", // Chagas Weevil
        "抓娃娃机": "Claw Machine", // Chagas Weevil
        "唤生之母": "Mother of Life",
        "唤生水母": "Mother of Life",
        "熔烛": "Molton Candle",
        "乐园向导": "Balloon Boy",
        "夜魇": "Cervitaur",
        "天气预报": "Weather Forecast",
        "罪人守望": "Sinner Sentry", 
        //"”教练“ 【清剿目标】": "", //removed?
        //'"龙脊" 科利·兰根': "", //removed?
        "罗塞塔防暴员": "Rosetta Bruiser",
        "罗塞塔机械师": "Rosetta Mechanic",
        "罗塞塔重装员": "Rosetta Heavy",
        // Fog Events - 迷雾区域
            // has no individual names
        // Workshops - 防守工坊
            // has no individual names
        // Moving Houses - 移动房屋
            // has no individual names
        // Red Events - 限时事件
        "这里没有迪斯科": "Where Does Disco Go?",
        "湖之暗面": "The Dark Side",
        //"": "Cargo Scramble"
        "挖通地狱": "Dig to Hell",
        "腐乐园": "Paradise Lost",
        "喀戎行动": "Operation Chiron",
        // Accessories - 武器配件
        // Weapon Attachments - 武器配件
        // Optics - 瞄具配件
        "轻量化红点瞄具": "Light Reflex Sight",
        "战斗侦查瞄具": "Recon Combat Optic",
        "反射式瞄具": "Reflex Sight",
        "精准步枪瞄具": "Precision Rifle Scope",
        "战术全像瞄准镜": "Tactical Holographic Sight",
        "精准光学瞄具": "Precision Optic",
        "战术步枪瞄具": "Tactical Rifle Scope",
        "轻型光学瞄具": "Light Optic",
        "中距离战术瞄具": "Mid-Range Optic",
        "密封型反射式瞄具": "Sealed Reflex Sight",
        "紧凑型反射式瞄具": "Compact Reflex Sight",
        "棱镜式瞄具": "Prismatic Sight",
        "远距离战术瞄具": "Long-Range Tactical Sight",
        "大型光学瞄具": "Large Optic Sight",
        "紧固型微型红点瞄具": "Fastened Mini Reflex Sight",
        "微型红点瞄具": "Mini Reflex Sight",
        "先进战斗光学瞄具": "Advanced Combat Optic",
        "全像瞄准镜": "Holographic Sight",
        // Muzzle Attachments - 枪口配件
        "鱼鹰抑制器": "Osprey Suppressor",
        "集成型补偿器": "Integrated Compensator",
        "多用途霰弹枪抑制器": "Multi-Use Shotgun Suppressor",
        "锤头型补偿器": "Hammer Compensator",
        "短型抑制器": "Short Suppressor",
        "战术消焰器": "Tactical Flash Hider",
        "小型补偿器": "Small Compensator",
        "加长型制退器": "Extended Brake",
        "一体式抑制器": "Integrated Suppressor",
        "小型制退器": "Small Muzzle Brake",
        "一体式消焰器": "Integrated Flash Hider",
        //"多孔式消焰器": "", // Multi-Hole Flash Hider
        "伪装用抑制器": "Camouflage Suppressor",
        "大型抑制器": "Large Suppressor",
        "大型枪口制退器": "Large Brake",
        "前向消焰器": "Forward Flash Hider",
        "消焰器": "Flash Hider",
        "轻量化制退器": "Light Brake",
        "基础抑制器": "Basic Suppressor",
        "紧凑型制退器": "Compact Brake",
        "霰弹枪制退器": "Shotgun Brake",
        // Tactial Attachments - 战术配件
        "小型红外指示器": "Mini Reflex Sight, Small Infrared",
        "前护手握把": "Front Guard Grip",
        "后护手握把": "Back Guard Grip",
        "大型激光指示器": "Large Laser Sight",
        "集成型激光指示器": "Integrated Laser Sight",
        "角型握把": "Triangle Grip",
        "战术激光指示器": "Tactical Laser Sight",
        "小型激光指示器": "Small Laser Sight",
        "轻质前握把": "Light Front Grip",
        "轻质水平握把": "Light Horizontal Grip",
        "战术手电筒": "Tactical Flashlight",
        "红外指示器": "Infrared Indicator",
        "紧凑型红外指示器": "Compact Infrared Indicator",
        "战术组合握把": "Tactical Combine Grip",
        "眼镜蛇握把": "Cobra Grip",
        "垂直握把": "Vertical Grip",
        "紧凑型手电筒": "Compact Flashlight",
        "激光指示器": "Laser Sight",
        "折叠脚架": "Folding Bipod",
        // Magazines - 弹匣配件
        "狙击枪战术弹匣": "Tactical SR Mag",
        "轻机枪校准弹鼓": "Calibrated LMG Drum Mag",
        "狙击枪改良弹匣": "Amended SR Mag",
        "步枪轻量化弹匣": "Light Rifle Mag",
        "冲锋枪加重型弹匣": "Weighted SMG Mag",
        "轻机枪大型弹鼓": "Large LMG Drum Mag",
        "手枪战术型弹匣": "Tactical Pistol Mag",
        "冲锋枪战术型弹匣": "Tactical SMG Mag",
        "步枪扩容弹匣": "Extended Rifle Mag",
        "手枪加长型弹匣": "Extended Pistol Mag",
        "手枪改良弹匣": "Amended Pistol Mag",
        "冲锋枪改良弹匣": "Amended SMG Mag",
        "步枪改良弹匣": "Amended Rifle Mag",
        // Puzzle Types
        "异常门扉": "Door Puzzle",
        "异常路牌": "Broken Billboard",
        "广告牌异常": "Broken Billboard",
        "破碎山石异常": "Breakable Rock",
        "异常电话亭": "Phone Booth",
        "异常雕像": "Statue Puzzle",
        "黑水相机": "Camera Emote",
        //"": "Compact Brake (needs Mysterious Painting)",
        "诡谲画作: 小型制退器": "Small Muzzle Brake (needs Mysterious Painting)",
        "诡谲画作: 轻型光学瞄具": "Light Optic (needs Mysterious Painting)",
        "诡谲画作: 小型激光指示器": "Small Laser Sight (needs Mysterious Painting)",
        "诡谲画作: 战术步枪瞄具": "Tacticle Rifle Scope (needs Mysterious Painting)",
        "诡谲画作: 前向消焰器": "Forward Flash Hider (needs Mysterious Painting)",
        // Attachment Dupes with Spelling differences
        "战斗侦察瞄具": "Recon Combat Optic",
        "眼镜蛇握把": "Cobra Grip",
        "反射式瞄具·黑色": "Reflex Sight",
        "角形握把": "Triangle Grip",
        "霰弹枪式制动器": "Shotgun Brake",
        "密封型反射瞄具": "Sealed Reflex Sight",
        "多用途霰弹枪抑制器(6226,-588)": "Multi-Use Shotgun Suppressor (6226,-588)", // Keep coordinates when available
        "大型光学瞄具,黑心地带(3039,990)": "Large Optic Sight (3039,990)",
        "大型光学瞄具,黑心地带(3037,-979)": "Large Optic Sight (3037,-979)",
        "手枪加强型弹匣": "Extended Pistol Mag",
        "诡谲画作：小型制退器": "Small Muzzle Brake (needs Mysterious Painting)",
        "诡谲画作：轻型光学瞄具": "Light Optic (needs Mysterious Painting)",
        "诡谲画作：小型激光指示器": "Small Laser Sight (needs Mysterious Painting)",
        "诡谲画作：战术步枪瞄具": "Tacticle Rifle Scope (needs Mysterious Painting)",
        "诡谲画作：前向消焰器": "Forward Flash Hider (needs Mysterious Painting)",
        "诡谲画作:战术步枪瞄具": "Tacticle Rifle Scope (needs Mysterious Painting)",
        // Item Categories - 手枪
        "手枪": "Pistols",
        "霰弹枪": "Shotguns",
        "冲锋枪": "SMGs", // Submachine Guns
        "步枪": "Rifles",
        "狙击枪": "Sniper Rifles",
        "轻机枪": "LMGs", // Light Machine Guns
        "弓弩": "Crossbows",
        "重型火器": "Heavy Weapons",
        "刀剑": "Melee Weapons",
        "头盔": "Helmets",
        "面部": "Masks", // Face
        "上身": "Vests", // Top
        "下身": "Pants", // Bottom
        "手套": "Gloves",
        "鞋子": "Shoes",
        "瞄具配件": "Optics",
        "枪口配件": "Muzzle Attachments",
        "战术配件": "Tactial Attachments",
        "弹匣配件": "Magazines",
        "碎弹模组": "Shrapnel Mods",
        "霜寒模组": "Frost Vortex Mods",
        "爆弹模组": "Unstable Bomber Mods",
        "电涌模组": "Power Surge Mods",
        "标记模组": "The Bull's Eye Mods",
        "弹射模组": "Bounce Mods",
        "快枪手模组": "Fast Gunner Mods",
        "灼烧模组": "Burn Mods",
        "阵地模组": "Fortress Warfare Mods",
        "武器通用": "Weapon Compatible", // ?
        "头盔模组": "Helmet Mods",
        "面部模组": "Mask Mods", // Face mods
        "上身模组": "Vest Mods", // Top mods
        "下身模组": "Pants Mods", // Bottom Mods
        "手套模组": "Glove Mods",
        "鞋子模组": "Shoe Mods",
        "防具通用": "Armor Compatible", // ?
        "近战通用": "Melee General", // ?
        "流派效果": "Genre Effect", // ?
        "模组后缀": "Module Suffixes", // ?
        "元素伤害": "Elemental Damage", // ?
        "特殊子弹": "Special Bullets", // ?
        "套装碎片": "Set Fragments",
        "素材": "Materials",
        "近战蓝图": "Melee Weapon Blueprints",
        "手枪蓝图": "Pistol Blueprints",
        "霰弹枪蓝图": "Shotgun Blueprints",
        "冲锋枪蓝图": "SMG Blueprints", // Submachine Gun Blueprints
        "步枪蓝图": "Rifle Blueprints",
        "狙击枪蓝图": "Sniper Rifle Blueprints",
        "轻机枪蓝图": "LMG Blueprints", // Light Machine Gun Blueprints
        "弓弩蓝图": "Crossbow Blueprints",
        "家具配方": "Furniture Blueprints",
        "肉类": "Meat",
        "鱼类": "Fish",
        "药草": "Herbs",
        // Recipes - 食谱
        "食谱：熏肉罗宋汤": "Recipe: Borscht Deluxe",
        "食谱：畸变塔可卷": "Recipe: Taco", // In World item says Herbal Tea
        "食谱：星尘茶": "Recipe: Stardust Tea",
        "食谱：培根肉排汉堡": "Recipe: Bacon Burger",
        "食谱：南瓜星空派": "Recipe: Stargazy Pie",
        "食谱：消脂果汁": "Recipe: Fat-Burning Juice",
        "食谱：安全三明治": "Recipe: Safety Sandwich",
        "食谱：星尘水果罐头": "Recipe: Assorted Canned Food",
        "食谱：星尘通心粉罐头": "Recipe: Stardust Italian Soup Can",
        "食谱：奇迹茶": "Recipe: Miracle Tea",
        "食谱：碎裂面包": "Recipe: Shattered Bread",
        "食谱：星尘南瓜泥沙拉": "Recipe: Stardust Pumpkin Salad",
        "食谱：幽光蘑菇罐头": "Recipe: Spectral Canned Mushroom",
        "食谱：星尘炸肉": "Recipe: Mixed Fried Hot Dog",
        "食谱：元宝饺子": "Recipe: Yuanbao Dumplings",
        "食谱：深海鱼片披萨": "Recipe: Stargazy pizza",
        "食谱：炸薯条": "Recipe: French Fries",
        "食谱：反重力奶昔": "Recipe: Anti-gravity Milkshake",
        "食谱：金钱饼": "Recipe: Croquette",
        "食谱：特调冰酿": "Recipe: Signature Ice Brew",
        "食谱:奇思妙想饮": "Recipe: Whimsical Drink",
        "食谱：炸鱼薯条": "Recipe: Fish & Chips",
        "食谱：幽灵饼干": "Recipe: Ghost Cookies",
        "食谱：畸变带骨香肠": "Recipe: Bone-in Deviated Sausage",
        "食谱：捕获之汤": "Recipe: Securement Soup",
        "食谱：蜜酿炖肉": "Recipe: Honey Glaced Meat",
        // Deviants - 收容物
        "远归之蝶": "Butterfly's Emissary",
        "活体凝胶": "Festering Gel",
        "荣枯种子": "Harveseed",
        "捕梦网": "Dreamcatcher",
        "低语亡骨": "Canine Skull",
        "电鳗": "Electric Eel",
        "迪斯科球": "Disco Ball",
        "发条青蛙": "Frog the Leaper",
        "极寒水母": "Polar Jelly",
        "青龙": "Chefosaurus",
        "蜂团团": "Buzzy Bee",
        "工号37": "H37",
        //"": "Fetch-A-Lot Bunny",
        "姜饼屋": "Gingerbread House",
        //"": "Atomic Lighter",
        "凝视的黑猫": "Enchanted Void",
        "木工河狸": "Logging Beaver",
        "空间魔方": "Space Turner",
        "元素小子": "Digby Boy",
        //"": "Snow Globe",
        //"": "Growshroom",
        "皆斩": "Zeno-Purifier",
        "门扉": "Strange Door",
        //"": "Party Monkey",
        "巫毒娃娃": "Voodoo Doll",
        "炎之精": "Flame Essence",
        "破碎少女": "Shattered Maiden",
        //"": "Mini Wonder",
        "异维大猫": "Extradimensional Cat",
        "球状闪电": "Orb Lightning",
        "迷你黄衣": "Mini Feaster",
        "小纸人": "Paper Doll",
        //"": "Lethal Rabit",
        //"": "Artisan's Touch",
        "愿望先生": "Mr Wish",
        "红龙": "Pyro Dino",
        //"": "Dr. Teddy",
        "恶臭球根": "Grumpy Bulb",
        "空之子": "By-The-Wind",
        //"": "Lava Fox",
        "胡桃夹子": "Nutcracker",
        //"": "Wish Machine",
        "蝶之梦": "Rebecca",
        "气球狗": "Pup Buddy",
        "一碗美味": "Hug-In-A-Bowl",
        //"": "Masonic Pyramid",
        // Mysterious Painting - 诡谲画作
        "诡谲画作·代顿湿地": "Mysterious Painting · Dayton Wetlands",
        "诡谲画作·破碎三角洲": "Mysterious Painting · Broken Delta",
        "诡谲画作·铁锈河": "Mysterious Painting · Iron River",
        "诡谲画作·垩峰山": "Mysterious Painting · Chalk Peak",
        "诡谲画作·孤狼荒原": "Mysterious Painting · Red Sands",
        "诡谲画作·黑心地带": "Mysterious Painting · Blackheart",
        // Ores
        //"": "Rock",
        "硫磺": "Sulfur",
        "铜矿": "Copper Ore",
        "锡矿": "Tin Ore",
        "锡矿富集区": "Tin Ore Area",
        "铁矿": "Iron Ore",
        "铝矿": "Aluminum Ore",
        "钨矿": "Tungsten Ore",
        "银矿": "Silver Ore",
        "银矿区域": "Silver Ore Area",
        "银矿(稀有)": "Silver Ore (Random)",
        "银矿 (稀有)": "Silver Ore (Random)",
        "金矿": "Gold Ore",
        "金矿区域": "Gold Ore Area",
        "金矿(稀有)": "Gold Ore (Random)",
        "金矿 (稀有)": "Gold Ore (Random)",
        "金矿（先锋服)": "Gold Mine",
        "星尘矿": "Stardust Ore",
        "星尘矿石": "Stardust Ore",
        "星尘矿区": "Stardust Ore Area",
        "星尘矿区域": "Stardust Ore Area",
        "星尘矿(稀有)": "Stardust Ore (Random)",
        "星尘矿 (稀有)": "Stardust Ore (Random)",
        // Plants
        "橘子": "Oranges",
        "果蔬篮橘子": "Oranges",
        "小麦": "Wheat",
        "果蔬篮小麦": "Wheat",
        "红色浆果": "Hawthorn Berry",
        "卷心菜": "Cabbage",
        "果蔬篮卷心菜": "Cabbage",
        "甜菜": "Beet",
        "果蔬篮甜菜": "Beet",
        "蓝莓": "Blueberry",
        "南瓜": "Pumpkin",
        "果蔬篮南瓜": "Pumpkin",
        "玉米": "Corn",
        "果蔬篮玉米": "Corn",
        "土豆": "Potato",
        "果蔬篮土豆": "Potato",
        "蘑菇": "Mushroom",
        "果蔬篮蘑菇": "Mushroom",
        //"": "Cucumber",
        //"": "Tomato",
        //"": "Red Tulip",
        //"": "Yellow Tulip",
        //"": "Yellow Hydrangea",
        //"": "Blue Hydrangea",
        //"": "White Petunia",
        //"": "Blue Petunia",
        "芦荟": "Aloe Vera",
        "鼠尾草 * 5": "Sage * 5",
        "鼠尾草 * 8": "Sage * 8",
        "桔梗": "Bellflower",
        "金银花": "Honeysuckle",
        "金银花 * 3": "Honeysuckle * 3",
        "金银花 * 4": "Honeysuckle * 4",
        "藏红花": "Saffron",
        "血菖蒲": "Scarlet Calamus",
        "紫锥菊": "Coneflower",
        "黄莲花": "Yellow Lotus",
        //"": "Peppercorn",
        "苹果": "Apple",
        "苹果树": "Apple Tree",
        "苹果树 * 2": "Apple Tree * 2",
        //"": "Cactus",
        "葡萄": "Grapes",
        "贝壳岩石": "Shell Rock",
        "海草岩石": "Seaweed Rock",
        "观赏性花海": "Sea of ​​Flowers",
        "香蕉树": "Banana Tree",
        "香蕉树 * 2": "Banana Tree * 2",
        "香蕉树 * 4": "Banana Tree * 4",
        "香蕉树 * 6": "Banana Tree * 6",
        "香蕉树 * 7": "Banana Tree * 7",
        "椰子树": "Coconut Tree",
        "椰子树 * 3": "Coconut Tree * 3",
        "巨木": "Giant Tree",
        "龙血树(巨木)": "Giant Tree",
        // Animals
        "野生动物": "Animals",
        "兔子窝": "Rabbit Hole",
        "鹿": "Deer",
        "星蚀鹿群": "Deer",
        "星蚀雄鹿": "Deer",
        "星蚀雌鹿": "Deer",
        "野猪": "Boar",
        "野猪群": "Boar",
        "星蚀鳄": "Alligator",
        "羊群": "Flock",
        "花豹": "Leopard",
        "星蚀熊窝": "Bear's Den",
        "星蚀熊": "Bear",
        "肉排": "Steak",
        "鳄鱼蛋": "Alligator Eggs",
        "鸟蛋": "Bird Eggs",
        // Oil Wells
        "原油油井": "Oil Well",
        // Echo Stone - 回响石
            // has no individual names
        // Hints - 留言
        "别靠近箱子": "Mimic",
        "地堡门禁卡": "Bunker Access Card",
        "吓人箱子": "Mimic",
        "空间异动": "Space Anomaly",
        "地下入口": "Underground Entrance",
        "电话亭": "Telephone Booth",
        "拟态怪储物箱": "Mimic",
        "拟态宝箱怪": "Mimic",
        "密码: 5897": "Password: 5897",
        "密码: 325": "Password: 325",
        "地下通道入口": "Underground Entrance",
        "地下通道最近入口": "Underground Entrance",
        "地窖入口": "Underground Entrance",
        "山洞入口": "Cave Entrance",
        "溶洞入口": "Cave entrance",
        "镜女": "Mirror Enemy",
        "拟态储物箱别开": "Mimic",
        "电梯：负一层": "Elevator: Underground Level 1",
        "拟态宝箱怪别开": "Mimic",
        "空间异常": "Space Anomaly",
        "5层楼梯": "5 Stairs",
        "箱子怪别开": "Mimic",
        "下楼电梯": "Elevator",
        "下楼电梯位置": "Elevator",
        "隐藏宝箱最后位置": "Treasure Chest",
        "抽屉柜": "Drawers",
        // Side Quests - 隐藏任务
        //"": "A Miracle Chase",
        "隐藏的宝箱": "Morphic Crate Tutorial", //
        //"异常档案": "",//Abnormal Files?
        //"": "The Shadowed Lighthouse",
        "玩具小熊": "The Call of Childhood",
        "急救！急救！": "Dayton Hospital",
        //'"玩具熊"女孩': "", //Teddy Bear Girl?
        //"": "Harvest Season",
        //"": "The Lost Lady",
        //"": "Deviation Expert",
        //"": "Martial God's Home",
        "信徒的藏宝图": "Lost In Madness - Starting Point",
        "信徒的财产箱": "Lost In Madness - Treasure Location",
        //"": "Stardust Infiltration",
        //"": "An Act of Theft",
        "检测点见闻": "Sketch of an Inspection Point",
        //"": "Supply Line",
        //"": "Where the Cat and Mice Play",
        "红与黑": "Carnival of Doom",
        //"": "The Treasure Infinite",
        //"": "Love Sorrow",
        //"": "Foreign Rock",
        //"": "Unfinished Expedition",
        //"": "Mayfly Badge",
        //"": "Secret Flavors",
        //"": "Save Meta-Human",
        //"": "Welcome!",
        //"": "Boy Just Wanna Have Fun",
        //"": "For Sarah",
        //"": "A Gift Overdue",
        //"": "Experimental Material",
        //"女儿的问候": "", //Greetings from my daughter?
        //"": "Into the Madness",
        //"": "Grumbling Scavenger",
        //"": "To Save or Not to Save",
        //"寻找记忆": "", //Searching for memories?
        //"": "Save Meta-Human",
        "被丢弃的玩偶": "Anna's Toys",
        //"": "Chance Encounter: Welcome Aboard",
        "艺术家的钥匙": "Cultist Meeting - Starting Point",
        "信徒的宝箱": "Cultist Meeting - Treasure Location",
        "特别关系": "A Special Relationship",
        //"嘉莲": "",
        "生日快乐": "Happy Birthday",
        //"": "Little Shop of Kindness",
        "招财猫开始点": "Lucky Cat - Starting Point",
        "招财猫1号": "Lucky Cat #1",
        "招财猫2号": "Lucky Cat #2",
        "招财猫3号": "Lucky Cat #3",
        "招财猫给予的宝箱": "Lucky Cat - Treasure Location",
        "好消息坏消息": "On Joy and Sorrow - Starting Point",
        "神婆的宝箱": "On Joy and Sorrow - Treasure Location",
        //"成就：一览众山小": "",//Achievement: A view of the world?
        "农庄惊魂": "Farm Horror",
        "限定版牛奶": "Limited Edition",
        "考古学家的馈赠": "Be True 'Til Death",
        "遗留财产": "A Family Legacy",
        "悲伤画像": "Sorrowful Portrait",
        //"罗塞塔保险箱": "", //Rosetta Safe?
        "密码：9274": "Password: 9274", //Really a Side Quest?
        "秘密配方": "Recipe", //Really a Side Quest?
        // Merchant - 商人
        "韦伯": "Weber",
        "赵金潭": "Zhao Jintan",
        //"": "Jonathan",
        //"": "Emma Potter",
        "拟态体商店": "Severin VII-S2041 (SIRA Trader)",
        //"": "Nisa (Sproutlet Trader)",
        "鱼饵商人": "Margerie (Fish Merchant)",
        "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie【Fish Blueprints】",
        // Livable Location - 宜居地点
        // Livable Location are the recommended places to live with subjective opinions, These are usually large flat areas with rich resources and close to water sources.
            // has no individual names
        // Not sure where/if the following are used.
        "异常点": "Abnormal Object",
        "稀有": "Rare",
        "持续刷新": "Continuous Refresh",
        "碧湖山庄": "Greenlake Hill",
        "检测点91": "Inspection Point 91",
        "戴维思角": "Davis Point",
        "检测点24": "Inspection Point 24",
        "翻车鱼岛旅客中心": "Mola Island Visitor Center",
        "治炼厂污染点": "Refinery Pollution Plan",
        "检测点3711": "Inspection Point 3711",
        
    }
}