export default {
    "buttons": {
        "filter": "Filter",
        "select_all": "Select All",
        "deselect_all": "Deselect All",
        "close": "Close",
        "move_left": "Move Left",
        "move_right": "Move Right"
    },
    "tabs": {
        "by_category": "Category",
        "by_item": "Item",
        "by_search": "Search",
        "resource_list": "Resources",
        "setting": "Settings",
        "user_data": "User Data",
        "quick_setting": "Quick Settings",
        "quick_setting_resource": "Resource",
        "quick_setting_bus_route": "Monster Bus",
        "area": "Areas",
        "treasure": "Treasures",
        "monster": "Explore",
        "collection": "Collection",
        "hint": "Hint",
        "logged": "Data",
        "guest": "Data",
        "oneclick_delete_enable": "OneClick",
        "oneclick_delete_disable": "Disable",
        "oneclick_delete_badge": "In OneClick mode",
        "oneclick_delete_hint1": "After turning it on, clicking on a marker will no longer display a pop-up window, but will directly delete or undelete the marker.",
        "oneclick_delete_enable_hint": "OneClick deletion mode is enabled",
        "oneclick_delete_disable_hint": "OneClick deletion mode is disabled",
        "oneclick_delete_dialog_title": "Warning",
        "oneclick_delete_dialog_content": "After turning on the one-click deletion mode, no pop-up window will appear when you click a marker on the map. Instead, the marker will be directly deleted or undelete. Do you want to continue turning it on?",
        "oneclick_delete_dialog_close": "Close",
        "oneclick_delete_dialog_confirm": "Confirm",
        "batch_editing_enable": "Batch",
        "batch_editing_disable": "Disable",
        "batch_editing_hint": "You can batch delete or undelete all markers of one category. You need to log in to use it.",
        "setting_btn_hint": "Map related settings",
        "login_btn_hint": "Manage my data",
        "back_to_categories": "Back to Categories",
        "display_area": "Area Filter",
    },
    "floor_text": {
        "roof": "( Roof )",
        "at_floor": "( Floor {floor} )",
        "underground": "( Floor {floor} Underground )"
    },
    "settings": {
        "has_video": "Video Marker",
        "deleted_marker": "Deleted Marker",
        "map_area_style": "Map Area Style",
        "monster_bus_route": "Monster Bus Route",
        "marker_text": "Marker Text",
        "resource_area": "Resource Area",
        "last_updated_datetime": "Marker Updated Time",
        "icon_drawing_method": "Icon Drawing Method (Canvas is Recommended when the icon is broken)",
        "dark_mode": "Dark Mode",
        "language": "Language",
        "auto_query": "Query when the Categories Change",
        "auto_draw_marker_after_search": "Display the Search Result on the Map",
        "show": "Show",
        "hide": "Hide",
        "line_style": "Line Style",
        "area_style": "Fill Style",
        "wasm": "Wasm (Best Performance)",
        "canvas": "Canvas (Best Compatibility)",
        "on": "On",
        "off": "Off"
    },
    "user_data": {
        "local_storage": "Local Data",
        "count": "no records | {count} record | {count} records",
        "local_storage_tutorial": "Tutorial",
        "backup": "Backup & Restore",
        "local_storage_text": "You can delete any marker without login. But the data will only storage at current browser. You can backup the data and transfer to another web browser.",
        "backup_placeholder": "Datas",
        "backup_button": "Backup",
        "restore_button": "Restore",
        "cloud_storage": "Cloud Data (Only supports Wechat Authentication for now)",
        "clear_all_data": "Delete All Data",
        "restore_hint": "Tip: This operation will merge local data with imported data. If you are logged in, the data will also be synchronized to the cloud. Do you want to continue?",
        "delete_hint": "Are you sure you want to delete all data?"
    },
    "marker_dialog": {
        "no_marker_img": "No Images",
        "delete_markder": "Delete Marker",
        "undelete": "Undo Delete",
        "delete_only": "Delete Only",
        "hide_category": "Hide {category}",
        "no_update_time": "No update time",
        "rewards": "Rewards",
        "close": "Close",
        "detail": "Detail",
        "operation": "Operation",
        "timer_title": "Reset Timer",
        "timer_title_not_login": "(Need Login) Reset Timer",
        "to_login": "Login to Unlock Timer Feature",
        "comment": "Comments",
        "auto_set_timer": "Auto Set Timer",
        "auto_set_timer_not_login": "(Need Login) Auto Set Timer",
        "timer_tutorial": "Timer Tutorial",
        "sharing": "Sharing",
        "session_script": "Currently available at: ",
        "hint": "[ Hint ]",
        "sharing_hint": "The shared link will automatically display the marker when opened.",
        "download_qr_code": "Download",
        "sharing_link": "Link",
        "copy": "Copy",
        "update": "Updated",
        "guide": "Guide",
        "donate": "Donate",
    },
    "donate": {
        "payment": "Please scan the QR code using WeChat",
        "text": "Your support can help the website continue to operate and update more features",
        "warning": "Minors are prohibited from donating"
    },
    "categories": {
        "巨楔": "Monolith",
        "主城": "Settlement",
        "研究所": "Lab",
        "大型资源点": "Town",
        "小型资源点": "Village",
        "采集点": "Plant",
        "收容井": "Securement Silo",
        "传送塔": "Teleporter",
        "武器配件": "Accessory",
        "食谱": "Recipe",
        "精英怪": "Elite",
        "收容物": "Deviants",
        "异常点": "Abnormal Object",
        "宝箱怪": "Morphic Crate",
        "武器箱": "Weapon Crate",
        "装备箱": "Gear Crate",
        "神秘宝藏": "Mysterious Chest",
        "隐藏宝箱": "Hidden Crate",
        "留言": "Hint",
        "诡谲画作": "Mysterious Painting",
        "商人": "Merchant",
        "隐藏任务": "Side Quests",
        "迷雾区域": "Fog Event",
        "移动房屋": "Moving House",
        "回响石": "Echo Stone",
        "储物箱": "Storage Crate",
        "位面锚": "Rift Anchor",
        "防守工坊": "Workshop",
        "宜居地点": "Livable Location",
        "限时事件": "Red Events",
        "矿物点": "Mineral",
        "代顿湿地": "Dayton Wetlands",
        "破碎三角洲": "Broken Delta",
        "垩峰山": "Chalk Peak",
        "铁锈河": "Iron River",
        "孤狼荒原": "Lone Wolf Wastes",
        "黑心地带": "Blackheart",
        "怪物巴士路线": "Monster Bus",
        "远归之蝶": "Butterfly's Emissary",
        "活体凝胶": "Festering Gel",
        "荣枯种子": "Harveseed",
        "捕梦网": "Dreamcatcher",
        "迪斯科球": "Disco Ball",
        "元素小子": "Digby Boy",
        "木工河狸": "Logging Beaver",
        "电鳗": "Electric Eel",
        "愿望先生": "Mr Wish",
        "姜饼屋": "Gingerbread House",
        "蝶之梦": "蝶之梦",
        "一碗美味": "Hug-In-A-Bowl",
        "极寒水母": "Polar Jelly",
        "工号37": "H37",
        "低语亡骨": "Canine Skull",
        "蜂团团": "Buzzy Bee",
        "空间魔方": "Space Turner",
        "气球狗": "气球狗",
        "凝视的黑猫": "凝视的黑猫",
        "空之子": "By-The-Wind",
        "恶臭球根": "Grumpy Bulb",
        "胡桃夹子": "Nutcracker",
        "青龙": "Chefosourus",
        "发条青蛙": "Frog the Leaper",
        "红龙": "Pyro Dino",
        "门扉": "Strange Door",
        "小纸人": "Paper Figure",
        "巫毒娃娃": "Voodoo Doll",
        "迷你黄衣": "Mini Feaster",
        "皆斩": "Zeno-Purifier",
        "破碎少女": "Shattered Maiden",
        "异维大猫": "Extradimensional Cat",
        "球状闪电": "Ball Lightning",
        // 下面是添加新的翻译
        // 每行格式都一样，左边双引号是原文，中间是英文冒号，右边是翻译，结尾是因为逗号，不能使用中文冒号和中文的逗号
        // ,是英文逗号, :英文冒号
        // ，是中文逗号，：中文冒号，不能混用
        // 添加一条翻译
        // 首字母大写
        "土豆": "Potato",
        "果蔬篮土豆": "Potato",
        "南瓜": "Pumpkin",
        "果蔬篮南瓜": "Pumpkin",
        "玉米": "Corn",
        "果蔬篮玉米": "Corn",
        "炎之精": "Flame Essence",
        "短型抑制器": "Short Suppressor ",
        "步枪轻量化弹匣": "Amended Rifle Mag",
        "集成型补偿器": "Ntegrated Compensator",
        "紧凑型手电筒": "Compact Flashlight",
        "眼镜蛇握把": "Cobra Grip",
        "战斗侦察瞄具": "Recon Combat Optic",
        "冲锋枪加重型弹匣": "Weighted SMG Mag",
        "诡谲画作：小型制退器": "Small Brake",
        "步枪扩容弹匣": "Extended Rifle Mag",
        "手枪加强型弹匣": "Extended Pistol Mag ",
        "手枪战术型弹匣": "Tactical Pistol Mag",
        "冲锋枪战术型弹匣": "Tactical SMG Mag",
        "鱼鹰抑制器": "Osprey Suppressor",
        "手枪改良弹匣": "Amended Pistol Mag",
        "霰弹枪式制动器": "Shotgun Brake",
        "密封型反射瞄具": "Sealed Reflex Sight",
        "战术组合握把": "Tactical Combine Grip ",
        "紧凑型红外指示器": "Compact Infrared Indicator",
        "大型枪口制退器 ": "Large Brake ",
        "加长型制退器": "Extended Brake",
        "大型激光指示器": "Large Laser Sight ",
        "后护手握把": "Back Guard Grip",
        "反射式瞄具": "Reflex Sight ",
        "角形握把": "Triangle Grip",
        "小型补偿器": "Small Compensator",
        "诡谲画作：小型激光指示器": "Small Laser Sight",
        "折叠脚架": "Folding Bipod",
        "精准光学瞄具": "Precision Optic",
        "诡谲画作:战术步枪瞄具": "Tacticle Rifle Scope Tacticle ",
        "锤头型补偿器": "Hammer Compensator",
        "战术激光指示器": "Tactical Laser Sight",
        "步枪轻量化弹匣": "Light Rifle Mag",
        "小型红外指示器": "Mini Reflex Sight, Small Infrared",
        "精准步枪瞄具": "Precision Rifle Scope",
        "集成型激光指示器": "Integrated Laser Sight",
        "多用途霰弹枪抑制器": "Multi-Use Shotgun Suppressor",
        "大型光学瞄具,黑心地带(3037,-979)": "Large Optic Sight",
        "轻机枪大型弹鼓": "Large LMG Drum Mag",
        "狙击枪战术弹匣": "Tactical SR Mag",
        "战术全像瞄准镜": "Tactical Holographic Sight",
        "前护手握把": "Front Guard Grip",
        "白崖基地": "White Cliff",
        "太阳农场": "Sunshine Farm",
        "黑原陷落区": "Blackfell Fallen Zone",
        "黑原油田": "Blackfell Oil Fields",
        "73号源质分离点": "73 Source Extraction Point",
        "交错现实研究所": "Alternative Reality Research Institute",
        "绿荫镇": "Evergreen",
        "阿卡尔克镇": "Alkirk",
        "秽水工业区": "Greywater Industrial Zone",
        "东黑原枢纽": "East Blackfell Junction",
        "黯梦巨楔警戒区": "Mirage Monolith Danger Zone",
        "克里夫顿": "Clifton",
        "海风疗养地": "Breezy Shores Resort",
        "碧湖山庄": "Greenlake Hill",
        "尖牙巨楔": "Monolith of Thirst",
        "尖牙巨楔警戒区": "Monolith of Thirst Danger Zone",
        "矿镇": "Mining Town",
        "检测点384": "Inspection Point 384",
        "狂热信徒聚落": "Believer Colony",
        "检测点266": "Inspection Point 266",
        "盖亚军事基地": "Gaia Military Base",
        "鞍前营地": "Saddlefront Camp",
        "朽鞍镇": "Rotten Saddle",
        "妮娜奶奶的水果餐吧": "Grandma Nina's Diner",
        "检测点91": "Inspection Point 91",
        "格尔峰电站": "Mount Guel Power",
        "银滩度假区": "Silvershore Resort",
        "渔人码头": "Fisherman Wharf",
        "戴维思角": "Davis Point",
        "沉没宅院": "Sunken House",
        "废弃货场": "Junkyard",
        "检测点24": "Inspection Point 24",
        "暖阳镇": "Sunbury",
        "暖阳中学": "Sunbury Middle School",
        "海港镇": "Harborside",
        "望岛镇": "Overlook Town",
        "翻车鱼岛旅客中心": "Mola Island Visitor Center",
        "苏德兰果园": "Sutherland Family Orchard",
        "海岬庄园": "Cape Manor",
        "小码头": "Petit Harbor",
        "离岸广场": "Coastside Plaza",
        "艾尔汽修店": "Aiden's Auto Repair",
        "波光镇集市": "Rippleby Market",
        "波光镇": "Rippleby",
        "风车阵列": "Wind Farm",
        "蜿蜒山种植园": "Winding Ridge Farmland",
        "里奇收容点": "Ricci Securement Point",
        "生命进化研究所": "HP Evolution Institute",
        "治炼厂污染点": "Refinery Pollution Plan",
        "河心码头": "Riverhart Harbor",
        "污染检测点77": "Pollution Inspection Point 77",
        "远眺伐木场": "Overlook Lumberyard",
        "高地": "Highland",
        "高地居住区": "Highland Resiential Zone",
        "崖下营地": "Cliffside Camp",
        "代顿货栈": "Dayton Warehouse",
        "代顿医院": "Dayton Hospital",
        "贪欲巨楔": "Monolith of Greed",
        "贪欲巨楔警戒区": "Monolith of Greed Danger Zone",
        "腐烂庄园": "Rotten Manor",
        "中途镇变电站": "Throughville Substation",
        "中途镇": "Throughville",
        "检测点3711": "Inspection Point 3711",
        "检测点7802": "Inspection Point 7802",
        "赫斯特工业": "Hearst Industries",
        "赫斯特": "Hearst",
        "赫斯特滩涂": "Hearst Mudflats",
        // 07-17 补充
        "蘑菇": "Mushroom",
        "果蔬篮蘑菇": "Mushroom",
        "观赏性花海": "Sea of ​​Flowers",
        "甜菜": "Beet",
        "果蔬篮甜菜": "Beet",
        "卷心菜": "Cabbage",
        "果蔬篮卷心菜": "Cabbage",
        "铁矿": "iron ore",
        "锡矿": "Tin ore",
        "铜矿": "Copper ore",
        "野生动物": "Animals",
        "贝壳岩石": "Shell rock",
        "硫磺": "Sulfur",
        "铝矿": "Aluminum Ore",
        "钨矿": "Tungsten Ore",
        "海草岩石": "Seaweed Rock",
        "小麦": "Wheat",
        "果蔬篮小麦": "Wheat",
        "蓝莓": "Blueberry",
        "星蚀鳄": "Alligator",
        "抽屉柜": "Chest of Drawers",
        "橘子": "Oranges",
        "果蔬篮橘子": "Oranges",
        "橘子镇": "Citrus County",
        "金矿(稀有)": "Gold Mine (Random)",
        "金矿 (稀有)": "Gold Mine (Random)",
        "金矿": "Gold Mine",
        "金矿区域": "Gold Mine",
        "银矿": "Silver Mine",
        "银矿(稀有)": "Silver Mine (Random)",
        "银矿 (稀有)": "Silver Mine (Random)",
        "星尘矿": "Stardust Mine",
        "星尘矿石": "Stardust Mine",
        "星尘矿(稀有)": "Stardust Mine (Random)",
        "星尘矿 (稀有)": "Stardust Mine (Random)",
        "星尘矿区域": "Stardust Mine Area",
        "红色浆果": "Red berries",
        "肉排": "steak",
        "收容井-阿尔法": "Securement Silo - Alpha",
        "阿尔法研究所": "Alpha Institute",
        "鳄鱼蛋": "Alligator Eggs",
        "苹果树": "Apple Tree",
        "葡萄": "Grapes",
        "星蚀鹿群": "Deer",
        "香蕉树": "Banana Tree",
        "鸟蛋": "Bird Eggs",
        "椰子树": "Coconut Tree",
        "黄莲花": "Yellow Lotus",
        "紫锥菊": "Echinacea",
        "野猪": "Wild Boar",
        "野猪群": "Wild Boar",
        "金银花": "Lonicera",
        "罗塞塔机械师": "Rosetta Mechanic",
        "罗塞塔重装员": "Rosetta Heavy",
        "雨壳": "Rainfall Reaper",
        "乐园向导": "Balloon Boy",
        "星尘簇": "Star Walker",
        "熔烛": "Molton Candle",
        "罗塞塔防暴员": "Rosetta Bruiser",
        "暴食狂": "Glutton",
        "唤生之母": "Mother of Life",
        "旅人营地": "Deadsville",
        "迈尔集市": "Meyer's Market",
        "稀有": "Rare",
        "持续刷新": "Continuous Refresh",
        "地下入口": "Underground Entrance",
        "原油油井": "Oil Well",
        "藏红花": "Saffron",
        "银矿区域": "Silver Mining Area",
        "星尘矿区": "Stardust Mine",
        "芦荟": "Aloe Vera",
        "遗忘巨楔": "Forsaken Monolith",
        "巨木": "Giant Tree",
        "收容井-寒境": "Securement Silo Psi",
        "血菖蒲": "Calamus",
        "鹿": "Deer",
        "拟态体商店": "Merchant",
        "苹果": "Apple",
        "山洞入口": "Cave Entrance",
        "溶洞入口": "Cave entrance",
        "锡矿富集区": "Tin Ore",
        "大型枪口制退器": "Large muzzle brake",
        "诡谲画作: 前向消焰器": "Forward Flash Hider",
        "集成型激光指示器": "Integrated Laser Pointer",
        "反射式瞄具·黑色": "Reflex Sights",
        "紧固型微型红点瞄具": "Tightening Micro Red Dot Sight",
        "诡谲画作: 小型制退器": "Small Muzzle Brake",
        "兔子窝": "Rabbit Hole",
        "鱼饵商人": "Bait Merchant",
        "花豹": "Leopard",
        "黑原镇": "Blackfell",
        "诡谲画作: 战术步枪瞄具": "Tactical Rifle Sights",
        "污染区": "Contaminated Area",
        "一体式抑制器": "Integrated Suppressor",
        "悬巢": "Fort Eyrie",
        "星蚀熊窝": "Bear's Den",
        "星蚀熊": "Bear"
    }
}