export default {
  buttons: {
    filter: "Filter",
    select_all: "Alle Auswählen",
    deselect_all: "Auswahl Entfernen",
    close: "",
    move_left: "",
    move_right: "",
  },
  tabs: {
    by_category: "Kategorie",
    by_item: "Gegenstand",
    by_search: "Suchen",
    resource_list: "Ressourcen",
    setting: "Einstellungen",
    user_data: "Benutzer Info",
    quick_setting: "Schnell Einstellungen",
    quick_setting_fuel_loot: "Treibstoffbeute",
    quick_setting_resource: "Ressource",
    quick_setting_bus_route: "Monster Bus",
    quick_setting_show_players: "Show Players",
    quick_setting_pollution: "Pollution",
    "quick_setting_popup_coordinate": "Coordinate Follow Pointer",
    area: "Umgebungen",
    treasure: "Schätze",
    monster: "Erkunden",
    collection: "Kollektion",
    hint: "Tipp",
    logged: "Info",
    guest: "Login",
    oneclick_delete_enable: "EinClick",
    oneclick_delete_disable: "Ausschalten",
    oneclick_delete_badge: "In EinClick Modus",
    oneclick_delete_hint1:
      "Nach dem aktivieren werden Pop Up Fenster nicht mehr geöffnet, sondern das Symbol direkt entfernt!",
    oneclick_delete_enable_hint: "EinClick entfernungs modus ist angeschaltet",
    oneclick_delete_disable_hint:
      "EinClick entfernungs modus ist ausgeschaltet",
    oneclick_delete_dialog_title: "Warnung",
    oneclick_delete_dialog_content:
      "Nach dem aktivieren werden Pop Up Fenster nicht mehr geöffnet, sondern das Symbol direkt entfernt! Willst Du diese Option Aktivieren?",
    oneclick_delete_dialog_close: "Schließen",
    oneclick_delete_dialog_confirm: "Bestätigen",
    batch_editing_enable: "Fortschritt",
    batch_editing_disable: "Zurück",
    batch_editing_hint:
      "Du kannst alle Markierungen einer Kategorie entfernen oder wiederherstellen. Du musst Dich zunächst dafür anmelden, um die Funktion zu verwenden.",
    setting_btn_hint: "Kartenbezogene Einstellungen",
    login_btn_hint: "Meine Daten verwalten",
    back_to_categories: "Zurück zu den Kategorien",
    display_area: "Umgebungsfilter",
    select_item_category: "Auswählen",
    related_items: "Verwandte Gegenstände",
    locate_item:
      "Klicke auf den Gegenstand, um diesen zu lokalisieren bzw. zu finden",
    search_resources: "Nach Ressourcen suchen",
    input_resource_name: "Name Eingeben",
    locate: "Lokalisieren",
    // Miscellaneous UI strings
    any_name: "Gegenwärtig nur Chinesisch unterstützt",
    locations: "Aufenthaltsorte",
    locate_point: "Klicken um den Standort zu zentrieren",
    input_item: "Bitte einen Standortsnamen eingeben",
    related_item: "Gegenstände",
    related_makers: "Markierungen",
    locate_marker: "Klicken um die Markierung zu zentrieren",
    input_marker: "Bitte einen Markierungsnamen eingeben",
    related_resources: "Ressourcen",
    locate_resource: "Klicken um die Ressource einzutragen",
    input_resource_for_searching: "Bitte einen Ressourcennamen eingeben",
    follow_xingchuan: "Folge Xingchuan",
    bilibili: "BiliBili",
    tiktok: "TikTok",
    ad: "Werbung",
    ad2: "Werbung",
    jd: "Werbung nicht in Deutsch verfügbar",
    daigan: "Werbung nicht in Deutsch verfügbar",
    login_warring: "Bitte hole Dir zuerst den Text vom Discord-Server-Bot.",
    delete_all: "Alle entfernen",
    resume_all: "Wiederherstellen",
    exit_management_mode: "Zurück",
    select_scenario: "Scenario"
  },
  floor_text: {
    roof: "( Dach )",
    at_floor: "( Stockwerk {floor} )",
    underground: "( Stockwerk {floor} Unterirdisch )",
    level: "( Lv. {level} )",
  },
  settings: {
    has_video: "Video Markierung",
    deleted_marker: "Markierung entfernen",
    map_area_style: "Karten Umgebungs Stil",
    monster_bus_route: "Monster Bus Route",
    marker_text: "Markierungs Text",
    resource_area: "Ressourcen Umgebung",
    last_updated_datetime: "Markierungs aktualisierungs Zeit",
    icon_drawing_method:
      "Methode zum Zeichnen von Symbolen (Canvas wird empfohlen, wenn das Symbol defekt ist)",
    dark_mode: "Dark Mode",
    language: "Sprache",
    auto_query: "Abfrage bei Änderung der Kategorien",
    auto_draw_marker_after_search: "Anzeigen der Resultate auf der Karte",
    show: "Zeige",
    hide: "Verstecke",
    line_style: "Linien Stil",
    area_style: "Füllungs Stil",
    wasm: "Wasm (Beste Performance)",
    canvas: "Canvas (Beste Kompatibilität)",
    on: "An",
    off: "Aus",
    draw_text_mode: "Markierungs Text Stil",
    draw_text_mode_1: "Vollständig",
    draw_text_mode_2: "Vereinfacht",
    deleted_marker_style: "Entfernter Markierungs Stil",
    deleted_marker_style_1: "Kreuz",
    deleted_marker_style_2: "Durchsichtig",
    deleted_marker_style_3: "Verstcke",
  },
  user_data: {
    local_storage: "Lokale Daten",
    count: "keine Datensätze | {count} Datensatz | {count} Datensätze",
    local_storage_tutorial: "Tutorial",
    backup: "Backup & Wiederherstellung",
    local_storage_text:
      "Du kannst jeden Marker löschen, ohne angemeldet zu sein. Die Daten werden jedoch nur im Browser gespeichert. Du kannst die Daten speichern und in einen anderen Webbrowser übertragen.",
    backup_placeholder: "Daten",
    backup_button: "Backup",
    restore_button: "Wiederherstellen",
    cloud_storage: "Cloud Daten",
    clear_all_data: "Alle Daten löschen",
    restore_hint:
      "Tipp: Bei diesem Vorgang werden lokale Daten mit importierten Daten zusammengeführt. Wenn Du angemeldet bist, werden die Daten auch mit der Cloud synchronisiert. Willst Du fortfahren?",
    delete_hint:
      "Willst Du wirklich alle Daten löschen? Wenn Du schon angemeldet bist, werden auch die Cloud-Daten gelöscht. Willst Du fortfahren?",
    wechat_login: "Wechat",
    wechat_mp_login: "Wechat2",
    discord_login: "Discord",
    login_tutorial: "Tutorial",
    login_tutorial_text:
      "Nach dem Einloggen werden die lokalen und Cloud-Daten automatisch synchronisiert und du kannst sie in jedem Browser und auf jedem Gerät weiter nutzen. Du kannst sie auch ganz normal ohne Einloggen nutzen, die Daten können allerdings nur im lokalen Browser gespeichert werden.",
    not_login: "Nicht angemeldet",
    login_success: "Du hast Dich erfolgreich angemeldet!",
    data_is_syncing: "Daten werden Synchronisiert",
    last_syncing_time: "Letzte Synchronisation: ",
    logout: "Ausloggen",
  },
  marker_dialog: {
    no_marker_img: "Keine Bilder",
    delete_markder: "Markierung entfernen",
    undelete: "Entfernung aufheben",
    delete_only: "Nur entfernen",
    hide_category: "Verstecken {category}",
    no_update_time: "Keine update Zeit",
    rewards: "Belohnungen",
    close: "Schließen",
    detail: "Details",
    operation: "Operationen",
    timer_title: "Kisten zurücksetzungs Timer",
    timer_title_not_login: "(Benötigt angemeldung) Kisten zurücksetzungs Timer",
    deviant_timer_title: "Deviant zurücksetzungs Timer", // Not sure if there is a German Translation for Deviant, have only been playing with the Language set to English
    to_login: "Anmelden um das Timer Feature frei zu schalten",
    comment: "Kommentare",
    auto_set_timer: "Automatischer Timer",
    auto_set_timer_not_login: "(Benötigt angemeldung) Auto Set Timer",
    timer_tutorial: "Timer Tutorial",
    sharing: "Teilen",
    session_script: "Gerade verfügbar bei: ",
    hint: "[ Hint ]",
    sharing_hint:
      "Beim Öffnen des geteilten Links wird automatisch die Markierung angezeigt.",
    download_qr_code: "Herunterladen",
    sharing_link: "Link",
    copy: "Kopieren",
    update: "Aktualisiert",
    guide: "Guide",
    donate: "Spenden",
    auto_reset_help_title: "Hilfe",
    auto_reset_help_text:
      "Die feste Aktualisierungszeit für Waffenkisten und Ausrüstungskisten beginnt um 00:00:00 und wird alle 4 Stunden zur vollen Stunde aktualisiert. Wenn du die Kisten nach Erreichen der Aktualisierungszeit immer noch nicht öffnen kannst, melde dich einfach erneut an.",
    auto_reset_help_ok: "Okay",
    click_to_copy: "Klicken zum kopieren",
    copied_successfully: "Erfolgreich kopiert",
    common_hint: "Generelle Tipps",
  },
  donate: {
    payment: "Bitte scanne den QR code mit WeChat",
    text: "Deine Unterstützung kann dazu beitragen, die Seite Operationsbereit zu halten und diese zu Aktualisieren!",
    warning: "Minderjährigen wird das Spenden verboten",
  },
  scenario: {
      "not_available": "Not Available",
      "current": "Current",
      "available": "Available",
      "coming": "Coming",
      "scenarios": "Scenarios"
  },
  categories: {
    // Areas
    传送塔: "Teleporter",
    巨楔: "Monolith",
    主城: "Siedlung",
    研究所: "Labor",
    大型资源点: "Stadt",
    小型资源点: "Dorf",
    收容井: "Sicherungs Silo",
    位面锚: "Rift Anker",
    空间锚点: "Rift Anker",
    // Treasures
    神秘宝藏: "Mysteriöse Kiste",
    神秘宝箱: "Mysteriöse Kiste",
    武器箱: "Waffen Kiste",
    装备箱: "Gear Kiste", // Needs someone knowing how it is written ingame
    隐藏宝箱: "Versteckte Kiste",
    秘藏宝箱: "Versteckte Kiste",
    宝箱怪: "Morphische Kiste", // Needs someone to confirm the Translation
    储物箱: "Storage Crate", // Needs someone knowing how it is written ingame
    // Explore
    精英怪: "Elite",
    迷雾区域: "Rauch Event",
    防守工坊: "Workshop",
    移动房屋: "Bewegendes Haus",
    限时事件: "Rotes Event",
    // Collection
    武器配件: "Anbauteile", // "Waffen Anbauteile" is too long and breaks the UI
    食谱: "Rezept",
    收容物: "Deviant", // Needs someone knowing how it is written ingame
    诡谲画作: "Mysteriöses Gemälde",
    矿物点: "Mineral",
    采集点: "Material",
    种子箱: "Saat Kiste (Samen)",
    调味料箱: "Gewürz Kiste",
    种子香料: "Saat & Gewürz",
    饮料机: "Drink Maschine",
    随机素材箱: "Zufällige Kiste",
    抗菌剂箱: "Medizinische Kiste",
    // PvP
    回响石: "Echo Stone", // Needs someone knowing how it is written ingame
    // Hint
    留言: "Tipp",
    隐藏任务: "Neben Aufgabe",
    支线任务: "Neben Aufgabe",
    商人: "Händler",
    宜居地点: "Belebbare Orte",
    // Regions
    代顿湿地: "Dayton Wetlands",
    破碎三角洲: "Broken Delta",
    垩峰山: "Chalk Peak",
    铁锈河: "Iron River",
    孤狼荒原: "Red Sands",
    黑心地带: "Blackheart",
    // Routes
    // No need to translate the fuel count number.
    怪物巴士路线: "Monster Bus",
    便携混合燃油: "Portabler gemischter Treibstoff",
    // Areas
    污染区: "Kontaminierte Umgebung",
    // Teleporters - 传送塔
    猎犬岛传送塔: "Teleportations Turm",
    望岛镇传送塔: "Teleportations Turm",
    离岸广场传送塔: "Teleportations Turm",
    临溪东部传送塔: "Teleportations Turm",
    贪欲巨楔传送塔: "Monolith of Greed Teleportations Turm",
    代顿检查点传送塔: "Teleportations Turm",
    高岸南部传送塔: "Teleportations Turm",
    西格玛传送塔: "Teleportations Turm",
    暖阳中部传送塔: "Teleportations Turm",
    三角洲南部传送塔: "Teleportations Turm",
    盖亚山区传送塔: "Teleportations Turm",
    盖亚巨楔传送塔: "Gaia Cliff Monolith Teleportations Turm",
    代顿北部传送塔: "Teleportations Turm",
    高地西部传送塔: "Teleportations Turm",
    盖亚西部传送塔: "Teleportations Turm",
    朽鞍镇传送塔: "Teleportations Turm",
    银滩北部传送塔: "Teleportations Turm",
    翠湖南部传送塔: "Teleportations Turm",
    翠湖北部传送塔: "Teleportations Turm",
    阿尔法传送塔: "Teleportations Turm",
    月湖传送塔: "Teleportations Turm",
    庄园东部传送塔: "Teleportations Turm",
    尖牙巨楔传送塔: "Monolith of Thirst Teleportations Turm",
    蜿蜒山区传送塔: "Teleportations Turm",
    波光北部传送塔: "Teleportations Turm",
    黯梦巨楔传送塔: "Mirage Monolith Teleportations Turm",
    风角边境传送塔: "Teleportations Turm",
    谷地南部传送塔: "Teleportations Turm",
    西塔传送塔: "Teleportations Turm",
    黑原中部传送塔: "Teleportations Turm",
    遗忘巨楔传送塔: "Forsaken Monolith Teleportations Turm",
    悬巢北部传送塔: "Teleportations Turm",
    悬巢南部传送塔: "Teleportations Turm",
    内部传送塔: "Teleportations Turm",
    巨人阶梯传送塔: "Teleportations Turm",
    黑心内弯传送塔: "Blackheart's Bay Teleportations Turm",
    // Monoliths - 巨楔
    贪欲巨楔: "Monolith of Greed", // Needs someone knowing how it is written ingame
    盖亚巨楔: "Gaia Cliff Monolith", // Needs someone knowing how it is written ingame
    黯梦巨楔: "Mirage Monolith", // Needs someone knowing how it is written ingame
    尖牙巨楔: "Monolith of Thirst", // Needs someone knowing how it is written ingame
    遗忘巨楔: "Forsaken Monolith", // Needs someone knowing how it is written ingame
    // Settlements - 主城
    旅人营地: "Deadsville",
    迈尔集市: "Meyer's Market",
    秽水营地: "Greywater Camp",
    深草旅店: "Tall Grass Inn",
    黑原镇: "Blackfell",
    // Labs - 研究所
    生命进化研究所: "HP Evolutions Institut", // Needs someone knowing how it is written ingame
    // Towns - 大型资源点
    中途镇: "Throughville",
    腐烂庄园: "Rotten Manor",
    橘子镇: "Citrus County",
    望岛镇: "Overlook Town",
    苏德兰果园: "Sutherland Family Orchard",
    离岸广场: "Coastside Plaza",
    临溪: "Brookham",
    代顿医院: "Dayton Hospital",
    贪欲巨楔警戒区: "Monolith of Greed Danger Zone",
    赫斯特工业: "Hearst Industries",
    海港镇: "Harborside",
    猎犬岛哨站: "Wild Dog Isle Outpost",
    暖阳中学: "Sunbury Middle School",
    暖阳镇: "Sunbury",
    苏德兰化工厂: "Sutherland Chemical Plant",
    高岸镇: "High Banks",
    废弃货场: "Junkyard",
    盖亚研究所遗址: "Gaia Research Center Ruins",
    东部铁路枢纽: "Eastern Railway Junction",
    盖亚巨楔警戒区: "Gaia Cliff Monolith Danger Zone",
    高地: "Highland",
    冶炼厂污染点: "Refinery Pollution Plant",
    秽水工业区: "Greywater Industrial Zone",
    阿卡尔克镇: "Alkirk",
    东黑原枢纽: "East Blackfell Junction",
    波光镇: "Rippleby",
    里奇收容点: "Ricci Sicherungs Point",
    黯梦巨楔警戒区: "Mirage Monolith Danger Zone",
    盖亚军事基地: "Gaia Military Base",
    朽鞍镇: "Rotten Saddle",
    银滩度假区: "Silvershore Resort",
    碧湖山镇: "Greenlake Hill",
    霍特镇: "Holt Town",
    熔炉巢穴: "Furnace Lair",
    常青藤酒庄: "Evergreen Vineyard",
    阿尔法研究所: "Alpha Institute",
    尖牙巨楔警戒区: "Monolith of Thirst Danger Zone",
    交错现实研究所: "Alternative Reality Research Institute",
    黑原油田: "Blackfell Oil Fields",
    黑原陷落区: "Blackfell Fallen Zone",
    绿荫镇: "Evergreen",
    悬巢: "Fort Eyrie",
    "73号源质分离点": "73 Source Extraction Point",
    太阳农场: "Sunshine Farm",
    白崖基地: "White Cliff",
    // Villages
    中途镇变电站: "Throughville Substation",
    检测点3771: "Inspection Point 3771",
    翻车鱼岛游客中心: "Mola Island Visitor Center",
    海岬庄园: "Cape Manor",
    小码头: "Petit Harbor",
    艾尔汽修店: "Aiden's Auto Repair",
    艾尔的隐蔽所: "Aiden's Hideout",
    检测点7802: "Inspection Point 7802",
    临溪警戒所: "Brookham Guardhouse",
    代顿货栈: "Dayton Warehouse",
    崖下营地: "Cliffside Camp",
    北岸营地: "North Shore Camp",
    赫斯特: "Hearst",
    赫斯特滩涂: "Hearst Mudflats",
    湖心野营地: "Lakeheart Camp",
    迈尔: "Meyer",
    高岸巢穴: "Highbank Nest",
    废弃隐蔽所: "Abandoned Hideout",
    骑士修车店: "Knight Vehicle Repairs",
    山脊中转站: "Ridge Transfer Station",
    山脊营地: "Ridge Camp",
    暖阳农庄: "Sunbury Farm",
    瀑布广场: "Waterfall Plaza",
    沉船坟场: "Ship Graveyard",
    沉没宅院: "Sunken House",
    检测点024: "Inspection Point 024",
    检测点9043: "Inspection Point 9043",
    "TAB-6A营地": "Tab-6A Camp",
    高地居住区: "Highland Residential Zone",
    洗劫一空的营地: "Ransacked Camp",
    远眺伐木场: "Overlook Lumberyard",
    污染检测点77: "Pollution Inspection Point 77",
    河心码头: "Riverhart Harbor",
    河畔纪念品店: "Riverside Souvenirs",
    枯竭油井: "Depleted Oil Well",
    蜿蜒山种植园: "Winding Ridge Farmland",
    浅滩公园: "Shoal Park",
    波光镇集市: "Rippleby Market",
    风车阵列: "Wind Farm",
    秘港: "Secret Harbor",
    检测点023: "Inspection Point 023",
    克里夫顿: "Clifton",
    海风疗养地: "Breezy Shores Resort",
    诺顿农场: "Norton Farm",
    高岸检测点: "Highbank Inspection Point",
    私酿庄园: "Brewery Estate",
    老大的乐园: "The Boss's Playground",
    霍特电站: "Holt Power Station",
    帕斯利广场: "Paisley Plaza",
    山麓别墅: "Hilly Homestead",
    盖亚通讯阵列: "Gaia kommunikations Anordnung",
    检测点266: "Untersuchungs Punkt 266",
    狂热信徒聚落: "Vertrauens Kolonie",
    戴维斯角: "Davis Punkt",
    鞍前营地: "Saddlefront Camp",
    渔人码头: "Fischerman Wharf",
    格尔峰电站: "Berg Guel Kraft",
    检测点091: "Untersuchungs Punkt 091",
    妮娜奶奶的水果餐吧: "Großmutter Nina's Lokal",
    检测点384: "Untersuchungs Punkt 384",
    矿镇: "Mining Town",
    翠湖游客中心: "Greenlake Visitor Center",
    // Securement Silos - 收容井
    "收容井-西格玛": "Sicherungs Silo - Sigma",
    "收容井-斐": "Sicherungs Silo - Phi",
    "收容井-暗狱": "Sicherungs Silo EX1",
    "收容井-阿尔法": "Sicherungs Silo - Alpha",
    "收容井-寒境": "Sicherungs Silo - Psi",
    "收容井-西塔": "Sicherungs Silo - Theta",
    // Rift Anchors - 位面锚
    // has no individual names yet in chinese
    // Mysterious Chests - 神秘宝藏
    // has no individual names
    // Weapon Crates - 武器箱
    // has no individual names
    "武器箱【剧情箱子】": "Waffen Kiste【Story】",
    // Gear Crates - 装备箱
    // has no individual names
    // Hidden Crates - 隐藏宝箱
    // has no individual names
    // Morphic Crates - 宝箱怪
    // has no individual names
    // Storage Crates - 储物箱
    // has no individual names
    // Elites - 精英怪
    暴食狂: "Vielfraß",
    屠夫: "Gebieter",
    裁决者: "Gebieter",
    星尘簇: "Sternwanderer",
    门徒: "Disciple",
    雨壳: "Rainfall Reaper",
    腐坏眼虫: "Greifautomat", // Chagas Weevil
    娃娃机: "Greifautomat", // Chagas Weevil
    抓娃娃机: "Greifautomat", // Chagas Weevil
    唤生之母: "Mutter des Lebens",
    唤生水母: "Mutter des Lebens",
    熔烛: "Molton Kerze",
    乐园向导: "Ballon Junge",
    夜魇: "Cervitaur",
    天气预报: "Wettervorhersage",
    罪人守望: "Sünderwache",
    //"”教练“ 【清剿目标】": "", //removed?
    //'"龙脊" 科利·兰根': "", //removed?
    罗塞塔防暴员: "Rosetta Schläger",
    罗塞塔机械师: "Rosetta Mechaniker",
    罗塞塔重装员: "Rosetta Schwer",
    // Fog Events - 迷雾区域
    // has no individual names
    // Workshops - 防守工坊
    // has no individual names
    // Moving Houses - 移动房屋
    // has no individual names
    // Red Events - 限时事件
    这里没有迪斯科: "Where Does Disco Go?", // How should you translate this if you haven't played the game in the German language
    湖之暗面: "Die dunkle Seite",
    //"": "Cargo Scramble"
    挖通地狱: "Grabe zur Hölle",
    腐乐园: "Verlorenes Paradies",
    喀戎行动: "Operation Chiron",
    // Accessories - 武器配件
    // Weapon Attachments - 武器配件
    // Optics - 瞄具配件
    轻量化红点瞄具: "Leichtes Reflex Visier",
    战斗侦查瞄具: "Aufklärungs Kampfoptik",
    反射式瞄具: "Reflex Visier",
    精准步枪瞄具: "Prezisions Zielfernrohr",
    战术全像瞄准镜: "Taktisches Holographises Visier",
    精准光学瞄具: "Prezisions Visier",
    战术步枪瞄具: "Taktisches Gewehr Visier",
    轻型光学瞄具: "Leichtes Visier",
    中距离战术瞄具: "Mittleres Distanz Visier",
    密封型反射式瞄具: "Sealed Reflex Sight", // How do you translate this (Google Translation: Verriegeltes Reflex Visier)
    紧凑型反射式瞄具: "Compact Reflex Sight",
    棱镜式瞄具: "Prismatic Sight",
    远距离战术瞄具: "Long-Range Tactical Sight",
    大型光学瞄具: "Large Optic Sight",
    紧固型微型红点瞄具: "Fastened Mini Reflex Sight",
    微型红点瞄具: "Mini Reflex Sight",
    先进战斗光学瞄具: "Advanced Combat Optic",
    全像瞄准镜: "Holographic Sight",
    // Muzzle Attachments - 枪口配件
    鱼鹰抑制器: "Osprey Suppressor",
    集成型补偿器: "Integrated Compensator",
    多用途霰弹枪抑制器: "Multi-Use Shotgun Suppressor",
    锤头型补偿器: "Hammer Compensator",
    短型抑制器: "Short Suppressor",
    战术消焰器: "Tactical Flash Hider",
    小型补偿器: "Small Compensator",
    加长型制退器: "Extended Brake",
    一体式抑制器: "Integrated Suppressor",
    小型制退器: "Small Muzzle Brake",
    一体式消焰器: "Integrated Flash Hider",
    //"多孔式消焰器": "", // Multi-Hole Flash Hider
    伪装用抑制器: "Camouflage Suppressor",
    大型抑制器: "Large Suppressor",
    大型枪口制退器: "Large Brake",
    前向消焰器: "Forward Flash Hider",
    消焰器: "Flash Hider",
    轻量化制退器: "Light Brake",
    基础抑制器: "Basic Suppressor",
    紧凑型制退器: "Compact Brake",
    霰弹枪制退器: "Shotgun Brake",
    // Tactial Attachments - 战术配件
    小型红外指示器: "Mini Reflex Sight, Small Infrared",
    前护手握把: "Front Guard Grip",
    后护手握把: "Back Guard Grip",
    大型激光指示器: "Large Laser Sight",
    集成型激光指示器: "Integrated Laser Sight",
    角型握把: "Triangle Grip",
    战术激光指示器: "Tactical Laser Sight",
    小型激光指示器: "Small Laser Sight",
    轻质前握把: "Light Front Grip",
    轻质水平握把: "Light Horizontal Grip",
    战术手电筒: "Tactical Flashlight",
    红外指示器: "Infrared Indicator",
    紧凑型红外指示器: "Compact Infrared Indicator",
    战术组合握把: "Tactical Combine Grip",
    眼镜蛇握把: "Cobra Grip",
    垂直握把: "Vertical Grip",
    紧凑型手电筒: "Compact Flashlight",
    激光指示器: "Laser Sight",
    折叠脚架: "Folding Bipod",
    // Magazines - 弹匣配件
    狙击枪战术弹匣: "Tactical SR Mag",
    轻机枪校准弹鼓: "Calibrated LMG Drum Mag",
    狙击枪改良弹匣: "Amended SR Mag",
    步枪轻量化弹匣: "Light Rifle Mag",
    冲锋枪加重型弹匣: "Weighted SMG Mag",
    轻机枪大型弹鼓: "Large LMG Drum Mag",
    手枪战术型弹匣: "Tactical Pistol Mag",
    冲锋枪战术型弹匣: "Tactical SMG Mag",
    步枪扩容弹匣: "Extended Rifle Mag",
    手枪加长型弹匣: "Extended Pistol Mag",
    手枪改良弹匣: "Amended Pistol Mag",
    冲锋枪改良弹匣: "Amended SMG Mag",
    步枪改良弹匣: "Amended Rifle Mag",
    // Puzzle Types
    异常门扉: "Türen Puzzle",
    异常路牌: "Zerstörte Werbetafel",
    广告牌异常: "Zerstörte Werbetafel",
    破碎山石异常: "Zerstörbarer Stein",
    异常电话亭: "Telefon Zelle",
    异常雕像: "Statue Puzzle",
    黑水相机: "Kamera Emote",
    //"": "Compact Brake (needs Mysterious Painting)",
    "诡谲画作: 小型制退器": "Small Muzzle Brake (needs Mysterious Painting)",
    "诡谲画作: 轻型光学瞄具": "Light Optic (needs Mysterious Painting)",
    "诡谲画作: 小型激光指示器": "Small Laser Sight (needs Mysterious Painting)",
    "诡谲画作: 战术步枪瞄具":
      "Tacticle Rifle Scope (needs Mysterious Painting)",
    "诡谲画作: 前向消焰器": "Forward Flash Hider (needs Mysterious Painting)",
    // Attachment Dupes with Spelling differences
    战斗侦察瞄具: "Recon Combat Optic",
    眼镜蛇握把: "Cobra Grip",
    "反射式瞄具·黑色": "Reflex Sight",
    角形握把: "Triangle Grip",
    霰弹枪式制动器: "Shotgun Brake",
    密封型反射瞄具: "Sealed Reflex Sight",
    "多用途霰弹枪抑制器(6226,-588)": "Multi-Use Shotgun Suppressor (6226,-588)", // Keep coordinates when available
    "大型光学瞄具,黑心地带(3039,990)": "Large Optic Sight (3039,990)",
    "大型光学瞄具,黑心地带(3037,-979)": "Large Optic Sight (3037,-979)",
    手枪加强型弹匣: "Extended Pistol Mag",
    "诡谲画作：小型制退器": "Small Muzzle Brake (needs Mysterious Painting)",
    "诡谲画作：轻型光学瞄具": "Light Optic (needs Mysterious Painting)",
    "诡谲画作：小型激光指示器": "Small Laser Sight (needs Mysterious Painting)",
    "诡谲画作：战术步枪瞄具":
      "Tacticle Rifle Scope (needs Mysterious Painting)",
    "诡谲画作：前向消焰器": "Forward Flash Hider (needs Mysterious Painting)",
    "诡谲画作:战术步枪瞄具": "Tacticle Rifle Scope (needs Mysterious Painting)",
    // Item Categories - 手枪
    手枪: "Pistolen",
    霰弹枪: "Schrotflinten",
    冲锋枪: "MPs", // Submachine Guns
    步枪: "Gewehre",
    狙击枪: "Scharfschützen Gewehre",
    轻机枪: "LMGs", // Light Machine Guns
    弓弩: "Armbrust",
    重型火器: "Schwere Waffen",
    刀剑: "Nahkampf Waffen",
    头盔: "Helme",
    面部: "Masken", // Face
    上身: "Westen", // Top
    下身: "Hosen", // Bottom
    手套: "Handschuhe",
    鞋子: "Schuhe",
    瞄具配件: "Visiere",
    枪口配件: "Mündungs Anbauteile",
    战术配件: "Taktische Anbauteile",
    弹匣配件: "Magazine",
    碎弹模组: "Shrapnel Modifikationen",
    霜寒模组: "Frost Wirbel Modifikationen",
    爆弹模组: "Unstabiler Bomber Modifikationen",
    电涌模组: "Stromstoß Modifikationen",
    标记模组: "Das Bullenauge Modifikationen",
    弹射模组: "Abprall Modifikationen",
    快枪手模组: "Schneller Schütze Modifikationen",
    灼烧模组: "Verbrennung Modifikationen",
    阵地模组: "Festungskrieg Modifikationen",
    武器通用: "Waffenkompatibel", // ?
    头盔模组: "Helme Modifikationen",
    面部模组: "Masken Modifikationen", // Face Mods
    上身模组: "Westen Modifikationen", // Top Mods
    下身模组: "Hosen Modifikationen", // Bottom Mods
    手套模组: "Handschuhe Modifikationen",
    鞋子模组: "Schuhe Modifikationen",
    防具通用: "Panzerung Kampatibel", // ?
    近战通用: "Nahkampf General", // ?
    流派效果: "Genre Effekt", // ?
    模组后缀: "Module Suffixes", // ?
    元素伤害: "Elementar Schaden", // ?
    特殊子弹: "Spezial Geschosse", // ?
    套装碎片: "Set Fragmente",
    素材: "Materiale",
    近战蓝图: "Nahkampf Waffen Baupläne",
    手枪蓝图: "Pistolen Baupläne",
    霰弹枪蓝图: "Schrotflinten Baupläne",
    冲锋枪蓝图: "MP Baupläne", // Submachine Gun Blueprints
    步枪蓝图: "Gewehr Baupläne",
    狙击枪蓝图: "Scharfschützen Gewehr Baupläne",
    轻机枪蓝图: "LMG Baupläne", // Light Machine Gun Blueprints
    弓弩蓝图: "Armbrust Baupläne",
    家具配方: "Möbel Baupläne",
    肉类: "Fleisch",
    鱼类: "Fisch",
    药草: "Kräuter",
    // Recepies - 食谱
    "食谱：熏肉罗宋汤": "Rezept: Borscht Deluxe",
    "食谱：畸变塔可卷": "Rezept: Tacco", // In World item says Herbal Tea
    "食谱：星尘茶": "Rezept: Sternenstaub Tee",
    "食谱：培根肉排汉堡": "Rezept: Bacon Burger",
    "食谱：南瓜星空派": "Rezept: Stargazy Pie",
    "食谱：消脂果汁": "Rezept: Fat-Burning Juice",
    "食谱：安全三明治": "Rezept: Safety Sandwich",
    "食谱：星尘水果罐头": "Rezept: Assorted Canned Food",
    "食谱：星尘通心粉罐头": "Rezept: Sternenstaub Italian Soup Can",
    "食谱：奇迹茶": "Rezept: Wunder Tea",
    "食谱：碎裂面包": "Rezept: Shattered Bread",
    "食谱：星尘南瓜泥沙拉": "Rezept: Sternenstaub Pumpkin Salad",
    "食谱：幽光蘑菇罐头": "Rezept: Spectral Canned Mushroom",
    "食谱：星尘炸肉": "Rezept: Mixed Fried Hot Dog",
    "食谱：元宝饺子": "Rezept: Yuanbao Dumplings",
    "食谱：深海鱼片披萨": "Rezept: Stargazy pizza",
    "食谱：炸薯条": "Rezept: French Fries",
    "食谱：反重力奶昔": "Rezept: Anti-gravity Milkshake",
    "食谱：金钱饼": "Rezept: Croquette",
    "食谱：特调冰酿": "Rezept: Signature Ice Brew",
    "食谱:奇思妙想饮": "Rezept: Whimsical Drink",
    "食谱：炸鱼薯条": "Rezept: Fish & Chips",
    "食谱：幽灵饼干": "Rezept: Ghost Cookies",
    "食谱：畸变带骨香肠": "Rezept: Bone-in Deviated Sausage",
    "食谱：捕获之汤": "Rezept: Sicherungs Soup",
    "食谱：蜜酿炖肉": "Rezept: Honey Glaced Meat",
    // Deviants - 收容物  // Full section has to be translated by someone playing the game with their language set to German
    远归之蝶: "Butterfly's Emissary",
    活体凝胶: "Festering Gel",
    荣枯种子: "Harveseed",
    捕梦网: "Dreamcatcher",
    低语亡骨: "Canine Skull",
    电鳗: "Electric Eel",
    迪斯科球: "Disco Ball",
    发条青蛙: "Frog the Leaper",
    极寒水母: "Polar Jelly",
    青龙: "Chefosaurus",
    蜂团团: "Buzzy Bee",
    工号37: "H37",
    //"": "Fetch-A-Lot Bunny",
    姜饼屋: "Gingerbread House",
    //"": "Atomic Lighter",
    凝视的黑猫: "Enchanted Void",
    木工河狸: "Logging Beaver",
    空间魔方: "Space Turner",
    元素小子: "Digby Boy",
    //"": "Snow Globe",
    //"": "Growshroom",
    皆斩: "Zeno-Purifier",
    门扉: "Strange Door",
    //"": "Party Monkey",
    巫毒娃娃: "Voodoo Doll",
    炎之精: "Flame Essence",
    破碎少女: "Shattered Maiden",
    //"": "Mini Wonder",
    异维大猫: "Extradimensional Cat",
    球状闪电: "Orb Lightning",
    迷你黄衣: "Mini Feaster",
    小纸人: "Paper Doll",
    //"": "Lethal Rabit",
    //"": "Artisan's Touch",
    愿望先生: "Mr Wish",
    红龙: "Pyro Dino",
    //"": "Dr. Teddy",
    恶臭球根: "Grumpy Bulb",
    空之子: "By-The-Wind",
    //"": "Lava Fox",
    胡桃夹子: "Nutcracker",
    //"": "Wish Machine",
    蝶之梦: "Rebecca",
    气球狗: "Pup Buddy",
    一碗美味: "Hug-In-A-Bowl",
    //"": "Masonic Pyramid",
    // Mysterious Painting - 诡谲画作
    "诡谲画作·代顿湿地": "Mysterious Painting · Dayton Wetlands",
    "诡谲画作·破碎三角洲": "Mysterious Painting · Broken Delta",
    "诡谲画作·铁锈河": "Mysterious Painting · Iron River",
    "诡谲画作·垩峰山": "Mysterious Painting · Chalk Peak",
    "诡谲画作·孤狼荒原": "Mysterious Painting · Red Sands",
    "诡谲画作·黑心地带": "Mysterious Painting · Blackheart",
    // Ores
    //"": "Stein",
    硫磺: "Schwefel",
    铜矿: "Kupfer Erz",
    锡矿: "Zinn Erz",
    锡矿富集区: "Zinn Erz Umgebung",
    铁矿: "Eisen Erz",
    铝矿: "Aluminum Erz",
    钨矿: "Wolfram Erz",
    银矿: "Silber Erz",
    银矿区域: "Silber Erz Umgebung",
    "银矿(稀有)": "Silber Erz (Zufällig)",
    "银矿 (稀有)": "Silber Erz (Zufällig)",
    金矿: "Gold Erz",
    金矿区域: "Gold Erz Umgebung",
    "金矿(稀有)": "Gold Erz (Zufällig)",
    "金矿 (稀有)": "Gold Erz (Zufällig)",
    "金矿（先锋服)": "Gold Mine",
    星尘矿: "Sternenstaub Erz",
    星尘矿石: "Sternenstaub Erz",
    星尘矿区: "Sternenstaub Erz Umgebung",
    星尘矿区域: "Sternenstaub Erz Umgebung",
    "星尘矿(稀有)": "Sternenstaub Erz (Zufällig)",
    "星尘矿 (稀有)": "Sternenstaub Erz (Zufällig)",
    // Plants
    橘子: "Orangen",
    果蔬篮橘子: "Orangen",
    小麦: "Weizen",
    果蔬篮小麦: "Weizen",
    红色浆果: "WeißdornbeereH",
    卷心菜: "Grün Kohl",
    果蔬篮卷心菜: "Grün Kohl",
    甜菜: "Rote Bete",
    果蔬篮甜菜: "Rote Bete",
    蓝莓: "Blaubeere",
    南瓜: "Kürbis",
    果蔬篮南瓜: "Kürbis",
    玉米: "Mais",
    果蔬篮玉米: "Mais",
    土豆: "Kartoffel",
    果蔬篮土豆: "Kartoffel",
    蘑菇: "Pilz",
    果蔬篮蘑菇: "Pilz",
    //"": "Gurke",
    //"": "Tomate",
    //"": "Rote Tulpe",
    //"": "Gelbe Tulpe",
    //"": "Yellow Hydrangea",
    //"": "Blue Hydrangea",
    //"": "White Petunia",
    //"": "Blue Petunia",
    芦荟: "Aloe Vera",
    "鼠尾草 * 5": "Traube * 5",
    "鼠尾草 * 8": "Traube * 8",
    桔梗: "Bellflower",
    金银花: "Honeysuckle",
    "金银花 * 3": "Honeysuckle * 3",
    "金银花 * 4": "Honeysuckle * 4",
    藏红花: "Saffran",
    血菖蒲: "Scarlet Calamus",
    紫锥菊: "Coneflower",
    黄莲花: "Gelber Lotus",
    //"": "Pfeffer",
    苹果: "Apfel",
    苹果树: "Apfel Baum",
    "苹果树 * 2": "Apfel Baum * 2",
    //"": "Kaktus",
    葡萄: "Grapes",
    贝壳岩石: "Shell Stein",
    海草岩石: "See Tang Stein",
    观赏性花海: "See der Blumen",
    香蕉树: "Bananen Baum",
    "香蕉树 * 2": "Bananen Baum * 2",
    "香蕉树 * 4": "Bananen Baum * 4",
    "香蕉树 * 6": "Bananen Baum * 6",
    "香蕉树 * 7": "Bananen Baum * 7",
    椰子树: "Kokosnuss Baum",
    "椰子树 * 3": "Kokosnuss Baum * 3",
    巨木: "Gigantischer Baum",
    "龙血树(巨木)": "Gigantischer Baum",
    // Animals
    野生动物: "Tiere",
    兔子窝: "Hasen Loch",
    鹿: "Reh",
    星蚀鹿群: "Reh",
    星蚀雄鹿: "Reh",
    星蚀雌鹿: "Reh",
    野猪: "Bär",
    野猪群: "Bär",
    星蚀鳄: "Alligator",
    羊群: "Flock",
    花豹: "Leopard",
    星蚀熊窝: "Bear's Den",
    星蚀熊: "Bär",
    肉排: "Steak",
    鳄鱼蛋: "Alligator Eier",
    鸟蛋: "Fogel Eier",
    // Oil Wells
    原油油井: "Öl Pumnpe",
    // Echo Stone - 回响石
    // has no individual names
    // Hints - 留言
    别靠近箱子: "Mimic",
    地堡门禁卡: "Bunkerzugangskarte",
    吓人箱子: "Mimic",
    空间异动: "Weltraumanomalie",
    地下入口: "Unterirdischer Eingang",
    电话亭: "Telefonzelle",
    拟态怪储物箱: "Mimic",
    拟态宝箱怪: "Mimic",
    "密码: 5897": "Passwort: 5897",
    "密码: 325": "Passwort: 325",
    地下通道入口: "Unterirdischer Eingang",
    地下通道最近入口: "Unterirdischer Eingang",
    地窖入口: "Unterirdischer Eingang",
    山洞入口: "Hölen Eingang",
    溶洞入口: "Hölen Eingang",
    镜女: "Spiegel Gegner",
    拟态储物箱别开: "Mimic",
    "电梯：负一层": "Aufzug: Unterirdisches Level 1",
    拟态宝箱怪别开: "Mimic",
    空间异常: "Weltraumanomalie",
    "5层楼梯": "5 Treppen",
    箱子怪别开: "Mimic",
    下楼电梯: "Aufzug",
    下楼电梯位置: "Aufzug",
    隐藏宝箱最后位置: "Schatzkiste",
    抽屉柜: "Schrank",
    // Side Quests - 隐藏任务
    //"": "A Miracle Chase",
    隐藏的宝箱: "Morphische Kiste Tutorial", //
    //"异常档案": "",//Abnormal Files?
    //"": "The Shadowed Lighthouse",
    玩具小熊: "Der Ruf der Kindheit",
    "急救！急救！": "Dayton Krankenhaus",
    //'"玩具熊"女孩': "", //Teddy Bear Girl?
    //"": "Erntezeit",
    //"": "Die verlorene Dame",
    //"": "Experte für Abweichung",
    //"": "Die Heimat des kriegerischen Gottes",
    信徒的藏宝图: "Lost In Madness - Ausgangspunkt",
    信徒的财产箱: "Lost In Madness - Fundort des Schatzes",
    //"": "Infiltration von Sternenstaub",
    //"": "Ein Akt des Diebstahls",
    检测点见闻: "Skizze eines Prüfpunktes",
    //"": "Zuleitung",
    //"": "Wo Katze und Mäuse spielen",
    红与黑: "Karneval des Verderbens",
    //"": "Der unendliche Schatz",
    //"": "Liebe, Trauer",
    //"": "Fremdes Gestein",
    //"": "Unvollendete Expedition",
    //"": "Eintagsfliege-Abzeichen",
    //"": "Geheime Geschmacksrichtungen",
    //"": "Save Meta-Human",
    //"": "Willkommen!",
    //"": "Junge will einfach nur Spaß haben",
    //"": "Für Sarah",
    //"": "Ein überfälliges Geschenk",
    //"": "Experimentelles Material",
    //"女儿的问候": "", //Grüße von meiner Tochter?
    //"": "Rein in den Wahnsinn",
    //"": "Grummelnder Aasfresser",
    //"": "sicher oder nicht sicher",
    //"寻找记忆": "", //Searching for memories?
    //"": "Save Meta-Human",
    被丢弃的玩偶: "Annas Spielzeug",
    //"": "Zufallsbegegnung: Willkommen an Bord
    艺术家的钥匙: "Kultistentreffen - Ausgangspunkt",
    信徒的宝箱: "Kultistentreffen - Schatzort",
    特别关系: "Eine besondere Beziehung",
    //"嘉莲": "",
    生日快乐: "Happy Birthday",
    //"": "Kleiner Laden der Freundlichkeit",
    招财猫开始点: "Lucky Cat - Ausgangspunkt",
    招财猫1号: "Glückskatze 1#",
    招财猫2号: "Glückskatze 2#",
    招财猫3号: "Glückskatze 3#",
    招财猫给予的宝箱: "Lucky Cat - Fundort des Schatzes",
    好消息坏消息: "Von Freude und Trauer - Ausgangspunkt",
    神婆的宝箱: "Von Freude und Trauer - Treasure Location",
    //"成就：一览众山小": "",//Achievement: Eine Sicht auf die Welt?
    农庄惊魂: "Horror auf dem Bauernhof",
    限定版牛奶: "limitierte edition",
    考古学家的馈赠: "Sei wahr bis zum Tod",
    遗留财产: "Ein Familienerbe",
    悲伤画像: "Trauriges Porträt",
    //"罗塞塔保险箱": "", //Rosetta Tresor?
    "密码：9274": "Password: 9274", //Wirklich eine Nebenquest?
    秘密配方: "Recipe", //Wirklich eine Nebenquest?
    // Merchant - 商人
    韦伯: "Weber",
    赵金潭: "Zhao Jintan",
    //"": "Jonathan",
    //"": "Emma Potter",
    拟态体商店: "Severin VII-S2041 (SIRA Trader)",
    //"": "Nisa (Sproutlet Trader)",
    鱼饵商人: "Margerie (Fish Merchant)",
    "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie【Fish Blueprints】",
    // Livable Location - 宜居地点
    // Livable Location are the recommended places to live with subjective opinions, These are usually large flat areas with rich resources and close to water sources.
    // has no individual names
    // Not sure where/if the following are used.
    异常点: "Abnormales Object",
    稀有: "selten",
    持续刷新: "Kontinuierliche Aktualisierung",
    碧湖山庄: "Greenlake Hill",
    检测点91: "Untersuchungs Punkt 91",
    戴维思角: "Davis Punkt",
    检测点24: "Untersuchungs Punkt 24",
    翻车鱼岛旅客中心: "Mola Island Besucher zentrum",
    治炼厂污染点: "Plan zur Verschmutzung der Raffinerie",
    检测点3711: "Untersuchungs Punkt 3711",
    // 2024/08/17
    翠湖山镇: "Greenlake Hill",
    无蘑菇: "kein Pilz",
    果蔬箱土豆: "Kartofel",
    油田区域: "Oilfield Area",
    抽水泵采集: "Pumpe",
    洞穴内: "Innerhalb der Höhle",
    便携式燃油: "Portabler Treibstoff",
    腐化熊: "Bär",
    水豚: "Capybara",
    狼: "Wolf",
    鳄鱼: "Krokodil",
    长嘴海鸥: "Long-Billed Seagull",
    海龟: "See Turtle",
    鹈鹕: "Pelikan",
    兔子: "Hase",
    鳄龟: "Schnappschildkröte",
    狐狸: "Fuchs",
    浣熊: "Waschbär",
    火烈鸟: "Flamingo",
    腐化鳄: "Korruptes Krokodil",
    腐化狼: "Korruptes Wolf",
    白斑狗鱼钓鱼点: "Europäischer Hecht",
    白斑狗鱼: "Europäischer Hecht",
    海鲈鱼: "Seebarsch",
    神仙鱼: "Skalar",
    长吻雀鳝: "Langnase Gar",
    黑鲈: "Schwarzbarsch",
    孔雀鱼: "Guppy",
    鲤鱼: "Karpfen",
    图丽鱼: "Astronotus Ocellatus",
    太阳鱼: "Lepomis",
    锦鲤: "Koi",
    龙鱼: "Arowana",
    鳙鱼: "Großkopf Karpfen",
    沙丁鱼: "Sardine",
    梭鱼: "Barracuda",
    鲭鱼: "Makerele",
    罗非鱼: "Tilapia",
    虹鳟: "Regenbogenforelle",
    鲑鱼: "Lachs",
    鲳鲹: "Pompano",
    松鼠: "Eichhörnchen",
    亚口鱼: "Sucker", // Needs someone who can tranlate this since i've only played the game while language is set english
    // scenario
    "PvE-天空之触": "PvE-MANIBUS",
    "PvP-分歧之路": "PvP-Evolution's Call",
    // map
    "玩家": "Player"
  },
};
