export default {
    "buttons": {
        "filter": "Filtrar",
        "select_all": "Selecionar Tudo",
        "deselect_all": "Desmarcar Tudo",
        "close": "Fechar",
        "move_left": "Mover para a Esquerda",
        "move_right": "Mover para a Direita",
        "edit": "Editar",
        "quit": "Sair",
        "apply": "Sim",
        "cancel": "Não"
    },
    "edit": {
        "mode_switch": "Entrar/sair do modo de edição?"
    },
    "tabs": {
        "by_category": "Categoria",
        "by_item": "Item",
        "by_search": "Pesquisar",
        "resource_list": "Recursos",
        "setting": "Configurações",
        "user_data": "Dados do Usuário",
        "quick_setting": "Configurações Rápidas",
        "quick_setting_fuel_loot": "Combustível",
        "quick_setting_resource": "Recurso",
        "quick_setting_bus_route": "Rota do Ônibus Monstro",
        "quick_setting_show_players": "Mostrar Jogadores",
        "quick_setting_pollution": "Poluição",
        "quick_setting_popup_coordinate": "Coordenada Segue o Cursor",
        "quick_setting_disaster_area": "Área de Desastre Tecelão do Caos",
        "area": "Áreas",
        "treasure": "Tesouros",
        "monster": "Explorar",
        "collection": "Coleção",
        "hint": "Dica",
        "logged": "Dados",
        "guest": "Login",
        "oneclick_delete_enable": "Um Clique",
        "oneclick_delete_disable": "Desativar",
        "oneclick_delete_badge": "Modo Um Clique Ativado",
        "oneclick_delete_hint1": "Ao ativar, clicar em um marcador não exibirá mais uma janela pop-up, mas irá deletar ou restaurar diretamente o marcador.",
        "oneclick_delete_enable_hint": "Modo de exclusão com um clique ativado",
        "oneclick_delete_disable_hint": "Modo de exclusão com um clique desativado",
        "oneclick_delete_dialog_title": "Aviso",
        "oneclick_delete_dialog_content": "Ao ativar o modo de exclusão com um clique, nenhuma janela será exibida ao clicar em um marcador no mapa. O marcador será deletado ou restaurado diretamente. Deseja continuar?",
        "oneclick_delete_dialog_close": "Fechar",
        "oneclick_delete_dialog_confirm": "Confirmar",
        "batch_editing_enable": "Progresso",
        "batch_editing_disable": "Sair",
        "batch_editing_hint": "Você pode deletar ou restaurar todos os marcadores de uma categoria. É necessário fazer login para usar.",
        "setting_btn_hint": "Configurações relacionadas ao mapa",
        "login_btn_hint": "Gerenciar meus dados",
        "back_to_categories": "Voltar para Categorias",
        "display_area": "Filtro de Área",
        "select_item_category": "Selecionar",
        "related_items": "Itens Relacionados",
        "locate_item": "Clique no item para localizar",
        "search_resources": "Pesquisar Recursos",
        "input_resource_name": "Digite o nome",
        "locate": "Localizar",
        "any_name": "Qualquer Nome",
        "keyword": "Palavra-chave",
        "locations": "Localizações",
        "locate_point": "Clique para centralizar a Localização",
        "input_item": "Por favor, insira o Nome da Localização",
        "related_item": "Itens",
        "related_makers": "Marcadores",
        "locate_marker": "Clique para centralizar o Marcador",
        "input_marker": "Por favor, insira o Nome do Marcador",
        "related_resources": "Recursos",
        "locate_resource": "Clique para centralizar o Recurso",
        "input_resource_for_searching": "Por favor, insira o Nome do Recurso"
    },
    "floor_text": {
        "roof": "( Telhado )",
        "at_floor": "( Andar {floor} )",
        "underground": "( Subsolo {floor} )",
        "level": "( Nível {level} )"
    },
    "settings": {
        "has_video": "Marcador de Vídeo",
        "deleted_marker": "Marcador Deletado",
        "map_area_style": "Estilo da Área do Mapa",
        "monster_bus_route": "Rota do Ônibus Monstro",
        "marker_text": "Texto do Marcador",
        "resource_area": "Área de Recursos",
        "last_updated_datetime": "Hora da Última Atualização do Marcador",
        "icon_drawing_method": "Método de Desenho do Ícone (Canvas é Recomendado quando o ícone está quebrado)",
        "dark_mode": "Modo Escuro",
        "language": "Idioma",
        "auto_query": "Consultar quando as Categorias Mudarem",
        "auto_draw_marker_after_search": "Exibir o Resultado da Pesquisa no Mapa",
        "show": "Mostrar",
        "hide": "Ocultar",
        "line_style": "Estilo da Linha",
        "area_style": "Estilo de Preenchimento",
        "wasm": "Wasm (Melhor Desempenho)",
        "canvas": "Canvas (Melhor Compatibilidade)",
        "on": "Ativado",
        "off": "Desativado",
        "draw_text_mode": "Estilo do Texto do Marcador",
        "draw_text_mode_1": "Completo",
        "draw_text_mode_2": "Simplificado",
        "deleted_marker_style": "Estilo do Marcador Deletado",
        "deleted_marker_style_1": "Cruz",
        "deleted_marker_style_2": "Translúcido",
        "deleted_marker_style_3": "Ocultar"
    },
    "user_data": {
        "local_storage": "Dados Locais",
        "count": "sem registros | {count} registro | {count} registros",
        "local_storage_tutorial": "Tutorial",
        "backup": "Backup e Restauração",
        "local_storage_text": "Você pode deletar qualquer marcador sem login. Mas os dados serão armazenados apenas no navegador atual. Você pode fazer backup dos dados e transferi-los para outro navegador.",
        "backup_placeholder": "Dados",
        "backup_button": "Fazer Backup",
        "restore_button": "Restaurar",
        "cloud_storage": "Dados na Nuvem",
        "clear_all_data": "Deletar Todos os Dados",
        "restore_hint": "Dica: Esta operação irá mesclar os dados locais com os dados importados. Se você estiver logado, os dados também serão sincronizados com a nuvem. Deseja continuar?",
        "delete_hint": "Você tem certeza que deseja deletar todos os dados? Se você já estiver logado, os dados na nuvem também serão apagados. Deseja continuar?",
        "wechat_login": "WeChat",
        "wechat_mp_login": "WeChat2",
        "discord_login": "Discord",
        "login_tutorial": "Tutorial de Login",
        "login_tutorial_text": "Após fazer login, os dados locais e na nuvem serão automaticamente sincronizados, permitindo que você continue usando em qualquer navegador e dispositivo. Você também pode usar sem fazer login, mas os dados só poderão ser armazenados no navegador local.",
        "not_login": "Não logado",
        "login_success": "Você fez login com sucesso",
        "data_is_syncing": "Os dados estão sendo sincronizados",
        "last_syncing_time": "Última Sincronização: ",
        "logout": "Sair"
    },
    "marker_dialog": {
        "no_marker_img": "Sem Imagens",
        "delete_markder": "Deletar Marcador",
        "undelete": "Restaurar",
        "delete_only": "Somente Deletar",
        "hide_category": "Ocultar {category}",
        "no_update_time": "Sem hora de atualização",
        "rewards": "Recompensas",
        "close": "Fechar",
        "detail": "Detalhe",
        "operation": "Operação",
        "timer_title": "Timer de Redefinição do Baú",
        "timer_title_not_login": "(Necessita Login) Timer de Redefinição do Baú",
        "deviant_timer_title": "Timer de Redefinição do Anômalo",
        "to_login": "Faça login para desbloquear o recurso de timer",
        "comment": "Comentários",
        "auto_set_timer": "Configurar Timer Automaticamente",
        "auto_set_timer_not_login": "(Necessita Login) Configurar Timer Automaticamente",
        "timer_tutorial": "Tutorial do Timer",
        "sharing": "Compartilhar",
        "session_script": "Atualmente disponível em: ",
        "hint": "[ Dica ]",
        "sharing_hint": "O link compartilhado exibirá automaticamente o marcador ao ser aberto.",
        "download_qr_code": "Baixar",
        "sharing_link": "Link",
        "copy": "Copiar",
        "update": "Atualizado",
        "guide": "Guia",
        "donate": "Doar",
        "auto_reset_help_title": "Ajuda",
        "auto_reset_help_text": "O horário fixo de atualização dos baús de armas e equipamentos começa às 00:00:00 e atualiza a cada 4 horas em ponto. Se você ainda não conseguir abrir os baús no horário de atualização, basta fazer login novamente.",
        "auto_reset_help_ok": "OK",
        "click_to_copy": "Clique para Copiar",
        "copied_successfully": "Copiado com Sucesso",
        "common_hint": "Dicas Gerais"
    },
    "donate": {
        "payment": "Please scan the QR code using WeChat",
        "text": "Your support can help the website continue to operate and update more features",
        "warning": "Minors are prohibited from donating"
    },
    "scenario": {
        "not_available": "Não Disponível",
        "current": "Atual",
        "available": "Disponível",
        "coming": "Chegando",
        "scenarios": "Cenários"
    },
    "languages": {
        "dialog_title": "Selecionar Idioma",
        "dialog_close": "Fechar",
        "contributors": "Contribuidores",
        "help_1": "Não encontoru o idioma que você está procurando?",
        "help_2": "Clique aqui para ajudar a melhorar as traduções",
        "default": "Default"
    },
    "categories": {
        "传送塔": "Teletransportador",
        "巨楔": "Monólito",
        "主城": "Assentamento",
        "研究所": "Laboratório",
        "大型资源点": "Cidade",
        "小型资源点": "Vila",
        "收容井": "Silo de Contenção",
        "位面锚": "Âncora Dimensional",
        "空间锚点": "Âncora Espacial",
        "观景点": "Ponto de Observação",
        "神秘宝藏": "Caixa Mística",
        "神秘宝箱": "Caixa Mística",
        "武器箱": "Caixa de Armas",
        "装备箱": "Caixa de Equipamentos",
        "隐藏宝箱": "Caixa Oculta",
        "秘藏宝箱": "Baú de Tesouro Oculto",
        "宝箱怪": "Caixa Mórfica",
        "储物箱": "Caixa de Armazenamento",
        "精英怪": "Elite",
        "迷雾区域": "Evento de Névoa",
        "防守工坊": "Oficina",
        "移动房屋": "Casa Móvel",
        "限时事件": "Evento Vermelho",
        "灭绝者": "Tecelão do Caos",
        "灭绝者(二阶段)": "Tecelão do Caos (Fase 2)",
        "灭绝者(三阶段)": "Tecelão do Caos (Fase 3)",
        "冰灭绝者(一阶段)": "Tecelão do Caos de Gelo (Fase 1)",
        "冰灭绝者(二阶段)": "Tecelão do Caos de Gelo (Fase 2)",
        "冰灭绝者(三阶段)": "Tecelão do Caos de Gelo (Fase 3)",
        "冰灭绝者(二/三阶段)": "Tecelão do Caos de Gelo (Fase 2/3)",
        "冰灭绝者(一/四阶段)": "Tecelão do Caos de Gelo (Fase 1/4)",
        "冰灭绝者(二/四阶段)": "Tecelão do Caos de Gelo (Fase 2/4)",
        "冰灭绝者(三/四阶段)": "Tecelão do Caos de Gelo (Fase 3/4)",
        "冰灭绝者(二/三/四阶段)": "Tecelão do Caos de Gelo (Fase 2/3/4)",
        "冰灭绝者(四阶段)": "Tecelão do Caos de Gelo (Fase 4)",
        "火灭绝者(二阶段)": "Tecelão do Caos de Fogo (Fase 2)",
        "火灭绝者(三阶段)": "Tecelão do Caos de Fogo (Fase 3)",
        "火灭绝者(四阶段)": "Tecelão do Caos de Fogo (Fase 4)",
        "火灭绝者(一/四阶段)": "Tecelão do Caos de Fogo (Fase 1/4)",
        "火灭绝者(二/四阶段)": "Tecelão do Caos de Fogo (Fase 2/4)",
        "火灭绝者(三/四阶段)": "Tecelão do Caos de Fogo (Fase 3/4)",
        "火灭绝者(二/三/四阶段)": "Tecelão do Caos de Fogo (Fase 2/3/4)",
        "武器配件": "Acessório",
        "食谱": "Receita",
        "收容物": "Desviante",
        "诡谲画作": "Pintura Misteriosa",
        "矿物点": "Minério",
        "采集点": "Material",
        "种子箱": "Baú de Sementes",
        "调味料箱": "Baú de Temperos",
        "种子香料": "Sementes e Temperos",
        "饮料机": "Máquina de Bebidas",
        "随机素材箱": "Baú Aleatório",
        "抗菌剂箱": "Baú de Medicamentos",
        "回响石": "Pedra de Eco",
        "留言": "Dica",
        "隐藏任务": "Missão Oculta",
        "支线任务": "Missão Secundária",
        "商人": "Comerciante",
        "宜居地点": "Local Habitável",
        "代顿湿地": "Pântanos de Dayton",
        "破碎三角洲": "Delta Quebrado",
        "垩峰山": "Pico de Giz",
        "铁锈河": "Rio Ferrugem",
        "孤狼荒原": "Deserto de Areias Vermelhas",
        "黑心地带": "Território Coração Negro",
        "玛瑙冻原": "Tundra Ônix",
        "维纳峡湾": "Fiorde Vena",
        "余烬滩": "Praia das Brasas",
        "怪物巴士路线": "Ônibus dos Monstros",
        "便携混合燃油": "Combustível Misto Portátil",
        "污染区": "Área Contaminada",
        "污染值": "Nível de Poluição",
        "建筑无法幸存": "Edifício não pode sobreviver",
        "建筑会受损": "Edifício será danificado",
        "被发现范围": "Alcance de Alerta",
        "猎犬岛传送塔": "Torre de Teletransporte",
        "望岛镇传送塔": "Torre de Teletransporte",
        "离岸广场传送塔": "Torre de Teletransporte",
        "临溪东部传送塔": "Torre de Teletransporte",
        "贪欲巨楔传送塔": "Torre de Teletransporte do Monólito da Ganância",
        "代顿检查点传送塔": "Torre de Teletransporte",
        "高岸南部传送塔": "Torre de Teletransporte",
        "西格玛传送塔": "Torre de Teletransporte",
        "暖阳中部传送塔": "Torre de Teletransporte",
        "三角洲南部传送塔": "Torre de Teletransporte",
        "盖亚山区传送塔": "Torre de Teletransporte",
        "盖亚巨楔传送塔": "Torre de Teletransporte do Monólito do Penhasco de Gaia",
        "代顿北部传送塔": "Torre de Teletransporte",
        "高地西部传送塔": "Torre de Teletransporte",
        "盖亚西部传送塔": "Torre de Teletransporte",
        "朽鞍镇传送塔": "Torre de Teletransporte",
        "银滩北部传送塔": "Torre de Teletransporte",
        "翠湖南部传送塔": "Torre de Teletransporte",
        "翠湖北部传送塔": "Torre de Teletransporte",
        "阿尔法传送塔": "Torre de Teletransporte",
        "月湖传送塔": "Torre de Teletransporte",
        "庄园东部传送塔": "Torre de Teletransporte",
        "尖牙巨楔传送塔": "Torre de Teletransporte do Monólito da Sede",
        "蜿蜒山区传送塔": "Torre de Teletransporte",
        "波光北部传送塔": "Torre de Teletransporte",
        "黯梦巨楔传送塔": "Torre de Teletransporte do Monólito da Miragem",
        "风角边境传送塔": "Torre de Teletransporte",
        "谷地南部传送塔": "Torre de Teletransporte",
        "西塔传送塔": "Torre de Teletransporte",
        "黑原中部传送塔": "Torre de Teletransporte",
        "遗忘巨楔传送塔": "Torre de Teletransporte do Monólito Esquecido",
        "悬巢北部传送塔": "Torre de Teletransporte",
        "悬巢南部传送塔": "Torre de Teletransporte",
        "内部传送塔": "Torre de Teletransporte",
        "巨人阶梯传送塔": "Torre de Teletransporte",
        "黑心内弯传送塔": "Torre de Teletransporte da Baía do Coração Negro",
        "冻火湾传送塔": "Torre de Teletransporte da Forja Congelada",
        "冻火北部传送塔": "Torre de Teletransporte do Norte Congelado",
        "鲸骨湾传送塔": "Torre de Teletransporte da Baía da Baleia",
        "山阴传送塔": "Torre de Teletransporte da Sombra da Montanha",
        "水畔传送塔": "Torre de Teletransporte à Beira d'Água",
        "港区传送塔": "Torre de Teletransporte do Distrito do Porto",
        "绿野传送塔": "Torre de Teletransporte do Campo Verde",
        "乐园传送塔": "Torre de Teletransporte da Terra dos Desejos",
        "望海传送塔": "Torre de Teletransporte Vista para o Mar",
        "林场传送塔": "Torre de Teletransporte da Fazenda Florestal",
        "慕斯市传送塔": "Torre de Teletransporte da Cidade do Alce",
        "潮间地传送塔": "Torre de Teletransporte da Ressaca",
        "黑石东部传送塔": "Torre de Teletransporte do Leste da Pedra Negra",
        "黑石北部传送塔": "Torre de Teletransporte do Norte da Pedra Negra",
        "冻原中部传送塔": "Torre de Teletransporte do Centro da Tundra",
        "大河警戒区传送塔": "Torre de Teletransporte da Zona de Exclusão da Taiga",
        "母巢巨穴传送塔": "Torre de Teletransporte da Caverna do Ninho",
        "破碎岩礁传送塔": "Torre de Teletransporte dos Recifes Quebrados",
        "雪崩巨楔传送塔": "Torre de Teletransporte Monólito da Avalanche",
        "雪崖传送塔": "Torre de Teletransporte dos Penhascos Nevados",
        "冻火西部传送塔": "Torre de Teletransporte do Oeste Congelado",
        "烟袋群岛传送塔": "Torre de Teletransporte da Ilha do Cachimbo",
        "蛇眼山口传送塔": "Torre de Teletransporte da Passagem do Olho de Serpente",
        "蛇腹传送塔": "Torre de Teletransporte da Barriga de Serpente",
        "蛇尾传送塔": "Torre de Teletransporte do Rabo de Serpente",
        "熟土区传送塔": "Torre de Teletransporte da Terra Fértil",
        "火喉北部传送塔": "Torre de Teletransporte do Norte da Garganta de Fogo",
        "火喉东部传送塔": "Torre de Teletransporte do Leste da Garganta de Fogo",
        "火喉飞升传送塔": "Torre de Teletransporte Ascensão da Garganta de Fogo",
        "火喉根基传送塔": "Torre de Teletransporte Base da Garganta de Fogo",
        "灰落传送塔": "Torre de Teletransporte Cinzenta",
        "寂火传送塔": "Torre de Teletransporte do Fogo Silencioso",
        "灼风传送塔": "Torre de Teletransporte do Vento Flamejante",
        "硫磺池传送塔": "Torre de Teletransporte da Piscina de Enxofre",
        "炽尘巨楔传送塔": "Torre de Teletransporte do Pó de Fogo",
        "贪欲巨楔": "Monólito da Ganância",
        "盖亚巨楔": "Monólito do Penhasco Gaia",
        "黯梦巨楔": "Monólito do Miragem",
        "尖牙巨楔": "Monólito da Sede",
        "遗忘巨楔": "Monólito Esquecido",
        "冻原巨楔": "Monólito da Tundra",
        "雪崩巨楔": "Monólito da Avalanche",
        "炽尘巨楔": "Monólito do Pó de Fogo",
        "旅人营地": "Deadsville",
        "迈尔集市": "Mercado do Meyer",
        "秽水营地": "Acampamento Greywater",
        "深草旅店": "Pousada de Tall Grass",
        "黑原镇": "BlackFell",
        "遗忘之地": "Oblivion",
        "熊栖雪场": "Pista de Esqui da Toca do Urso",
        "鲸骨乡": "Vila dos Ossos de Baleia",
        "冰屋营地": "Acampamento da Casa de Gelo",
        "不落号坠落点": "Local da Queda dos Sem Queda",
        "生命进化研究所": "Instituto de Evolução HP",
        "”黑域“之门": "Entrada da Zona de Névoa",
        "中途镇": "Throughville",
        "腐烂庄园": "Mansão Podre",
        "橘子镇": "Condado de Cítricos",
        "望岛镇": "Cidade da Vista da Ilha",
        "苏德兰果园": "Pomar da Família Sutherland",
        "离岸广场": "Praça da Costa",
        "临溪": "Brookham",
        "代顿医院": "Hospital Dayton",
        "贪欲巨楔警戒区": "Zona de Perigo do Monólito da Ganância",
        "赫斯特工业": "Indústrias Hearst",
        "海港镇": "Harborside",
        "猎犬岛哨站": "Posto Avançado da Ilha do Cão Selvagem",
        "暖阳中学": "Escola Secundária Sunbury",
        "暖阳镇": "Sunbury",
        "苏德兰化工厂": "Planta Química Sutherland",
        "高岸镇": "High Banks",
        "废弃货场": "Cemitério de Entulho",
        "盖亚研究所遗址": "Ruínas do Centro de Pesquisa Gaia",
        "东部铁路枢纽": "Juncão Ferroviária Leste",
        "盖亚巨楔警戒区": "Zona de Perigo do Monólito do Penhasco Gaia",
        "高地": "Highland",
        "冶炼厂污染点": "Planta de Poluição de Fundição",
        "秽水工业区": "Zona Industrial de Água Suja",
        "阿卡尔克镇": "Alkirk",
        "东黑原枢纽": "Juncão Blackfell Leste",
        "波光镇": "Rippleby",
        "里奇收容点": "Ponto de Apreensão Ricci",
        "黯梦巨楔警戒区": "Zona de Perigo do Monólito do Miragem",
        "盖亚军事基地": "Base Militar Gaia",
        "朽鞍镇": "Rotten Saddle",
        "银滩度假区": "Resort Silvershore",
        "碧湖山镇": "Greenlake Hill",
        "霍特镇": "Holt Town",
        "熔炉巢穴": "Covil da Fornalha",
        "常青藤酒庄": "Vinícola Evergreen",
        "阿尔法研究所": "Instituto Alpha",
        "尖牙巨楔警戒区": "Zona de Perigo do Monólito da Sede",
        "交错现实研究所": "Instituto de Pesquisa de Realidades Alternativas",
        "黑原油田": "Campos de Petróleo Blackfell",
        "黑原陷落区": "Zona de Queda Blackfell",
        "绿荫镇": "Evergreen",
        "悬巢": "Fortaleza Eyrie",
        "73号源质分离点": "Ponto de Extração da Fonte 73",
        "太阳农场": "Fazenda Sunshine",
        "白崖基地": "Base do Penhasco Branco",
        "灼风气象站": "Observatório Scorchwind",
        "炎神研究所": "Centro de Pesquisa do Deus do Fogo",
        "圣城前哨": "Periferia de Firethroat",
        "火喉下城": "Fortaleza Firethroat",
        "灰落车站": "Estação Ashenton",
        "熟土农庄": "Fazenda Ripe Land",
        "蛇尾滑索营地": "Acampamento da Cauda da Serpente",
        "火喉弃民街": "Favelas Firethroat",
        "燃尽之地": "Terra Queimada",
        "废弃提炼厂": "Refinaria Abandonada",
        "攀火祭祀场": "Aspecto do Fogo",
        "望火港": "Porto Firewatch",
        "烟袋度假区": "Resort Tabcco",
        "黑石灯塔": "Farol Obsidian",
        "异火码头": "Porto Pyro",
        "无明港": "Porto Sem Luz",
        "蛇眼瞭望点": "Mirante Eye of the Serpent",
        "蛇腹洞穴": "Caverna Belly of the Serpent",
        "纵队巡逻点": "Ponto de Patrulha Guerrilheiro",
        "硫磺池采伐区": "Pedreira de Enxofre",
        "温泉民宿": "Pousada das Águas Termais",
        "火喉圣域": "Fortaleza Firethroat",
        "冻火湾": "Forja do Gelo",
        "避火者地堡": "Santuário das Chamas",
        "炽尘巨楔警戒区": "Zona de Perigo do Monólito de Fogo e Poeira",
        "“母巢”收容保护区": "Área Restrita Hiverail",
        "雪崩巨楔警戒区": "Zona de Perigo do Monólito de Avalanche",
        "雪原气象站": "Posto de Controle Snowfield",
        "悬空哨卡": "Posto Suspenso",
        "冻原巨楔警戒区": "Zona de Perigo do Monólito da Tundra",
        "检测点653": "Ponto de Inspeção 653",
        "“大河”收容场": "Zona de Abrigo “Grande Rio“",
        "罗塞塔巡逻站": "Posto de Patrulha Rosetta",
        "慕斯市食品厂": "Fábrica de Alimentos da Cidade de Moose",
        "慕斯市": "Cidade de Moose",
        "慕斯市郊废屋": "Casa Abandonada nos Subúrbios de Moose City",
        "栖木岭观景台": "Mirante Perching Tree Prospect",
        "栖木缆车站": "Estação de Teleférico Perching Tree",
        "藏火岩洞": "Caverna Firehide",
        "黑石要塞": "Fortaleza Blackstone",
        "“心愿奇境”西园区": "Wishland Oeste",
        "“心愿奇境”东园区": "Wishland Leste",
        "乐园东入口": "Entrada Leste de Wishland",
        "乐园西入口": "Entrada Oeste de Wishland",
        "滑索洞穴营地": "Acampamento de Caverna Zipline",
        "融冰港": "Porto Icemelt",
        "菲斯库尔港": "Porto Fiskur",
        "影日洞穴": "Caverna Sunshroud",
        "灰落市": "Ashenton",
        "中途镇变电站": "Subestação de Throughville",
        "检测点3771": "Ponto de Inspeção 3771",
        "翻车鱼岛游客中心": "Centro de Visitantes da Ilha Mola",
        "海岬庄园": "Mansão Cape",
        "小码头": "Pequeno Porto",
        "艾尔汽修店": "Oficina de Reparos de Aiden",
        "艾尔的隐蔽所": "Esconderijo de Aiden",
        "检测点7802": "Ponto de Inspeção 7802",
        "临溪警戒所": "Posto de Vigilância de Brookham",
        "代 Dayton 货栈": "Armazém de Dayton",
        "崖下营地": "Acampamento Cliffside",
        "北岸营地": "Acampamento North Shore",
        "赫斯特": "Hearst",
        "赫斯特滩涂": "Pântano de Hearst",
        "湖心野营地": "Acampamento Lakeheart",
        "迈尔": "Meyer",
        "高岸巢穴": "Ninho Highbank",
        "废弃隐蔽所": "Esconderijo Abandonado",
        "骑士修车店": "Oficina de Reparos Knight",
        "山脊中转站": "Estação de Transferência Ridge",
        "山脊营地": "Acampamento Ridge",
        "暖阳农庄": "Fazenda Sunbury",
        "瀑布广场": "Praça Waterfall",
        "沉船坟场": "Cemitério de Navios",
        "沉没宅院": "Casa Submersa",
        "检测点024": "Ponto de Inspeção 024",
        "检测点9043": "Ponto de Inspeção 9043",
        "TAB-6A营地": "Acampamento TAB-6A",
        "高地居住区": "Zona Residencial Highland",
        "洗劫一空的营地": "Acampamento Saqueado",
        "远眺伐木场": "Serraria Overlook",
        "污染检测点77": "Ponto de Inspeção de Poluição 77",
        "河心码头": "Porto Riverhart",
        "河畔纪念品店": "Loja de Souvenirs Riverside",
        "枯竭油井": "Poço de Petróleo Depletado",
        "蜿蜒山种植园": "Plantação Winding Ridge",
        "浅滩公园": "Parque Shoal",
        "波光镇集市": "Mercado Rippleby",
        "风车阵列": "Fazenda Eólica",
        "秘港": "Porto Secreto",
        "检测点023": "Ponto de Inspeção 023",
        "克里夫顿": "Clifton",
        "海风疗养地": "Resort Breezy Shores",
        "诺顿农场": "Fazenda Norton",
        "高岸检测点": "Ponto de Inspeção Highbank",
        "私酿庄园": "Mansão da Cervejaria",
        "老大的乐园": "Parque de Diversões do Chefe",
        "霍特电站": "Estação de Energia Holt",
        "帕斯利广场": "Praça Paisley",
        "山麓别墅": "Casa na Encosta",
        "盖亚通讯阵列": "Array de Comunicação Gaia",
        "检测点266": "Ponto de Inspeção 266",
        "狂热信徒聚落": "Colônia dos Crentes",
        "戴维斯角": "Ponto Davis",
        "鞍前营地": "Acampamento Saddlefront",
        "渔人码头": "Cais dos Pescadores",
        "格尔峰电站": "Estação de Energia Mount Guel",
        "检测点091": "Ponto de Inspeção 091",
        "妮娜奶奶的水果餐吧": "Diner da Vovó Nina",
        "检测点384": "Ponto de Inspeção 384",
        "矿镇": "Cidade Mineira",
        "翠湖游客中心": "Centro de Visitantes Greenlake",
        "搁浅滩涂": "Pântano de Encalhe",
        "海边旧屋": "Cabana à Beira-Mar",
        "洞口营地": "Acampamento na Boca da Caverna",
        "破败码头": "Cais Derelito",
        "幽谷民居": "Residência do Vale",
        "废弃水塔": "Torre d'Água Abandonada",
        "瞭望处": "Mirante",
        "松林猎场": "Campo de Caça dos Pinheiros",
        "纵队前哨": "Posto de Avançada Guerrilheiro",
        "废弃避难所": "Abrigo Abandonado",
        "干涸码头": "Cais Seco",
        "林场": "Floresta",
        "潮间地农场": "Fazenda da Zona Intermarinha",
        "食品厂货栈": "Armazém da Fábrica de Doces",
        "悬索营地": "Acampamento de Cabo",
        "栈道木屋": "Cabana do Passadiço",
        "废弃探险营地": "Acampamento de Expedição Abandonado",
        "悬索货栈": "Armazém de Cabo",
        "荒废农庄": "Fazenda Abandonada",
        "鲸骨遗迹": "Ruínas dos Ossos de Baleia",
        "瞭望点": "Ponto de Observação",
        "路边野餐": "Piquenique à Beira da Estrada",
        "古船农场": "Fazenda do Navio Antigo",
        "临时调查营地": "Acampamento de Investigação Temporário",
        "倒挂遗迹": "Ruínas Invertidas",
        "幽灵渔村": "Vila Fantasma",
        "悬船冰洞": "Gruta do Navio Pendurado",
        "断桥": "Ponte Colapsada",
        "暖火营地": "Acampamento Fogo Quente",
        "雪松小屋": "Cabana de Cedro",
        "收容井-西格玛": "Silo de Contenção - Sigma",
        "收容井-斐": "Silo de Contenção - Phi",
        "收容井-暗狱": "Silo de Contenção EX1",
        "收容井-阿尔法": "Silo de Contenção - Alpha",
        "收容井-寒境": "Silo de Contenção - Psi",
        "收容井-西塔": "Silo de Contenção - Theta",
        "收容井·塔乌": "Silo de Contenção - 08",
        "空间锚点·断桥": "Âncora de Fenda - Ponte Colapsada",
        "空间锚点·“心愿奇境”": "Âncora de Fenda - Wishland - Oeste",
        "空间锚点·慕斯市食品厂": "Âncora de Fenda - Fábrica de Doces de Mousseville",
        "空间锚点·慕斯市": "Âncora de Fenda - Mousseville",
        "空间锚点·搁浅滩涂": "Âncora de Fenda - Pântano de Encalhe",
        "空间锚点·烟袋度假区": "Âncora de Fenda - Resort de Tabaco",
        "空间锚点·悬船冰洞": "Âncora de Fenda - Gruta do Navio Pendurado",
        "空间锚点·菲斯库尔港": "Âncora de Fenda - Porto Fiskur",
        "空间锚点·“母巢”收容保护区": "Âncora de Fenda - Área Restrita Hiverail",
        "空间锚点·黑石要塞": "Âncora de Fenda - Acampamento Obsidiana",
        "空间锚点·“大河”收容场": "Âncora de Fenda - Centro de Contenção Taiga",
        "空间锚点·冻火湾": "Âncora de Fenda - Forja Congelada",
        "空间锚点·“黑域”之门": "Âncora de Fenda - Entrada da Zona da Névoa",
        "空间锚点·致命信号": "Âncora de Fenda - Sinal Fatal",
        "空间锚点·蛇腹洞穴": "Âncora de Fenda - Caverna SunShroud",
        "空间锚点·蛇尾滑索营地": "Âncora de Fenda - Acampamento Cauda de Serpente",
        "空间锚点·燃尽之地": "Âncora de Fenda - Terra Queimada",
        "空间锚点·废弃提炼厂": "Âncora de Fenda - Refinaria Abandonada",
        "空间锚点·火喉下城": "Âncora de Fenda - Fortaleza da Garganta de Fogo",
        "空间锚点·灰落市1": "Âncora de Fenda - AshenTon 1",
        "空间锚点·灰落市2": "Âncora de Fenda - AshenTon 2",
        "空间锚点·炎神研究所": "Âncora de Fenda - Centro de Pesquisa do Deus do Fogo",
        "空间锚点·温泉民宿": "Âncora de Fenda - Pousada de Águas Termais",
        "空间锚点·塔乌": "Âncora de Fenda - Silo de Recolhimento 08",
        "武器箱【剧情箱子】": "Caixa de Arma【História】",
        "暴食狂": "Glutão",
        "屠夫": "Árbitro",
        "裁决者": "Árbitro",
        "星尘簇": "Andarilho das Estrelas",
        "门徒": "Discípulo",
        "雨壳": "Ceifador da Chuva",
        "腐坏眼虫": "Máquina de Garras",
        "娃娃机": "Máquina de Garras",
        "抓娃娃机": "Máquina de Garras",
        "唤生之母": "Mãe da Vida",
        "唤生水母": "Mãe da Vida",
        "熔烛": "Candle Molten",
        "乐园向导": "Menino do Balão",
        "夜魇": "Cervitaur",
        "天气预报": "Previsão do Tempo",
        "罪人守望": "Sentinela dos Pecadores",
        "罗塞塔防暴员": "Rosetta Bruiser",
        "罗塞塔机械师": "Rosetta Mecânico",
        "罗塞塔重装员": "Rosetta Pesado",
        "这里没有迪斯科": "Para Onde Vai o Disco?",
        "湖之暗面": "O Lado Escuro",
        "挖通地狱": "Cavar até o Inferno",
        "腐乐园": "Paraíso Perdido",
        "喀戎行动": "Operação Quíron",
        "轻量化红点瞄具": "Mira Reflexiva Leve",
        "战斗侦查瞄具": "Óptica de Combate de Reconhecimento",
        "反射式瞄具": "Mira Reflexiva",
        "精准步枪瞄具": "Mira de Rifle de Precisão",
        "战术全像瞄准镜": "Mira Tática Holográfica",
        "精准光学瞄具": "Óptica de Precisão",
        "战术步枪瞄具": "Mira Tática de Rifle",
        "轻型光学瞄具": "Óptica Leve",
        "中距离战术瞄具": "Mira Tática de Médio Alcance",
        "密封型反射式瞄具": "Mira Reflexiva Selada",
        "紧凑型反射式瞄具": "Mira Reflexiva Compacta",
        "棱镜式瞄具": "Mira Prismática",
        "远距离战术瞄具": "Mira Tática de Longo Alcance",
        "大型光学瞄具": "Mira Óptica Grande",
        "紧固型微型红点瞄具": "Mira Reflexiva Mini Fixada",
        "微型红点瞄具": "Mira Reflexiva Mini",
        "先进战斗光学瞄具": "Óptica de Combate Avançada",
        "全像瞄准镜": "Mira Holográfica",
        "鱼鹰抑制器": "Supressor Osprey",
        "集成型补偿器": "Compensador Integrado",
        "多用途霰弹枪抑制器": "Supressor de Espingarda Multiuso",
        "锤头型补偿器": "Compensador de Martelo",
        "短型抑制器": "Supressor Curto",
        "战术消焰器": "Redutor de Flashes Tático",
        "小型补偿器": "Compensador Pequeno",
        "加长型制退器": "Freio Estendido",
        "一体式抑制器": "Supressor Integrado",
        "小型制退器": "Freio de Boca Pequeno",
        "一体式消焰器": "Redutor de Flashes Integrado",
        "伪装用抑制器": "Supressor de Camuflagem",
        "大型抑制器": "Supressor Grande",
        "大型枪口制退器": "Freio de Boca Grande",
        "前向消焰器": "Redutor de Flash Frontal",
        "消焰器": "Redutor de Flash",
        "轻量化制退器": "Freio Leve",
        "基础抑制器": "Supressor Básico",
        "紧凑型制退器": "Freio Compacto",
        "霰弹枪制退器": "Freio de Espingarda",
        "小型红外指示器": "Mini Mira Reflexiva, Infravermelho Pequeno",
        "前护手握把": "Empunhadura de Proteção Frontal",
        "后护手握把": "Empunhadura de Proteção Traseira",
        "大型激光指示器": "Indicador Laser Grande",
        "集成型激光指示器": "Indicador Laser Integrado",
        "角型握把": "Empunhadura Triangular",
        "战术激光指示器": "Indicador Laser Tático",
        "小型激光指示器": "Indicador Laser Pequeno",
        "轻质前握把": "Empunhadura Frontal Leve",
        "轻质水平握把": "Empunhadura Horizontal Leve",
        "战术手电筒": "Lanterna Tática",
        "红外指示器": "Indicador Infra-vermelho",
        "紧凑型红外指示器": "Indicador Infra-vermelho Compacto",
        "战术组合握把": "Empunhadura Tática Combinada",
        "眼镜蛇握把": "Empunhadura Cobra",
        "垂直握把": "Empunhadura Vertical",
        "紧凑型手电筒": "Lanterna Compacta",
        "激光指示器": "Indicador Laser",
        "折叠脚架": "Bipé Dobrável",
        "狙击枪战术弹匣": "Carregador Tático de SR",
        "轻机枪校准弹鼓": "Carregador de Tambor Calibrado de LMG",
        "狙击枪改良弹匣": "Carregador Ampliado de SR",
        "步枪轻量化弹匣": "Carregador Leve de Rifle",
        "冲锋枪加重型弹匣": "Carregador Pesado de SMG",
        "轻机枪大型弹鼓": "Carregador de Tambor Grande de LMG",
        "手枪战术型弹匣": "Carregador Tático de Pistola",
        "冲锋枪战术型弹匣": "Carregador Tático de SMG",
        "步枪扩容弹匣": "Carregador Estendido de Rifle",
        "手枪加长型弹匣": "Carregador Estendido de Pistola",
        "手枪改良弹匣": "Carregador Ampliado de Pistola",
        "冲锋枪改良弹匣": "Carregador Ampliado de SMG",
        "步枪改良弹匣": "Carregador Ampliado de Rifle",
        "异常门扉": "Quebra-Cabeça de Porta",
        "异常路牌": "Painel Publicitário Quebrado",
        "广告牌异常": "Painel Publicitário Quebrado",
        "破碎山石异常": "Pedra Quebrável",
        "异常电话亭": "Cabine Telefônica",
        "异常雕像": "Quebra-Cabeça de Estátua",
        "黑水相机": "Emote de Câmera",
        "诡谲画作: 小型制退器": "Freio de Boca Pequeno (necessita Pintura Misteriosa)",
        "诡谲画作: 轻型光学瞄具": "Óptica Leve (necessita Pintura Misteriosa)",
        "诡谲画作: 小型激光指示器": "Indicador Laser Pequeno (necessita Pintura Misteriosa)",
        "诡谲画作: 战术步枪瞄具": "Mira Tática de Rifle (necessita Pintura Misteriosa)",
        "诡谲画作: 前向消焰器": "Redutor de Flash Frontal (necessita Pintura Misteriosa)",
        "战斗侦察瞄具": "Óptica de Combate de Reconhecimento",
        "反射式瞄具·黑色": "Mira Reflexiva",
        "角形握把": "Empunhadura Triangular",
        "霰弹枪式制动器": "Freio de Espingarda",
        "密封型反射瞄具": "Mira Reflexiva Selada",
        "多用途霰弹枪抑制器(6226,-588)": "Supressor de Espingarda Multiuso (6226,-588)",
        "大型光学瞄具,黑心地带(3039,990)": "Mira Óptica Grande (3039,990)",
        "大型光学瞄具,黑心地带(3037,-979)": "Mira Óptica Grande (3037,-979)",
        "手枪加强型弹匣": "Carregador Estendido de Pistola",
        "诡谲画作：小型制退器": "Freio de Boca Pequeno (necessita Pintura Misteriosa)",
        "诡谲画作：轻型光学瞄具": "Óptica Leve (necessita Pintura Misteriosa)",
        "诡谲画作：小型激光指示器": "Indicador Laser Pequeno (necessita Pintura Misteriosa)",
        "诡谲画作：战术步枪瞄具": "Mira Tática de Rifle (necessita Pintura Misteriosa)",
        "诡谲画作：前向消焰器": "Redutor de Flash Frontal (necessita Pintura Misteriosa)",
        "诡谲画作:战术步枪瞄具": "Mira Tática de Rifle (necessita Pintura Misteriosa)",
        "手枪": "Pistolas",
        "霰弹枪": "Espingardas",
        "冲锋枪": "SMGs",
        "步枪": "Rifles",
        "狙击枪": "Fuzis de Precisão",
        "轻机枪": "LMGs",
        "弓弩": "Arcos e Flechas",
        "重型火器": "Armas Pesadas",
        "刀剑": "Armas Brancas",
        "头盔": "Capacetes",
        "面部": "Máscaras",
        "上身": "Coletes",
        "下身": "Calças",
        "手套": "Luvas",
        "鞋子": "Sapatos",
        "瞄具配件": "Ópticas",
        "枪口配件": "Acessórios de Cano",
        "战术配件": "Acessórios Táticos",
        "弹匣配件": "Acessórios de Carregador",
        "碎弹模组": "Módulos de Estilhaços",
        "霜寒模组": "Módulos de Vórtice de Gelo",
        "爆弹模组": "Módulos de Bomba Instável",
        "电涌模组": "Módulos de Sobrecarga de Energia",
        "标记模组": "Módulos de Olho de Touro",
        "弹射模组": "Módulos de Rebate",
        "快枪手模组": "Módulos de Atirador Rápido",
        "灼烧模组": "Módulos de Queimadura",
        "阵地模组": "Módulos de Defesa de Fortaleza",
        "武器通用": "Compatível com Armas",
        "头盔模组": "Módulos de Capacete",
        "面部模组": "Módulos de Máscara",
        "上身模组": "Módulos de Colete",
        "下身模组": "Módulos de Calças",
        "手套模组": "Módulos de Luvas",
        "鞋子模组": "Módulos de Sapato",
        "防具通用": "Compatível com Armaduras",
        "近战通用": "Geral de Armas Brancas",
        "流派效果": "Efeito de Gênero",
        "模组后缀": "Sufixos de Módulo",
        "元素伤害": "Dano Elementar",
        "特殊子弹": "Balas Especiais",
        "套装碎片": "Fragmentos de Conjunto",
        "素材": "Materiais",
        "近战蓝图": "Plantilhas de Armas Brancas",
        "手枪蓝图": "Plantilhas de Pistolas",
        "霰弹枪蓝图": "Plantilhas de Espingardas",
        "冲锋枪蓝图": "Plantilhas de SMGs",
        "步枪蓝图": "Plantilhas de Rifles",
        "狙击枪蓝图": "Plantilhas de Fuzis de Precisão",
        "轻机枪蓝图": "Plantilhas de LMGs",
        "弓弩蓝图": "Plantilhas de Arcos e Flechas",
        "家具配方": "Plantilhas de Móveis",
        "肉类": "Carne",
        "鱼类": "Peixes",
        "药草": "Ervas",
        "食谱：熏肉罗宋汤": "Receita: Borscht Deluxe",
        "食谱：畸变塔可卷": "Receita: Taco",
        "食谱：星尘茶": "Receita: Chá de Poeira Estelar",
        "食谱：培根肉排汉堡": "Receita: Hambúrguer de Bacon",
        "食谱：南瓜星空派": "Receita: Stargazy Pie",
        "食谱：消脂果汁": "Receita: Suco Termogênico",
        "食谱：安全三明治": "Receita: Sanduíche Seguro",
        "食谱：星尘水果罐头": "Receita: Comida enlatada sortida",
        "食谱：星尘通心粉罐头": "Receita: Sopa Italiana enlatada Stardust",
        "食谱：奇迹茶": "Receita: Chá Milagroso",
        "食谱：碎裂面包": "Receita: Pão Quebrado",
        "食谱：星尘南瓜泥沙拉": "Receita: Salada de Abóbora Stardust",
        "食谱：幽光蘑菇罐头": "Receita: Cogumelo em conserva espectral",
        "食谱：星尘炸肉": "Receita: Cachorro-quente frito misto",
        "食谱：元宝饺子": "Receita: Bolinhos Yuanbao",
        "食谱：深海鱼片披萨": "Receita: Pizza Stargazy",
        "食谱：炸薯条": "Receita: Batatas Fritas",
        "食谱：反重力奶昔": "Receita: Milkshake Antigravidade",
        "食谱：金钱饼": "Receita: Croquete",
        "食谱：特调冰酿": "Receita: Ice Brew Especial",
        "食谱:奇思妙想饮": "Receita: Bebida Caprichosa",
        "食谱：炸鱼薯条": "Receita: Peixe com Batatas Fritas",
        "食谱：幽灵饼干": "Receita: Biscoitos Fantasma",
        "食谱：畸变带骨香肠": "Receita: Linguiça Deviada com Osso",
        "食谱：捕获之汤": "Receita: Sopa de Captura",
        "食谱：蜜酿炖肉": "Receita: Carne Glaceada com Mel",
        "远归之蝶": "Emissário da Borboleta",
        "活体凝胶": "Gel Fétido",
        "荣枯种子": "Semente da Colheita",
        "捕梦网": "Apanhador de Sonhos",
        "低语亡骨": "Cráneo Canino",
        "电鳗": "Anguila Elétrica",
        "迪斯科球": "Bola de Disco",
        "发条青蛙": "Frog the Leaper",
        "极寒水母": "Medusa Polar",
        "青龙": "Chefosaurus",
        "蜂团团": "Abelha Zumbidora",
        "工号37": "H37",
        "姜饼屋": "Casa de Gengibre",
        "核子打火机": "Isqueiro Atômico",
        "凝视的黑猫": "Vazio Encantado",
        "木工河狸": "Castor de Carpinteiro",
        "空间魔方": "Cubo Espacial",
        "元素小子": "Menino Digby",
        "雪景球": "Globo de Neve",
        "上界之卵": "Ovo do Mundo Superior",
        "庞然大菇": "Cogumelo Gigante",
        "皆斩": "Purificador Zeno",
        "门扉": "Porta Estranha",
        "巫毒娃娃": "Boneca Vodu",
        "炎之精": "Essência de Chama",
        "破碎少女": "Donzela Quebrada",
        "迷你奇点": "Mini Maravilha",
        "异维大猫": "Gato Extradimensional",
        "球状闪电": "Relâmpago Esférico",
        "迷你黄衣": "Mini Devorador",
        "小纸人": "Boneca de Papel",
        "愿望先生": "Sr. Desejo",
        "红龙": "Dino Pirotécnico",
        "熊医生": "Dr. Teddy",
        "恶臭球根": "Bulbo Fedorento",
        "空之子": "Pelo Vento",
        "胡桃夹子": "Quebra-nozes",
        "蝶之梦": "Rebecca",
        "气球狗": "Cão de Balão",
        "一碗美味": "Abraço em Uma Tigela",
        "诡谲画作·代 Dayton湿地": "Pintura Misteriosa · Pântano Dayton",
        "诡谲画作·破碎三角洲": "Pintura Misteriosa · Delta Quebrado",
        "诡谲画作·铁锈河": "Pintura Misteriosa · Rio Ferrugem",
        "诡谲画作·垩峰山": "Pintura Misteriosa · Pico Calcário",
        "诡谲画作·孤狼荒原": "Pintura Misteriosa · Areias Vermelhas",
        "诡谲画作·黑心地带": "Pintura Misteriosa · Coração Negro",
        "硫磺": "Enxofre",
        "铜矿": "Minério de Cobre",
        "锡矿": "Minério de Estanho",
        "锡矿富集区": "Área de Minério de Estanho",
        "铁矿": "Minério de Ferro",
        "铝矿": "Minério de Alumínio",
        "钨矿": "Minério de Tungstênio",
        "银矿": "Minério de Prata",
        "银矿区域": "Área de Minério de Prata",
        "银矿(稀有)": "Minério de Prata (Aleatório)",
        "银矿 (稀有)": "Minério de Prata (Aleatório)",
        "金矿": "Minério de Ouro",
        "金矿区域": "Área de Minério de Ouro",
        "金矿(稀有)": "Minério de Ouro (Aleatório)",
        "金矿 (稀有)": "Minério de Ouro (Aleatório)",
        "金矿（先锋服)": "Mina de Ouro",
        "星尘矿": "Minério de Stardust",
        "星尘矿石": "Minério de Stardust",
        "星尘矿区": "Área de Minério de Stardust",
        "星尘矿区域": "Área de Minério de Stardust",
        "星尘矿(稀有)": "Minério de Stardust (Aleatório)",
        "星尘矿 (稀有)": "Minério de Stardust (Aleatório)",
        "橘子": "Laranjas",
        "果蔬篮橘子": "Laranjas",
        "小麦": "Trigo",
        "果蔬篮小麦": "Trigo",
        "红色浆果": "Baga de Hawthorn",
        "卷心菜": "Repolho",
        "果蔬篮卷心菜": "Repolho",
        "甜菜": "Beterraba",
        "果蔬篮甜菜": "Beterraba",
        "蓝莓": "Mirtilo",
        "南瓜": "Abóbora",
        "果蔬篮南瓜": "Abóbora",
        "玉米": "Milho",
        "果蔬篮玉米": "Milho",
        "土豆": "Batata",
        "果蔬篮土豆": "Batata",
        "蘑菇": "Cogumelo",
        "果蔬篮蘑菇": "Cogumelo",
        "火刺果": "Spikemato",
        "阳姜": "Gengibre Solar",
        "薄荷": "Hortelã",
        "雪茸": "Fungo de Neve",
        "芦荟": "Aloe Vera",
        "鼠尾草 * 5": "Sálvia * 5",
        "鼠尾草 * 8": "Sálvia * 8",
        "桔梗": "Campânula",
        "金银花": "Madressilva",
        "金银花 * 3": "Madressilva * 3",
        "金银花 * 4": "Madressilva * 4",
        "藏红花": "Açafrão",
        "血菖蒲": "Cálamo Escarlate",
        "紫锥菊": "Echinacea",
        "黄莲花": "Lótus Amarelo",
        "苹果": "Maçã",
        "苹果树": "Árvore de Maçã",
        "苹果树 * 2": "Árvore de Maçã * 2",
        "葡萄": "Uvas",
        "贝壳岩石": "Pedra de Concha",
        "海草岩石": "Pedra de Alga Marinha",
        "观赏性花海": "Mar de Flores",
        "香蕉树": "Árvore de Banana",
        "香蕉树 * 2": "Árvore de Banana * 2",
        "香蕉树 * 4": "Árvore de Banana * 4",
        "香蕉树 * 6": "Árvore de Banana * 6",
        "香蕉树 * 7": "Árvore de Banana * 7",
        "椰子树": "Árvore de Coco",
        "椰子树 * 3": "Árvore de Coco * 3",
        "巨木": "Árvore Gigante",
        "龙血树(巨木)": "Árvore Gigante",
        "野生动物": "Animais",
        "兔子窝": "Buraco de Coelho",
        "鹿": "Cervo",
        "星蚀鹿群": "Rebanho de Cervo",
        "星蚀雄鹿": "Cervo Macho",
        "星蚀雌鹿": "Cervo Fêmea",
        "野猪": "Javali",
        "野猪群": "Rebanho de Javali",
        "星蚀鳄": "Jacaré",
        "羊群": "Rebanho de Ovelhas",
        "花豹": "Leopardo",
        "星蚀熊窝": "Caverna do Urso",
        "星蚀熊": "Urso",
        "肉排": "Bife",
        "鳄鱼蛋": "Ovos de Jacaré",
        "鸟蛋": "Ovos de Pássaro",
        "原油油井": "Poço de Petróleo",
        "别靠近箱子": "Mímico",
        "地堡门禁卡": "Cartão de Acesso ao Bunker",
        "吓人箱子": "Mímico",
        "空间异动": "Anomalia Espacial",
        "地下入口": "Entrada Subterrânea",
        "电话亭": "Cabine Telefônica",
        "拟态怪储物箱": "Mímico",
        "拟态宝箱怪": "Mímico",
        "密码: 5897": "Senha: 5897",
        "密码: 325": "Senha: 325",
        "地下通道入口": "Entrada Subterrânea",
        "地下通道最近入口": "Entrada Subterrânea",
        "地窖入口": "Entrada Subterrânea",
        "山洞入口": "Entrada da Caverna",
        "溶洞入口": "Entrada da Caverna",
        "镜女": "Inimigo Espelho",
        "拟态储物箱别开": "Mímico",
        "电梯：负一层": "Elevador: Nível Subterrâneo 1",
        "拟态宝箱怪别开": "Mímico",
        "空间异常": "Anomalia Espacial",
        "5层楼梯": "5 Escadas",
        "箱子怪别开": "Mímico",
        "下楼电梯": "Elevador",
        "下楼电梯位置": "Elevador",
        "隐藏宝箱最后位置": "Baú de Tesouro",
        "抽屉柜": "Gavetas",
        "混合矿场": "Mineração Mista",
        "隐藏的宝箱": "Tutorial do Baú Morfogenético",
        "玩具小熊": "O Chamado da Infância",
        "急救！急救！": "Hospital Dayton",
        "信徒的藏宝图": "Perdido na Loucura - Ponto de Partida",
        "信徒的财产箱": "Perdido na Loucura - Localização do Tesouro",
        "检测点见闻": "Esboço de um Ponto de Inspeção",
        "红与黑": "Carnaval da Perdição",
        "被丢弃的玩偶": "Brinquedos de Anna",
        "艺术家的钥匙": "Reunião de Cultistas - Ponto de Partida",
        "信徒的宝箱": "Reunião de Cultistas - Localização do Tesouro",
        "特别关系": "Um Relacionamento Especial",
        "生日快乐": "Feliz Aniversário",
        "招财猫开始点": "Gato da Sorte - Ponto de Partida",
        "招财猫1号": "Gato da Sorte #1",
        "招财猫2号": "Gato da Sorte #2",
        "招财猫3号": "Gato da Sorte #3",
        "招财猫给予的宝箱": "Gato da Sorte - Localização do Tesouro",
        "好消息坏消息": "Sobre Alegria e Tristeza - Ponto de Partida",
        "神婆的宝箱": "Sobre Alegria e Tristeza - Localização do Tesouro",
        "农庄惊魂": "Terror na Fazenda",
        "限定版牛奶": "Edição Limitada",
        "考古学家的馈赠": "Seja Verdadeiro Até a Morte",
        "遗留财产": "Um Legado Familiar",
        "悲伤画像": "Retrato Triste",
        "密码：9274": "Senha: 9274",
        "秘密配方": "Receita",
        "韦伯": "Weber",
        "赵金潭": "Zhao Jintan",
        "拟态体商店": "Severin VII-S2041 (Comerciante SIRA)",
        "鱼饵商人": "Margerie (Comerciante de Iscas)",
        "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie【Mapas de Iscas】",
        "异常点": "Objeto Abnormal",
        "稀有": "Raro",
        "持续刷新": "Atualização Contínua",
        "碧湖山庄": "Greenlake Hill",
        "检测点91": "Ponto de Inspeção 91",
        "戴维思角": "Ponto Davis",
        "检测点24": "Ponto de Inspeção 24",
        "翻车鱼岛旅客中心": "Centro de Visitantes da Ilha Mola",
        "治炼厂污染点": "Ponto de Poluição da Refinaria",
        "检测点3711": "Ponto de Inspeção 3711",
        "翠湖山镇": "Greenlake Hill",
        "无蘑菇": "Sem Cogumelos",
        "果蔬箱土豆": "Batata",
        "油田区域": "Área de Campo de Petróleo",
        "抽水泵采集": "Bomba",
        "洞穴内": "Dentro da Caverna",
        "便携式燃油": "Combustível Portátil",
        "腐化熊": "Urso Corrompido",
        "水豚": "Capivara",
        "狼": "Lobo",
        "鳄鱼": "Crocodilo",
        "长嘴海鸥": "Gaivota de Bico Longo",
        "海龟": "Tartaruga Marinha",
        "鹈鹕": "Pelicano",
        "兔子": "Coelho",
        "鳄龟": "Tartaruga Bico de Pato",
        "狐狸": "Raposa",
        "浣熊": "Guaxinim",
        "火烈鸟": "Flamingo",
        "腐化鳄": "Crocodilo Corrompido",
        "腐化狼": "Lobo Corrompido",
        "白斑狗鱼钓鱼点": "Northern Pike (Ponto de Pesca)",
        "白斑狗鱼": "Northern Pike",
        "海鲈鱼": "Sea Bass",
        "神仙鱼": "Peixe Anjo",
        "长吻雀鳝": "Longnose Gar",
        "黑鲈": "Black Bass",
        "孔雀鱼": "Guppy",
        "鲤鱼": "Carpa",
        "图丽鱼": "Astronotus Ocellatus",
        "太阳鱼": "Lepomis",
        "锦鲤": "Koi",
        "龙鱼": "Arowana",
        "鳙鱼": "Bighead Carp",
        "沙丁鱼": "Sardinha",
        "梭鱼": "Barracuda",
        "鲭鱼": "Mackerel",
        "罗非鱼": "Tilápia",
        "虹鳟": "Rainbow Trout",
        "鲑鱼": "Salmão",
        "鲳鲹": "Pompano",
        "松鼠": "Esquilo",
        "亚口鱼": "Sucker",
        "PvE-天空之触": "PvE-MANIBUS",
        "PvP-分歧之路": "PvP-Evolution's Call",
        "PvP-逆位战争": "PvP-Prismverse's Clash",
        "PvE-雪国人生": "PvE-Way of Winter",
        "玩家": "Jogador",
        "私有收容仓": "Unidade de Confinamento Privada",
        "出生点": "Ponto de Surgimento",
        "观景点：雪崩巨楔": "Ponto de Vista: Monólito da Avalanche",
        "观景点：菲斯库尔港": "Ponto de Vista: Porto Fiskur",
        "观景点：熊栖雪场": "Ponto de Vista: Covil do Urso",
        "观景点：母巢": "Ponto de Vista: Hiverail",
        "观景点：白崖黑域": "Ponto de Vista: Setor Negro do Penhasco Branco",
        "观景点：心愿奇境西园": "Ponto de Vista: Wish Land - Oeste",
        "观景点：荒原巨骨": "Ponto de Vista: Crânio da Terra Desolada",
        "观景点：冻火湾": "Ponto de Vista: Fornalha Congelada",
        "观景点：巨岩": "Ponto de Vista: Rocha Grande",
        "观景点：鲸骨乡": "Ponto de Vista: Ossos de Baleia",
        "观景点：“大河”收容场": "Ponto de Vista: Centro de Confinamento TAIGA",
        "观景点：搁浅船只": "Ponto de Vista: Navio Encalhado",
        "观景点：慕斯市食品厂": "Ponto de Vista: Fábrica de Doces Mousseville",
        "观景点：冻原巨楔": "Ponto de Vista: Monólito da Tundra",
        "观景点：慕斯市": "Ponto de Vista: Mousseville",
        "观景点：心愿奇境东园": "Ponto de Vista: Wish Land - Parque Leste",
        "观景点：黑石要塞": "Ponto de Vista: Fortaleza Obsidiana",
        "观景点：绚烂花海": "Ponto de Vista: Campos de Flores",
        "观景点：冰屋营地": "Ponto de Vista: Acampamento Igloo",
        "观景点：炎神实验室": "Ponto de Vista: Centro de Pesquisa do Deus do Fogo",
        "观景点：不落号坠落点": "Ponto de Vista: Ponto de Queda Não Caído",
        "观景点：收容井塔乌": "Ponto de Vista: Silo de Confinamento Taurus",
        "观景点：火喉下城": "Ponto de Vista: Fortaleza Garganta de Fogo",
        "观景点：炽尘巨楔": "Ponto de Vista: Monólito da Poeira Incandescente",
        "观景点：火喉圣域": "Ponto de Vista: Santuário da Garganta de Fogo",
        "观景点：月牙湖": "Ponto de Vista: Lago Crescente",
        "观景点：灰落": "Ponto de Vista: Ashenton",
        "观景点：影日洞穴": "Ponto de Vista: Caverna da Sombra do Sol",
        "观景点：遗忘之地": "Ponto de Vista: Oblivion",
        "空间锚点·废弃矿洞二层": "Rift Anchor - Abandoned Mine Floor 2",
        "收容井-德尔塔": "Securement Silo - Delta",
        "电梯": "elevator",
        "乖乖兔": "Fetch-A-Lot Bunny",
        "食谱：黄油松茸": "Recipe: Butter Matsutake Mushrooms",
        "食谱：硬邦邦姜糖": "Recipe: GingerDrop",
        "食谱：蜜蛋弹弹乐": "Recipe: Ginger Poppers",
        "食谱：雪茸蛋炒饭": "Recipe: Snow Mushroom Fried Rice",
        "食谱：水果派": "Recipe: Mixed Fruit Pie",
        "食谱：噼里啪啦南瓜汤": "Recipe: Sparkling Pumpkin Soup",
        "食谱：炙热炖肉火锅": "Recipe: Hearty Meat Stew",
        "食谱：鲜肉咖喱饭": "Recipe: Curry and Rice",
        "食谱：砰砰爆米花": "Recipe: Popcorn",
        "食谱：水果蛋糕": "Recipe: Fruit Cake",
        "食谱：炙热烈焰蛋挞": "Recipe: Flaming Eggtart",
        "食谱：麻辣兔丁罐头": "Recipe: Canned Spicy Rabbit Dices",
        "食谱：清凉薄荷肉罐头": "Recipe: Canned Minty Meat",
        "宝箱怪位置待定": "Localização do Monstro do Baú a Definir",
        "气球异常：轻量化红点瞄具": "Anomalia de Balão: Mira Red Dot Leve",
        "玩偶异常：戍卫前握把": "Anomalia de Boneco: Empunhadura Frontal do Guarda",
        "凝石异常：斜切握把": "Anomalia de Pedra Coagulada: Empunhadura Cortada",
        "凝石异常：远射补偿器": "Anomalia de Pedra Coagulada: Compensador de Longo Alcance",
        "凝石异常：小型补偿器": "Anomalia de Pedra Coagulada: Compensador Pequeno",
        "冰块宝箱：轻型光学瞄具": "Baú de Gelo: Mira Óptica Leve",
        "冰块宝箱：手枪加长型弹匣": "Baú de Gelo: Carregador Estendido de Pistola",
        "冰块宝箱：步枪扩容弹匣": "Baú de Gelo: Carregador de Rifle de Alta Capacidade",
        "凝石异常：轻型握把": "Anomalia de Pedra Coagulada: Empunhadura Leve",
        "冰块宝箱：冲锋枪加重型弹匣": "Baú de Gelo: Carregador Pesado de Submetralhadora",
        "凝石异常：隐秘抑制器": "Anomalia de Pedra Coagulada: Supressor Secreto",
        "冰块宝箱：轻机枪大型弹鼓": "Baú de Gelo: Cargador Grande de Metralhadora Leve",
        "凝石异常：一体式消焰器": "Anomalia de Pedra Coagulada: Supressor Integrado",
        "冰块宝箱：手枪战术型弹匣": "Baú de Gelo: Carregador Tático de Pistola",
        "凝石异常：冲锋枪战术型弹匣": "Anomalia de Pedra Coagulada: Carregador Tático de Submetralhadora",
        "凝石异常：奇袭制退器": "Anomalia de Pedra Coagulada: Dispositivo de Repulsão de Emboscada",
        "凝石异常：步枪轻量化弹匣": "Anomalia de Pedra Coagulada: Carregador Leve de Rifle",
        "凝石异常：密封型反射式瞄具": "Anomalia de Pedra Coagulada: Mira Reflexiva Selada",
        "气球异常：消焰器": "Anomalia de Balão: Supressor",
        "气球异常：小型制退器": "Anomalia de Balão: Pequeno Repulsor",
        "冰块宝箱：狙击枪战术弹匣": "Baú de Gelo: Carregador Tático de Rifle de Precisão",
        "脚印异常：精准步枪瞄具": "Anomalia de Pegada: Mira de Rifle de Precisão",
        "气球异常：狙击枪改良弹匣": "Anomalia de Balão: Carregador Aprimorado de Rifle de Precisão",
        "气球异常：小型红外指示器": "Anomalia de Balão: Pequeno Indicador Infravermelho",
        "气球异常：垂直握把": "Anomalia de Balão: Empunhadura Vertical",
        "松鼠异常：棕熊反射式瞄具": "Anomalia de Esquilo: Mira Reflexiva de Urso Pardo",
        "观景台": "Ponto de Vista Panorâmico",
        "气球异常": "Anomalia de Balão",
        "玩偶异常": "Anomalia de Boneco",
        "冰块宝箱": "Baú de Gelo",
        "冷晶矿": "Minério de Cristal Frio",
        "冰晶矿": "Minério de Cristal Frio",
        "热岩矿": "Minério de Rocha Quente",
        "寒冰瓜": "Melão de Gelo",
        "乌鸦蛋": "Ovo de Corvo",
        "极地椒": "Pimenta Polar",
        "极地椒 * 3": "Pimenta Polar * 3",
        "驯鹿": "Renas",
        "野牛": "Búfalo",
        "海豹": "Foca",
        "母羊": "Ovelha Fêmea",
        "公羊": "Carneiro",
        "北极狐": "Raposa Ártica",
        "北极熊": "Urso Polar",
        "熊": "Urso"
    }
}
