export default {
  buttons: {
    filter: "Filtro",
    select_all: "Selecionar tudo",
    deselect_all: "Desmarcar tudo",
    close: "",
    move_left: "",
    move_right: "",
    edit: "Editar",
    quit: "Desistir",
    apply: "Sim", //确认
    cancel: "Não", //取消
    heatmap: "Mapa de calor de recursos",
  },
  edit: {
    mode_switch: "Entrar/sair do modo de edição?", //是否进入/退出编辑模式
  },
  tabs: {
    by_category: "Categoria",
    by_item: "Item",
    by_search: "Procurar",
    resource_list: "Recursos",
    setting: "Configurações",
    user_data: "Dados do usuário",
    quick_setting: "Configurações rápidas",
    quick_setting_fuel_loot: "Rota de combustível",
    quick_setting_resource: "Recurso",
    quick_setting_bus_route: "Ônibus Monstro",
    quick_setting_show_players: "Mostrar jogadores",
    quick_setting_pollution: "Poluição",
    quick_setting_popup_coordinate: "Ponteiro de acompanhamento de coordenadas",
    quick_setting_disaster_area: "Área de desastre do Tecelão do Caos",
    area: "Áreas",
    treasure: "Tesouros",
    monster: "Explorar",
    collection: "Coleção",
    hint: "Dica",
    logged: "Dados",
    guest: "Conecte-se",
    oneclick_delete_enable: "Um clique",
    oneclick_delete_disable: "Desativar",
    oneclick_delete_badge: "No modo OneClick",
    oneclick_delete_hint1:
      "Depois de ativá-lo, clicar em um marcador não exibirá mais uma janela pop-up, mas excluirá ou recuperará diretamente o marcador.",
    oneclick_delete_enable_hint: "O modo de exclusão OneClick está ativado",
    oneclick_delete_disable_hint: "O modo de exclusão OneClick está desativado",
    oneclick_delete_dialog_title: "Aviso",
    oneclick_delete_dialog_content:
      "Depois de ativar o modo de exclusão com um clique, nenhuma janela pop-up aparecerá quando você clicar em um marcador no mapa. Em vez disso, o marcador será excluído ou recuperado diretamente. Deseja continuar ligando-o?",
    oneclick_delete_dialog_close: "Fechar",
    oneclick_delete_dialog_confirm: "Confirmar",
    batch_editing_enable: "Progresso",
    batch_editing_disable: "Saída",
    batch_editing_hint:
      "Você pode excluir ou recuperar em lote todos os marcadores de uma categoria. Você precisa fazer login para usá-lo.",
    setting_btn_hint: "Configurações relacionadas ao mapa",
    login_btn_hint: "Gerenciar meus dados",
    back_to_categories: "Voltar às categorias",
    display_area: "Filtro de área",
    select_item_category: "Selecione",
    related_items: "Itens Relacionados",
    locate_item: "Clique no item para localizar",
    search_resources: "Recursos de pesquisa",
    input_resource_name: "Nome de entrada",
    locate: "Localizar",
    // Miscellaneous UI strings
    any_name: "Qualquer palavra",
    keyword: "Palavra-chave",
    locations: "Locais",
    locate_point: "Clique para centralizar o local",
    input_item: "Insira um nome de local",
    related_item: "Unid",
    related_makers: "Marcadores",
    locate_marker: "Clique para centralizar o marcador",
    input_marker: "Insira um nome de marcador",
    related_resources: "Recursos",
    locate_resource: "Clique para centralizar o recurso",
    input_resource_for_searching: "Insira um nome de recurso",
    follow_xingchuan: "Siga Xingchuan",
    bilibili: "BiliBili",
    tiktok: "TikTok",
    ad: "ANÚNCIO",
    ad2: "ANÚNCIO",
    jd: "O anúncio não está disponível na versão em inglês",
    daigan: "O anúncio não está disponível na versão em inglês",
    login_warring: "Obtenha primeiro o texto do bot do Discord Server.",
    delete_all: "Excluir tudo",
    resume_all: "Restaurar",
    exit_management_mode: "Saída",
    select_scenario: "Cenário",
    show_unreviewed_markers: "Marcadores não revisados",
    show_unreviewed_areas: "Áreas não revisadas",
    地点区域: "Locais",
    宝箱秘藏: "Segredos",
    事件怪物: "Monstros",
    收集要素: "Coleções",
    异象轮盘: "Roda Visionária",
    地图提示: "Pontas",
    无尽长梦: "Sonho sem fim",
    "七日世界：禁区": "OnceHuman: RaidZone",
    非正常收容: "Desvio: Sobreviver",
    乐园岛: "Ilha Paraíso"
  },
  floor_text: {
    roof: "( Teto )",
    at_floor: "( Andar {floor} )",
    underground: "( Piso {floor} Subterrâneo )",
    level: "(Nível {level})",
  },
  settings: {
    has_video: "Marcador de vídeo",
    deleted_marker: "Marcador excluído",
    map_area_style: "Estilo de área do mapa",
    monster_bus_route: "Rota do ônibus monstro",
    marker_text: "Texto do marcador",
    resource_area: "Área de Recursos",
    last_updated_datetime: "Hora de atualização do marcador",
    icon_drawing_method:
      "Método de desenho de ícone (tela é recomendada quando o ícone está quebrado)",
    dark_mode: "Modo escuro",
    language: "Linguagem",
    auto_query: "Consultar quando as categorias mudam",
    auto_draw_marker_after_search: "Exibir o resultado da pesquisa no mapa",
    show: "Mostrar",
    hide: "Esconder",
    line_style: "Estilo de linha",
    area_style: "Estilo de preenchimento",
    wasm: "Wasm (melhor desempenho)",
    canvas: "Tela (melhor compatibilidade)",
    on: "Sobre",
    off: "Desligado",
    draw_text_mode: "Estilo de texto do marcador",
    draw_text_mode_1: "Completo",
    draw_text_mode_2: "Simplificado",
    deleted_marker_style: "Estilo de marcador excluído",
    deleted_marker_style_1: "Cruzar",
    deleted_marker_style_2: "Translúcido",
    deleted_marker_style_3: "Esconder",
  },
  user_data: {
    local_storage: "Dados locais",
    count: "sem registros | Registro {count} | {count} registros",
    local_storage_tutorial: "Tutorial",
    backup: "Backup e restauração",
    local_storage_text:
      "Você pode excluir qualquer marcador sem fazer login. Mas os dados serão armazenados apenas no navegador atual. Você pode fazer backup dos dados e transferi-los para outro navegador da web.",
    backup_placeholder: "Datas",
    backup_button: "Backup",
    restore_button: "Restaurar",
    cloud_storage: "Dados na nuvem",
    clear_all_data: "Excluir todos os dados",
    restore_hint:
      "Dica: Esta operação mesclará os dados locais com os dados importados. Se você estiver logado, os dados também serão sincronizados com a nuvem. Você quer continuar?",
    delete_hint:
      "Tem certeza de que deseja excluir todos os dados? Se você já estiver logado, os dados da nuvem também serão apagados. Você quer continuar?",
    wechat_login: "Conversamos",
    wechat_mp_login: "Wechat2",
    discord_login: "Discórdia",
    login_tutorial: "Tutorial",
    login_tutorial_text:
      "Após o login, os dados locais e da nuvem serão sincronizados automaticamente e você poderá continuar a usá-los em qualquer navegador e dispositivo. Você também pode usá-lo normalmente sem fazer login, mas os dados só podem ser armazenados no navegador local.",
    not_login: "Não logado",
    login_success: "Você fez login com sucesso",
    data_is_syncing: "Os dados estão sincronizando",
    last_syncing_time: "Hora da última sincronização:",
    logout: "Sair",
  },
  marker_dialog: {
    no_marker_img: "Sem imagens",
    delete_markder: "Excluir marcador",
    undelete: "Desfazer exclusão",
    delete_only: "Excluir apenas",
    hide_category: "Ocultar {category}",
    no_update_time: "Sem tempo de atualização",
    rewards: "Recompensas",
    close: "Fechar",
    detail: "Detalhe",
    operation: "Operação",
    timer_title: "Temporizador de reinicialização da caixa",
    timer_title_not_login: "(É necessário login) Temporizador de redefinição da caixa",
    deviant_timer_title: "Temporizador de reinicialização Mutações",
    to_login: "Faça login para desbloquear o recurso de temporizador",
    comment: "Comentários",
    auto_set_timer: "Temporizador de configuração automática",
    auto_set_timer_not_login: "(É necessário login) Configuração automática do temporizador",
    timer_tutorial: "Tutorial do cronômetro",
    sharing: "Compartilhamento",
    session_script: "Atualmente disponível em:",
    hint: "[ Dica ]",
    sharing_hint:
      "O link compartilhado exibirá automaticamente o marcador quando aberto.",
    download_qr_code: "Download",
    sharing_link: "Link",
    copy: "Cópia",
    update: "Atualizado",
    guide: "Guia",
    donate: "Doar",
    auto_reset_help_title: "Ajuda",
    auto_reset_help_text:
      "O tempo fixo de atualização para caixas de armas e caixas de equipamentos começa às 00:00:00 e é atualizado a cada 4 horas por hora. Se você ainda não conseguir abrir as caixas quando chegar o tempo de atualização, basta fazer login novamente.",
    auto_reset_help_ok: "OK",
    click_to_copy: "Clique para copiar",
    copied_successfully: "Copiado com sucesso",
    common_hint: "Dicas Gerais",
    batch_import: "Importação em lote",
    navigation_settings: "Configurações de navegação",
    contributors: "Colaboradores",
  },
  donate: {
    payment: "Por favor, digitalize o código QR usando o WeChat",
    text: "Seu suporte pode ajudar o site a continuar operando e atualizar mais recursos",
    warning: "Menores estão proibidos de doar",
  },
  scenario: {
    not_available: "Não disponível",
    current: "Atual",
    available: "Disponível",
    coming: "Chegando",
    scenarios: "Mapas",
  },
  languages: {
    dialog_title: "Selecione o idioma",
    dialog_close: "Fechar",
    contributors: "Colaboradores",
    help_1: "Não encontrou o idioma que procurava?",
    help_2: "Clique aqui para ajudar a melhorar as traduções.",
    default: "Padrão",
  },
  path_planning: {
    path_planning: "Planejamento de caminho",
    start: "Ponto inicial",
    end: "Ponto final",
    select_start: "Selecione o ponto inicial",
    select_end: "Selecione o ponto final",
    tips: "Dica: clique com o botão direito no mapa para definir rapidamente os pontos",
    clear: "Limpar caminho",
    submit: "Caminho de consulta",
    cancel: "Claro",
    placeholder: "Selecione no mapa",
  },
  heatmap: {
    no_data: "Sem dados",
    hint: "Quanto mais escura a cor do mapa de calor, mais recursos",
    clear: "Limpar mapa de calor",
  },
  categories: {
    // Areas
    传送塔: "Teletransportador",
    巨楔: "Monólito",
    主城: "Acampamento",
    研究所: "Laboratório",
    大型资源点: "Cidade",
    小型资源点: "Aldeia",
    收容井: "Silo de Segurança",
    位面锚: "Âncora de Fenda",
    空间锚点: "Âncora de Fenda",
    观景点: "Mirante",
    // Treasures
    神秘宝藏: "Caixa Mística", //Updated Name Ingame One
    神秘宝箱: "Caixa Mística", //Updated Name Ingame One
    武器箱: "Caixa armas",
    装备箱: "Caixa Armadura",
    隐藏宝箱: "Caixa Oculta",
    秘藏宝箱: "Caixa tesouro escondida",
    宝箱怪: "Caixa Mórfica",
    储物箱: "Caixa armazenamento",
    // Explore
    精英怪: "Elite",
    迷雾区域: "Evento de nevoeiro",
    防守工坊: "Oficina",
    移动房屋: "Mudança de casa",
    限时事件: "Evento Vermelho",
    灭绝者: "Tecelão do Caos",
    "灭绝者(二阶段)": "Tecelão do Caos (Estágio 2)",
    "灭绝者(三阶段)": "Tecelão do Caos (Estágio 3)",
    "冰灭绝者(一阶段)": "Tecelão do Caos de Gelo (Estágio 1)",
    "冰灭绝者(二阶段)": "Tecelão do Caos de Gelo (Estágio 2)",
    "冰灭绝者(三阶段)": "Tecelão do Caos de Gelo (Estágio 3)",
    "冰灭绝者(二/三阶段)": "Tecelão do Caos de Gelo (Estágio 2/3)",
    "冰灭绝者(一/四阶段)": "Tecelão do Caos de Gelo (Estágio 1/4)",
    "冰灭绝者(二/四阶段)": "Tecelão do Caos de Gelo (Estágio 2/4)",
    "冰灭绝者(三/四阶段)": "Tecelão do Caos de Gelo (Estágio 3/4)",
    "冰灭绝者(二/三/四阶段)": "Tecelão do Caos de Gelo (Estágio 2/3/4)",
    "冰灭绝者(四阶段)": "Tecelão do Caos de Gelo (Estágio 4)",
    "火灭绝者(二阶段)": "Tecelão do Caos de Fogo (Estágio 2)",
    "火灭绝者(三阶段)": "Tecelão do Caos de Fogo (Estágio 3)",
    "火灭绝者(四阶段)": "Tecelão do Caos de Fogo (Estágio 4)",
    "火灭绝者(一/四阶段)": "Tecelão do Caos de Fogo (Estágio 1/4)",
    "火灭绝者(二/四阶段)": "Tecelão do Caos de Fogo (Estágio 2/4)",
    "火灭绝者(三/四阶段)": "Tecelão do Caos de Fogo (Estágio 3/4)",
    "火灭绝者(二/三/四阶段)": "Tecelão do Caos de Fogo (Estágio 2/3/4)",
    // Collection
    武器配件: "Acessórios Arma", // "Weapon Attachments" is too long and breaks the UI
    食谱: "Receita",
    收容物: "Mutações",
    诡谲画作: "Pintura Misteriosa",
    矿物点: "Mineral",
    采集点: "Material",
    种子箱: "Baú de Sementes",
    调味料箱: "Baú de especiarias",
    种子香料: "Sementes e Especiarias",
    饮料机: "Máquina de bebidas",
    随机素材箱: "Baú Aleatório",
    抗菌剂箱: "Baú de remédios",
    // PvP
    回响石: "Pedra Eco",
    // Hint
    留言: "Dica",
    隐藏任务: "Missão paralela",
    支线任务: "Missão paralela",
    商人: "Comerciante",
    宜居地点: "Localização habitável",
    // Regions
    代顿湿地: "Pântanos de Dayton",
    破碎三角洲: "Delta Quebrado",
    垩峰山: "Pico de Giz",
    铁锈河: "Rio de Ferro",
    孤狼荒原: "Areias Vermelhas",
    黑心地带: "Coração Negro",
    玛瑙冻原: "Tundra ônix",
    维纳峡湾: "Fiorde de Vena",
    余烬滩: "Praia de Brasa",
    // Routes
    // No need to translate the fuel count number.
    怪物巴士路线: "Ônibus Monstro",
    便携混合燃油: "Combustível Misto Portátil",
    // Areas
    污染区: "Área Contaminada",
    污染值: "Valor da poluição",
    建筑无法幸存: "O edifício não pode sobreviver",
    建筑会受损: "Prédio será danificado",
    被发现范围: "Faixa de alerta",
    // Teleporters - 传送塔
    猎犬岛传送塔: "Torre de Teletransporte",
    望岛镇传送塔: "Torre de Teletransporte",
    离岸广场传送塔: "Torre de Teletransporte",
    临溪东部传送塔: "Torre de Teletransporte",
    贪欲巨楔传送塔: "Torre de Teletransporte do Monólito da Ganância",
    代顿检查点传送塔: "Torre de Teletransporte",
    高岸南部传送塔: "Torre de Teletransporte",
    西格玛传送塔: "Torre de Teletransporte",
    暖阳中部传送塔: "Torre de Teletransporte",
    三角洲南部传送塔: "Torre de Teletransporte",
    盖亚山区传送塔: "Torre de Teletransporte",
    盖亚巨楔传送塔: "Torre de teletransporte do monólito do penhasco de Gaia",
    代顿北部传送塔: "Torre de Teletransporte",
    高地西部传送塔: "Torre de Teletransporte",
    盖亚西部传送塔: "Torre de Teletransporte",
    朽鞍镇传送塔: "Torre de Teletransporte",
    银滩北部传送塔: "Torre de Teletransporte",
    翠湖南部传送塔: "Torre de Teletransporte",
    翠湖北部传送塔: "Torre de Teletransporte",
    阿尔法传送塔: "Torre de Teletransporte",
    月湖传送塔: "Torre de Teletransporte",
    庄园东部传送塔: "Torre de Teletransporte",
    尖牙巨楔传送塔: "Torre de Teletransporte Monólito da Sede",
    蜿蜒山区传送塔: "Torre de Teletransporte",
    波光北部传送塔: "Torre de Teletransporte",
    黯梦巨楔传送塔: "Torre de teletransporte Mirage Monolith",
    风角边境传送塔: "Torre de Teletransporte",
    谷地南部传送塔: "Torre de Teletransporte",
    西塔传送塔: "Torre de Teletransporte",
    黑原中部传送塔: "Torre de Teletransporte",
    遗忘巨楔传送塔: "Torre de Teletransporte do Monólito Abandonado",
    悬巢北部传送塔: "Torre de Teletransporte",
    悬巢南部传送塔: "Torre de Teletransporte",
    内部传送塔: "Torre de Teletransporte",
    巨人阶梯传送塔: "Torre de Teletransporte",
    黑心内弯传送塔: "Torre de Teletransporte da Baía do Coração Negro",
    //Way of Winter - 雪国人生
    //"望海传送塔": "Torre de Teletransporte", //Way of Winter - 10/19/24
    冻火湾传送塔: "Torre de Teletransporte da Forja Congelada", //Way of Winter - 10/19/24
    冻火北部传送塔: "Torre de Teletransporte Frost Norte", //Way of Winter - 10/19/24
    鲸骨湾传送塔: "Torre de teletransporte da Baía Whalebone", //Way of Winter - 10/19/24
    山阴传送塔: "Torre de teletransporte à sombra da montanha", //Way of Winter - 10/19/24
    水畔传送塔: "Torre de teletransporte à beira-mar", //Way of Winter - 10/19/24
    港区传送塔: "Torre de Teletransporte do Distrito Harbour", //Way of Winter - 10/19/24
    绿野传送塔: "Torre de teletransporte de campo verde", //Way of Winter - 10/19/24
    乐园传送塔: "Torre de teletransporte Wish Land", //Way of Winter - 10/19/24
    望海传送塔: "Torre de teletransporte com vista para o mar", //Way of Winter - 10/19/24
    林场传送塔: "Torre de teletransporte Woodland Ranch", //Way of Winter - 10/19/24
    慕斯市传送塔: "Torre de teletransporte de Moose City", //Way of Winter - 10/19/24
    潮间地传送塔: "Torre de Teletransporte Tidal Bore", //Way of Winter - 10/19/24
    黑石东部传送塔: "Torre de Teletransporte East Blackstone", //Way of Winter - 10/19/24
    黑石北部传送塔: "Torre de Teletransporte North Blackstone", //Way of Winter - 10/19/24
    冻原中部传送塔: "Torre Central de Teletransporte da Tundra", //Way of Winter - 10/19/24
    大河警戒区传送塔: "Torre de Teletransporte da Zona de Exclusão Taiga", //Way of Winter - 10/19/24
    母巢巨穴传送塔: "Torre de teletransporte da caverna Hiverail", //Way of Winter - 10/19/24
    破碎岩礁传送塔: "Torre de teletransporte de Recifes Quebrados", //Way of Winter - 10/19/24
    雪崩巨楔传送塔: "Torre de Teletransporte do Monólito Avalanche", //Way of Winter - 10/21/24
    雪崖传送塔: "Torre de Teletransporte Snow Cliffs", //Way of Winter - 10/21/24
    冻火西部传送塔: "Torre de Teletransporte Frost West", //Way of Winter - 10/21/24
    烟袋群岛传送塔: "Torre de Teletransporte Pipe Island", //Way of Winter - 10/21/24
    蛇眼山口传送塔: "Torre de teletransporte SnakeEye Pass",
    蛇腹传送塔: "Torre de teletransporte SnakeBelly",
    蛇尾传送塔: "Torre de teletransporte SnakeTail",
    熟土区传送塔: "Torre de teletransporte de terra madura",
    火喉北部传送塔: "Torre de Teletransporte Norte da Garganta de Fogo",
    火喉东部传送塔: "Torre de Teletransporte Leste da Garganta de Fogo",
    火喉飞升传送塔: "Torre de teletransporte Fire Throat Rise",
    火喉根基传送塔: "Torre de teletransporte da base da garganta de fogo",
    灰落传送塔: "Torre de teletransporte AshenTon",
    寂火传送塔: "Torre de Teletransporte SilentFire",
    灼风传送塔: "Torre de teletransporte BlazeWind",
    硫磺池传送塔: "Torre de Teletransporte da Piscina de Enxofre",
    炽尘巨楔传送塔: "Torre de teletransporte FireDust",

    // Monoliths - 巨楔
    贪欲巨楔: "Monólito da Ganância",
    盖亚巨楔: "Monólito do Penhasco de Gaia",
    黯梦巨楔: "Monólito Miragem",
    尖牙巨楔: "Monólito da Sede",
    遗忘巨楔: "Monólito Abandonado",
    //Way of Winter - 雪国人生
    冻原巨楔: "Monólito da Tundra", //Way of Winter - 10/19/24
    雪崩巨楔: "Monólito de Avalanche", //Way of Winter - 10/19/24
    炽尘巨楔: "Monólito de Pó de Fogo",
    // Settlements - 主城
    旅人营地: "Vila Morta",
    迈尔集市: "Mercado de Meyer",
    秽水营地: "Acampamento de Águas Cinzentas",
    深草旅店: "Pousada Grama Alta",
    黑原镇: "Blackfell",
    //Way of Winter - 雪国人生
    遗忘之地: "Esquecimento", //Way of Winter - 10/19/24
    熊栖雪场: "Covil do Urso", //Way of Winter - 10/19/24
    鲸骨乡: "Osso de baleia", //Way of Winter - 10/19/24
    冰屋营地: "Acampamento da Casa de Gelo", //Way of Winter - 10/19/24
    不落号坠落点: "Local de acidentes",

    // Labs - 研究所
    生命进化研究所: "Instituto de Evolução HP",
    "”黑域“之门": "Entrada da Zona de Neblina", //Way of Winter - 10/21/24

    // Towns - 大型资源点
    中途镇: "Através deville",
    腐烂庄园: "Mansão Podre",
    橘子镇: "Condado de cítricos",
    望岛镇: "Ignorar a cidade",
    苏德兰果园: "Pomar da Família Sutherland",
    离岸广场: "Praça Costeira",
    临溪: "Brookham",
    代顿医院: "Hospital Dayton",
    贪欲巨楔警戒区: "Zona de perigo do monólito da ganância",
    赫斯特工业: "Indústrias Hearst",
    海港镇: "Zona portuária",
    猎犬岛哨站: "Posto Avançado da Ilha do Cão Selvagem",
    暖阳中学: "Escola Secundária Sunbury",
    暖阳镇: "Sunbury",
    苏德兰化工厂: "Fábrica Química Sutherland",
    高岸镇: "Bancos Altos",
    废弃货场: "Ferro-velho",
    盖亚研究所遗址: "Ruínas do Centro de Pesquisa de Gaia",
    东部铁路枢纽: "Junção Ferroviária Oriental",
    盖亚巨楔警戒区: "Zona de perigo do monólito do penhasco de Gaia",
    高地: "Terras Altas",
    冶炼厂污染点: "Planta de Poluição de Refinaria",
    秽水工业区: "Zona Industrial de Águas Cinzentas",
    阿卡尔克镇: "Alkirk",
    东黑原枢纽: "Junção Leste de Blackfell",
    波光镇: "Rippleby",
    里奇收容点: "Ponto de segurança Ricci",
    黯梦巨楔警戒区: "Zona de Perigo do Monólito Mirage",
    盖亚军事基地: "Base Militar de Gaia",
    朽鞍镇: "Sela Podre",
    银滩度假区: "Silvershore Resort",
    碧湖山镇: "Colina do Lago Verde",
    霍特镇: "Cidade Holt",
    熔炉巢穴: "Covil da Fornalha",
    常青藤酒庄: "Vinhedo Evergreen",
    阿尔法研究所: "Instituto Alfa",
    尖牙巨楔警戒区: "Monólito da Zona de Perigo da Sede",
    交错现实研究所: "Instituto de Pesquisa de Realidade Alternativa",
    黑原油田: "Campos de petróleo de Blackfell",
    黑原陷落区: "Zona Caída de Blackfell",
    绿荫镇: "Sempre-viva",
    悬巢: "Forte Eyrie",
    "73号源质分离点": "73 Ponto de Extração de Fonte",
    太阳农场: "Fazenda do Sol",
    白崖基地: "Penhasco Branco",
    //Way of Winter - 雪国人生
    灼风气象站: "Observatório do Vento Escaldante", //Way of Winter - 10/19/24
    炎神研究所: "Centro de Pesquisa Deus do Fogo", //Way of Winter - 10/19/24
    圣城前哨: "Arredores da Garganta de Fogo", //Way of Winter - 10/19/24
    火喉下城: "Fortaleza da Garganta de Fogo", //Way of Winter - 10/19/24
    灰落车站: "Estação Ashton", //Way of Winter - 10/19/24
    熟土农庄: "Fazenda de terra madura", //Way of Winter - 10/19/24
    蛇尾滑索营地: "Acampamento Cauda da Serpente", //Way of Winter - 10/19/24
    火喉弃民街: "Favelas da Garganta de Fogo", //Way of Winter - 10/19/24
    燃尽之地: "Deserto Carbonizado", //Way of Winter - 10/19/24
    废弃提炼厂: "Refinaria Abandonada", //Way of Winter - 10/19/24
    攀火祭祀场: "Aspecto Fogo", //Way of Winter - 10/19/24
    望火港: "Porto de Vigília de Fogo", //Way of Winter - 10/19/24
    烟袋度假区: "Tabcco Resort", //Way of Winter - 10/19/24
    黑石灯塔: "Farol Obsidiano", //Way of Winter - 10/19/24
    异火码头: "Porto Pyro", //Way of Winter - 10/21/24
    无明港: "Porto sem luz", //Way of Winter - 10/21/24
    蛇眼瞭望点: "Mirante Olho de Cobra", //Way of Winter - 10/21/24
    蛇腹洞穴: "Caverna Barriga de Cobra", //Way of Winter - 10/21/24
    纵队巡逻点: "Ponto Partrol da Guerrilha", //Way of Winter - 10/21/24
    硫磺池采伐区: "Pedreira de Enxofre", //Way of Winter - 10/21/24
    温泉民宿: "Pousada Fontes Termais", //Way of Winter - 10/21/24
    火喉圣域: "Fortaleza da Garganta de Fogo", //Way of Winter - 10/21/24 (Might not be accurate) <--- Come Back
    冻火湾: "Forja Gélida", //Way of Winter - 10/21/24
    避火者地堡: "Santuário das Chamas", //Way of Winter - 10/21/24
    炽尘巨楔警戒区: "Zona de perigo do monólito de poeira de fogo", //Way of Winter - 10/21/24
    "“母巢”收容保护区": "Área restrita do Hiverail", //Way of Winter - 10/21/24
    雪崩巨楔警戒区: "Zona de perigo do monólito de avalanche", //Way of Winter - 10/21/24
    雪原气象站: "Ponto de verificação do campo de neve", //Way of Winter - 10/21/24
    悬空哨卡: "Ponto de verificação suspenso", //Way of Winter - 10/21/24
    冻原巨楔警戒区: "Zona de perigo do monólito da tundra", //Way of Winter - 10/21/24
    检测点653: "Ponto de Inspeção 653", //Way of Winter - 10/21/24
    "“大河”收容场": "Zona de Abrigo “Grande Rio”", //Way of Winter - 10/21/24
    罗塞塔巡逻站: "Estação de Patrulha Rosetta", //Way of Winter - 10/21/24
    慕斯市食品厂: "Fábrica de alimentos em Moose City", //Way of Winter - 10/21/24
    慕斯市: "Cidade dos Alces", //Way of Winter - 10/21/24 (Partial Guess Based on Teleporter)
    慕斯市郊废屋: "Casa abandonada nos arredores de Moose City", //Way of Winter - 10/21/24
    栖木岭观景台: "Balcão de observação do prospecto de árvores empoleiradas", //Way of Winter - 10/21/24
    栖木缆车站: "Estação de teleférico empoleirando-se na árvore", //Way of Winter - 10/21/24
    藏火岩洞: "Caverna do Couro de Fogo", //Way of Winter - 10/21/24
    黑石要塞: "Fortaleza de Pedra Negra", //Way of Winter - 10/21/24
    "“心愿奇境”西园区": "Terra dos Desejos Oeste", //Way of Winter - 10/21/24
    "“心愿奇境”东园区": "Terra dos Desejos Leste", //Way of Winter - 10/21/24
    乐园东入口: "Entrada leste de Wishland", //Way of Winter - 10/21/24
    乐园西入口: "Entrada oeste de Wishland", //Way of Winter - 10/21/24
    滑索洞穴营地: "Acampamento na caverna com tirolesa", //Way of Winter - 10/21/24
    融冰港: "Porto de derretimento de gelo", //Way of Winter - 10/21/24
    菲斯库尔港: "Porto de Peixe", //Way of Winter - 10/21/24
    影日洞穴: "Caverna da Proteção Solar", //Way of Winter - 10/21/24
    灰落市: "Ashenton", //Way of Winter - 10/21/24

    // Villages
    中途镇变电站: "Subestação de Throughville",
    检测点3771: "Ponto de Inspeção 3771",
    翻车鱼岛游客中心: "Centro de Visitantes da Ilha Mola",
    海岬庄园: "Mansão do Cabo",
    小码头: "Pequeno Porto",
    艾尔汽修店: "Reparação Automóvel de Aiden",
    艾尔的隐蔽所: "Esconderijo de Aiden",
    检测点7802: "Ponto de Inspeção 7802",
    临溪警戒所: "Guarita de Brookham",
    代顿货栈: "Armazém Dayton",
    崖下营地: "Acampamento no penhasco",
    北岸营地: "Acampamento Costa Norte",
    赫斯特: "coração",
    赫斯特滩涂: "Lodaçais de Hearst",
    湖心野营地: "Acampamento Lakeheart",
    迈尔: "Meyer",
    高岸巢穴: "Ninho do banco alto",
    废弃隐蔽所: "Esconderijo Abandonado",
    骑士修车店: "Reparos de veículos cavaleiros",
    山脊中转站: "Estação de transferência de Ridge",
    山脊营地: "Acampamento Ridge",
    暖阳农庄: "Fazenda Sunbury",
    瀑布广场: "Praça da Cachoeira",
    沉船坟场: "Cemitério de navios",
    沉没宅院: "Casa afundada",
    检测点024: "Ponto de Inspeção 024",
    检测点9043: "Ponto de Inspeção 9043",
    "TAB-6A营地": "Acampamento Tab-6A",
    高地居住区: "Zona Residencial das Terras Altas",
    洗劫一空的营地: "Acampamento saqueado",
    远眺伐木场: "Ignorar a madeireira",
    污染检测点77: "Ponto de Inspeção de Poluição 77",
    河心码头: "Porto de Riverhart",
    河畔纪念品店: "Lembranças à beira-rio",
    枯竭油井: "Poço de petróleo esgotado",
    蜿蜒山种植园: "Fazendas sinuosas em Ridge",
    浅滩公园: "Parque Shoal",
    波光镇集市: "Mercado Rippleby",
    风车阵列: "Parque Eólico",
    秘港: "Porto Secreto",
    检测点023: "Ponto de Inspeção 023",
    克里夫顿: "Clifton",
    海风疗养地: "Breezy Shores Resort",
    诺顿农场: "Fazenda Norton",
    高岸检测点: "Ponto de Inspeção Highbank",
    私酿庄园: "Propriedade da cervejaria",
    老大的乐园: "O playground do chefe",
    霍特电站: "Central Elétrica de Holt",
    帕斯利广场: "Praça Paisley",
    山麓别墅: "Herdade montanhosa",
    盖亚通讯阵列: "Matriz de Comunicação Gaia",
    检测点266: "Ponto de Inspeção 266",
    狂热信徒聚落: "Colônia dos Crentes",
    戴维斯角: "Ponto Davis",
    鞍前营地: "Acampamento Saddlefront",
    渔人码头: "Cais dos Pescadores",
    格尔峰电站: "Poder do Monte Guel",
    检测点091: "Ponto de Inspeção 091",
    妮娜奶奶的水果餐吧: "Jantar da vovó Nina",
    检测点384: "Ponto de Inspeção 384",
    矿镇: "Cidade mineira",
    翠湖游客中心: "Centro de visitantes de Greenlake",
    //Way of Winter - 雪国人生
    搁浅滩涂: "Lodaçais encalhados", //Way of Winter - 10/19/24
    海边旧屋: "Cabana à beira-mar", //Way of Winter - 10/21/24
    洞口营地: "Acampamento na Boca da Caverna", //Way of Winter - 10/21/24
    破败码头: "Abandonado jogado", //Way of Winter - 10/21/24
    幽谷民居: "Residência Vale", //Way of Winter - 10/21/24
    废弃水塔: "Torre de água abandonada", //Way of Winter - 10/21/24
    瞭望处: "Olhe", //Way of Winter - 10/21/24
    松林猎场: "Campo de Caça de Pinheiros", //Way of Winter - 10/21/24
    纵队前哨: "Posto Avançado de Guerrilha", //Way of Winter - 10/21/24
    废弃避难所: "Abrigo Abandonado", //Way of Winter - 10/21/24
    干涸码头: "Porto Seco", //Way of Winter - 10/21/24
    林场: "Floresta", //Way of Winter - 10/21/24
    潮间地农场: "Fazenda da Zona das Marés", //Way of Winter - 10/21/24
    食品厂货栈: "Armazém de Fábrica Doce", //Way of Winter - 10/21/24
    悬索营地: "Acampamento de cabo", //Way of Winter - 10/21/24
    栈道木屋: "Cabana no calçadão", //Way of Winter - 10/21/24
    废弃探险营地: "Acampamento de Expedição Abandonado", //Way of Winter - 10/21/24
    悬索货栈: "Armazém de cabos", //Way of Winter - 10/21/24
    荒废农庄: "Fazenda Abandonada", //Way of Winter - 10/21/24
    鲸骨遗迹: "Ruínas de Ossos de Baleia", //Way of Winter - 10/21/24
    瞭望点: "Mirante", //Way of Winter - 10/21/24
    路边野餐: "Piquenique na estrada", //Way of Winter - 10/21/24
    古船农场: "Antiga Fazenda de Navios", //Way of Winter - 10/21/24
    临时调查营地: "Campo de Investigação Temporário", //Way of Winter - 10/21/24
    倒挂遗迹: "Ruínas Invertidas", //Way of Winter - 10/21/24
    幽灵渔村: "Baía Fantasma", //Way of Winter - 10/21/24
    悬船冰洞: "Enseada do navio oscilante", //Way of Winter - 10/21/24
    断桥: "Ponte desabada", //Way of Winter - 10/21/24
    暖火营地: "Acampamento Fogo Quente", //Way of Winter - 10/21/24
    雪松小屋: "Cabana de Cedro", //Way of Winter - 10/21/24

    // Securement Silos - 收容井
    "收容井-西格玛": "Silo de Segurança - Sigma",
    "收容井-斐": "Silo de Segurança - Phi",
    "收容井-暗狱": "Silo de Segurança EX1",
    "收容井-阿尔法": "Silo de Segurança - Alfa",
    "收容井-寒境": "Silo de Segurança - Psi",
    "收容井-西塔": "Silo de Segurança - Theta",
    "收容井·塔乌": "Silo de Segurança 08",

    // Rift Anchors - 位面锚 // 空间锚点 = Rift Anchor
    //Way of Winter - 雪国人生
    "空间锚点·断桥": "Âncora de Rift - Ponte Desabada", //Way of Winter - 10/21/24
    "空间锚点·“心愿奇境”": "Âncora de Rift - Wishland - Oeste", //Way of Winter - 10/21/24
    "空间锚点·慕斯市食品厂": "Âncora Rift - Fábrica de Doces Mousseville", //Way of Winter - 10/21/24
    "空间锚点·慕斯市": "Âncora do Rift - Mousseville", //Way of Winter - 10/21/24
    "空间锚点·搁浅滩涂": "Âncora de Rift - Pântano Encalhado", //Way of Winter - 10/21/24
    "空间锚点·烟袋度假区": "Âncora do Rift - Tabacco Resort", //Way of Winter - 10/21/24
    "空间锚点·悬船冰洞": "Âncora de Rift - Enseada de Navio Pendente", //Way of Winter - 10/21/24
    "空间锚点·菲斯库尔港": "Âncora do Rift - Porto de Fiskur", //Way of Winter - 10/21/24
    "空间锚点·“母巢”收容保护区": "Âncora de Rift - Área Restrita do Hiverail", //Way of Winter - 10/21/24
    "空间锚点·黑石要塞": "Âncora da Fenda – Acampamento Obsidiano", //Way of Winter - 10/21/24
    "空间锚点·“大河”收容场": "Âncora Rift - Centro de Contenção Taiga", //Way of Winter - 10/21/24
    "空间锚点·冻火湾": "Âncora de Fenda - Forja Congelada", //Way of Winter - 10/21/24
    "空间锚点·“黑域”之门": "Rift Anchor – Entrada da Zona de Neblina", //Way of Winter - 10/21/24
    "空间锚点·致命信号": "Âncora de Rift - Sinal Fatal", //Way of Winter - 10/21/24
    "空间锚点·蛇腹洞穴": "Âncora da Fenda - Caverna SunShroud",
    "空间锚点·蛇尾滑索营地": "Âncora da Fenda – Acampamento Cauda da Serpente",
    "空间锚点·燃尽之地": "Âncora de Rift - WasteLand carbonizado",
    "空间锚点·废弃提炼厂": "Rift Anchor – Refinaria Abandonada",
    "空间锚点·火喉下城": "Âncora da Fenda – Fortaleza da Garganta de Fogo",
    "空间锚点·灰落市1": "Âncora de Fenda - AshenTon 1",
    "空间锚点·灰落市2": "Âncora de Fenda - AshenTon 2",
    "空间锚点·炎神研究所": "Rift Anchor - Centro de Pesquisa do Deus do Fogo",
    "空间锚点·温泉民宿": "Âncora do Rift - Hot Spring Inn",
    "空间锚点·塔乌": "Âncora Rift - Silo de Fixação 08",

    // has no individual names yet in chinese
    // Mysterious Chests - 神秘宝藏
    // has no individual names
    // Weapon Crates - 武器箱
    // has no individual names
    "武器箱【剧情箱子】": "Caixa Armas【História】",
    // Gear Crates - 装备箱
    // has no individual names
    // Hidden Crates - 隐藏宝箱
    // has no individual names
    // Morphic Crates - 宝箱怪
    // has no individual names
    // Storage Crates - 储物箱
    // has no individual names
    // Elites - 精英怪
    暴食狂: "Glutão",
    屠夫: "Árbitro",
    裁决者: "Árbitro",
    星尘簇: "Andarilho Estelar",
    门徒: "Discípulo",
    雨壳: "Ceifador de chuva",
    腐坏眼虫: "Máquina de Garra", // Chagas Weevil
    娃娃机: "Máquina de Garra", // Chagas Weevil
    抓娃娃机: "Máquina de Garra", // Chagas Weevil
    唤生之母: "Mãe da Vida",
    唤生水母: "Mãe da Vida",
    熔烛: "Vela Molton",
    乐园向导: "Menino Balão",
    夜魇: "Cervitauro",
    天气预报: "Previsão do tempo",
    罪人守望: "Sentinela Pecadora",
    //"”教练“ 【清剿目标】": "", //removed?
    //'"龙脊" 科利·兰根': "", //removed?
    罗塞塔防暴员: "Rosetta Bruiser",
    罗塞塔机械师: "Mecânico Roseta",
    罗塞塔重装员: "Roseta Pesada",
    // Fog Events - 迷雾区域
    // has no individual names
    // Workshops - 防守工坊
    // has no individual names
    // Moving Houses - 移动房屋
    // has no individual names
    // Red Events - 限时事件
    这里没有迪斯科: "Para onde vai a discoteca?",
    湖之暗面: "O lado negro",
    //"": "Corrida de carga"
    挖通地狱: "Cavar para o Inferno",
    腐乐园: "Paraíso Perdido",
    喀戎行动: "Operação Quíron",
    // Accessories - 武器配件
    // Weapon Attachments - 武器配件
    // Optics - 瞄具配件
    轻量化红点瞄具: "Visão Reflexa de Luz",
    战斗侦查瞄具: "Óptica de Combate Recon",
    反射式瞄具: "Visão Reflexa",
    精准步枪瞄具: "Mira de rifle de precisão",
    战术全像瞄准镜: "Visão holográfica tática",
    精准光学瞄具: "Óptica de Precisão",
    战术步枪瞄具: "Mira de rifle tático",
    轻型光学瞄具: "Óptica de Luz",
    中距离战术瞄具: "Óptica de médio alcance",
    密封型反射式瞄具: "Visão Reflexa Selada",
    紧凑型反射式瞄具: "Visão Reflexa Compacta",
    棱镜式瞄具: "Visão Prismática",
    远距离战术瞄具: "Visão Tática de Longo Alcance",
    大型光学瞄具: "Grande visão óptica",
    紧固型微型红点瞄具: "Mira Mini Reflex Fixada",
    微型红点瞄具: "Mini Visão Reflexa",
    先进战斗光学瞄具: "Óptica de Combate Avançada",
    全像瞄准镜: "Visão Holográfica",
    // Muzzle Attachments - 枪口配件
    鱼鹰抑制器: "Supressor de Osprey",
    集成型补偿器: "Compensador Integrado",
    多用途霰弹枪抑制器: "Supressor de espingarda multiuso",
    锤头型补偿器: "Compensador de martelo",
    短型抑制器: "Supressor Curto",
    战术消焰器: "Esconder Flash Tático",
    小型补偿器: "Compensador Pequeno",
    加长型制退器: "Freio Estendido",
    一体式抑制器: "Supressor Integrado",
    小型制退器: "Freio de boca pequeno",
    一体式消焰器: "Esconder Flash Integrado",
    //"多孔式消焰器": "", // Multi-Hole Flash Hider
    伪装用抑制器: "Supressor de Camuflagem",
    大型抑制器: "Supressor Grande",
    大型枪口制退器: "Freio Grande",
    前向消焰器: "Avançar Flash Hider",
    消焰器: "Esconder Flash",
    轻量化制退器: "Freio leve",
    基础抑制器: "Supressor Básico",
    紧凑型制退器: "Freio Compacto",
    霰弹枪制退器: "Freio de espingarda",
    // Tactial Attachments - 战术配件
    小型红外指示器: "Mini Mira Reflex, Infravermelho Pequeno",
    前护手握把: "Aperto de proteção frontal",
    后护手握把: "Aperto de proteção traseira",
    大型激光指示器: "Grande mira laser",
    集成型激光指示器: "Mira Laser Integrada",
    角型握把: "Aperto triangular",
    战术激光指示器: "Mira Laser Tática",
    小型激光指示器: "Mira laser pequena",
    轻质前握把: "Punho frontal leve",
    轻质水平握把: "Punho horizontal leve",
    战术手电筒: "Lanterna Tática",
    红外指示器: "Indicador infravermelho",
    紧凑型红外指示器: "Indicador infravermelho compacto",
    战术组合握把: "Aperto Combinado Tático",
    眼镜蛇握把: "Aperto Cobra",
    垂直握把: "Aperto Vertical",
    紧凑型手电筒: "Lanterna Compacta",
    激光指示器: "Mira Laser",
    折叠脚架: "Bipé dobrável",
    // Magazines - 弹匣配件
    狙击枪战术弹匣: "Mag tático SR",
    轻机枪校准弹鼓: "LMG Drum Mag calibrado",
    狙击枪改良弹匣: "Revista SR alterada",
    步枪轻量化弹匣: "Carregador de rifle leve",
    冲锋枪加重型弹匣: "SMG Mag ponderado",
    轻机枪大型弹鼓: "Carregador de bateria LMG grande",
    手枪战术型弹匣: "Carregador de pistola tática",
    冲锋枪战术型弹匣: "SMG Tático Mag",
    步枪扩容弹匣: "Carregador de rifle estendido",
    手枪加长型弹匣: "Carregador de Pistola Estendido",
    手枪改良弹匣: "Carregador de pistola alterado",
    冲锋枪改良弹匣: "Revista SMG alterada",
    步枪改良弹匣: "Revista de rifle alterada",
    // Puzzle Types
    异常门扉: "Quebra-cabeça da porta",
    异常路牌: "Outdoor quebrado",
    广告牌异常: "Outdoor quebrado",
    破碎山石异常: "Rocha Quebrável",
    异常电话亭: "Cabine telefônica",
    异常雕像: "Estátuas de quebra-cabeça",
    黑水相机: "Emote de câmera",
    //"": "Freio compacto (precisa de pintura misteriosa)",
    "诡谲画作: 小型制退器": "Freio de boca pequeno (precisa de pintura misteriosa)",
    "诡谲画作: 轻型光学瞄具": "Light Optic (precisa de pintura misteriosa)",
    "诡谲画作: 小型激光指示器": "Mira laser pequena (precisa de pintura misteriosa)",
    "诡谲画作: 战术步枪瞄具":
      "Mira de rifle tático (precisa de pintura misteriosa)",
    "诡谲画作: 前向消焰器": "Forward Flash Hider (precisa de pintura misteriosa)",
    // Attachment Dupes with Spelling differences
    战斗侦察瞄具: "Óptica de Combate Recon",
    "反射式瞄具·黑色": "Visão Reflexa",
    角形握把: "Aperto triangular",
    霰弹枪式制动器: "Freio de espingarda",
    密封型反射瞄具: "Visão Reflexa Selada",
    "多用途霰弹枪抑制器(6226,-588)": "Supressor de espingarda multiuso (6226,-588)", // Keep coordinates when available
    "大型光学瞄具,黑心地带(3039,990)": "Mira óptica grande (3.039.990)",
    "大型光学瞄具,黑心地带(3037,-979)": "Mira óptica grande (3037,-979)",
    手枪加强型弹匣: "Carregador de Pistola Estendido",
    "诡谲画作：小型制退器": "Freio de boca pequeno (precisa de pintura misteriosa)",
    "诡谲画作：轻型光学瞄具": "Light Optic (precisa de pintura misteriosa)",
    "诡谲画作：小型激光指示器": "Mira laser pequena (precisa de pintura misteriosa)",
    "诡谲画作：战术步枪瞄具":
      "Mira de rifle tático (precisa de pintura misteriosa)",
    "诡谲画作：前向消焰器": "Forward Flash Hider (precisa de pintura misteriosa)",
    "诡谲画作:战术步枪瞄具": "Mira de rifle tático (precisa de pintura misteriosa)",
    // Item Categories - 手枪
    手枪: "Pistolas",
    霰弹枪: "Espingardas",
    冲锋枪: "Submetralhadoras", // Submachine Guns
    步枪: "Fuzis",
    狙击枪: "Rifles de precisão",
    轻机枪: "metralhadoras leves", // Light Machine Guns
    弓弩: "Bestas",
    重型火器: "Armas Pesadas",
    刀剑: "Armas corpo a corpo",
    头盔: "Capacetes",
    面部: "Máscaras", // Face
    上身: "Coletes", // Top
    下身: "Calça", // Bottom
    手套: "Luvas",
    鞋子: "Sapato",
    瞄具配件: "Óptica",
    枪口配件: "Acessórios de focinho",
    战术配件: "Anexos Táticos",
    弹匣配件: "Revistas",
    碎弹模组: "Mods de estilhaços",
    霜寒模组: "Mods de vórtice gelado",
    爆弹模组: "Mods de bombardeiro instáveis",
    电涌模组: "Mods de surto de energia",
    标记模组: "Os mods do alvo",
    弹射模组: "Mods de salto",
    快枪手模组: "Mods de artilheiro rápido",
    灼烧模组: "Gravar mods",
    阵地模组: "Mods de guerra de fortaleza",
    武器通用: "Compatível com Arma", // ?
    头盔模组: "Mods de capacete",
    面部模组: "Mods de máscara", // Face mods
    上身模组: "Mods de colete", // Top mods
    下身模组: "Mods de calças", // Bottom Mods
    手套模组: "Mods de luvas",
    鞋子模组: "Mods de calçados",
    防具通用: "Compatível com Armadura", // ?
    近战通用: "Corpo a Corpo Geral", // ?
    流派效果: "Efeito de gênero", // ?
    模组后缀: "Sufixos de Módulo", // ?
    元素伤害: "Dano Elemental", // ?
    特殊子弹: "Balas Especiais", // ?
    套装碎片: "Definir fragmentos",
    素材: "Materiais",
    近战蓝图: "Projetos de armas corpo a corpo",
    手枪蓝图: "Projetos de pistola",
    霰弹枪蓝图: "Projetos de espingarda",
    冲锋枪蓝图: "Projetos SMG", // Submachine Gun Blueprints
    步枪蓝图: "Plantas de rifle",
    狙击枪蓝图: "Projetos de rifle de precisão",
    轻机枪蓝图: "Projetos de LMG", // Light Machine Gun Blueprints
    弓弩蓝图: "Projetos de besta",
    家具配方: "Plantas de móveis",
    肉类: "Carne",
    鱼类: "Peixe",
    药草: "Ervas",
    // Recipes - 食谱
    "食谱：熏肉罗宋汤": "Receita: Borscht Deluxe",
    "食谱：畸变塔可卷": "Receita: Taco", // In World item says Herbal Tea
    "食谱：星尘茶": "Receita: Chá Stardust",
    "食谱：培根肉排汉堡": "Receita: Hambúrguer de Bacon",
    "食谱：南瓜星空派": "Receita: Torta Stargazy",
    "食谱：消脂果汁": "Receita: suco para queimar gordura",
    "食谱：安全三明治": "Receita: Sanduíche de Segurança",
    "食谱：星尘水果罐头": "Receita: Alimentos Enlatados Diversos",
    "食谱：星尘通心粉罐头": "Receita: lata de sopa italiana Stardust",
    "食谱：奇迹茶": "Receita: Chá Milagroso",
    "食谱：碎裂面包": "Receita: Pão Estilhaçado",
    "食谱：星尘南瓜泥沙拉": "Receita: Salada de Abóbora Stardust",
    "食谱：幽光蘑菇罐头": "Receita: Cogumelo Enlatado Espectral",
    "食谱：星尘炸肉": "Receita: Cachorro Quente Misto Frito",
    "食谱：元宝饺子": "Receita: Bolinhos Yuanbao",
    "食谱：深海鱼片披萨": "Receita: pizza Stargazy",
    "食谱：炸薯条": "Receita: Batatas Fritas",
    "食谱：反重力奶昔": "Receita: Milkshake Antigravidade",
    "食谱：金钱饼": "Receita: Croquete",
    "食谱：特调冰酿": "Receita: cerveja gelada exclusiva",
    "食谱:奇思妙想饮": "Receita: Bebida Caprichosa",
    "食谱：炸鱼薯条": "Receita: Peixe e Batatas Fritas",
    "食谱：幽灵饼干": "Receita: biscoitos fantasmas",
    "食谱：畸变带骨香肠": "Receita: Salsicha Desviada com Osso",
    "食谱：捕获之汤": "Receita: Sopa de Segurança",
    "食谱：蜜酿炖肉": "Receita: Carne Glaceada com Mel",
    // Deviants - 收容物
    远归之蝶: "Emissário da Borboleta",
    活体凝胶: "Gel purulento",
    荣枯种子: "Semente colhida",
    捕梦网: "Apanhador de Sonhos",
    低语亡骨: "Caveira Canina",
    电鳗: "Enguia Elétrica",
    迪斯科球: "Bola de discoteca",
    发条青蛙: "Sapo, o saltador",
    极寒水母: "Geléia Polar",
    青龙: "Chefosaurus",
    蜂团团: "Abelha zumbida",
    工号37: "H37",
    //"": "Coelhinho buscar muito",
    姜饼屋: "Casa de pão de gengibre",
    核子打火机: "Isqueiro Atômico",
    凝视的黑猫: "Vazio Encantado",
    木工河狸: "Castor madeireiro",
    空间魔方: "Vira Espaço",
    元素小子: "Garoto Digby",
    雪景球: "Globo de neve",
    上界之卵: "Spawn do Mundo Superior",
    庞然大菇: "Cogumelo de crescimento",
    皆斩: "Zeno-Purificador",
    门扉: "Porta Estranha",
    //"": "Macaco de festa",
    巫毒娃娃: "Boneca vodu",
    炎之精: "Essência da Chama",
    破碎少女: "Donzela Despedaçada",
    迷你奇点: "Mini Maravilha",
    异维大猫: "Gato Extradimensional",
    球状闪电: "Orbe Relâmpago",
    迷你黄衣: "Mini Festa",
    小纸人: "Boneca de papel",
    //"": "Coelho letal",
    //"": "Toque de Artesão",
    愿望先生: "Senhor Desejo",
    红龙: "Piro Dino",
    熊医生: "Dr.",
    恶臭球根: "Bulbo mal-humorado",
    空之子: "Pelo Vento",
    //"": "Raposa de Lava",
    胡桃夹子: "Quebra-nozes",
    //"": "Máquina de desejos",
    蝶之梦: "Rebeca",
    气球狗: "Amigo cachorrinho",
    一碗美味: "Abraço em uma tigela",
    //"": "Pirâmide Maçônica",
    // Mysterious Painting - 诡谲画作
    "诡谲画作·代顿湿地": "Pintura Misteriosa · Pântanos de Dayton",
    "诡谲画作·破碎三角洲": "Pintura Misteriosa · Delta Quebrado",
    "诡谲画作·铁锈河": "Pintura Misteriosa · Rio de Ferro",
    "诡谲画作·垩峰山": "Pintura Misteriosa · Pico de Giz",
    "诡谲画作·孤狼荒原": "Pintura Misteriosa · Areias Vermelhas",
    "诡谲画作·黑心地带": "Pintura Misteriosa · Coração Negro",
    // Ores
    //"": "Pedra",
    硫磺: "Enxofre",
    铜矿: "Minério de cobre",
    锡矿: "Minério de Estanho",
    锡矿富集区: "Área de minério de estanho",
    铁矿: "Minério de Ferro",
    铝矿: "Minério de alumínio",
    钨矿: "Minério de tungstênio",
    银矿: "Minério de Prata",
    银矿区域: "Área de minério de prata",
    "银矿(稀有)": "Minério de Prata (Aleatório)",
    "银矿 (稀有)": "Minério de Prata (Aleatório)",
    金矿: "Minério de ouro",
    金矿区域: "Área de minério de ouro",
    "金矿(稀有)": "Minério de ouro (aleatório)",
    "金矿 (稀有)": "Minério de ouro (aleatório)",
    "金矿（先锋服)": "Mina de ouro",
    星尘矿: "Minério de poeira estelar",
    星尘矿石: "Minério de poeira estelar",
    星尘矿区: "Área de minério de poeira estelar",
    星尘矿区域: "Área de minério de poeira estelar",
    "星尘矿(稀有)": "Minério de poeira estelar (aleatório)",
    "星尘矿 (稀有)": "Minério de poeira estelar (aleatório)",
    // Plants
    橘子: "Laranjas",
    果蔬篮橘子: "Laranjas",
    小麦: "Trigo",
    果蔬篮小麦: "Trigo",
    红色浆果: "Baga de espinheiro",
    卷心菜: "Repolho",
    果蔬篮卷心菜: "Repolho",
    甜菜: "Beterraba",
    果蔬篮甜菜: "Beterraba",
    蓝莓: "Mirtilo",
    南瓜: "Abóbora",
    果蔬篮南瓜: "Abóbora",
    玉米: "Milho",
    果蔬篮玉米: "Milho",
    土豆: "Batata",
    果蔬篮土豆: "Batata",
    蘑菇: "Cogumelo",
    果蔬篮蘑菇: "Cogumelo",
    火刺果: "Espigão", //Way of Winter - 10/22/24
    阳姜: "Gengibre ensolarado", //Way of Winter - 10/22/24
    薄荷: "Hortelã", //Way of Winter - 10/22/24
    雪茸: "Fungo da neve", //Way of Winter - 10/22/24
    //"": "Pepino",
    //"": "Tomate",
    //"": "Tulipa Vermelha",
    //"": "Tulipa Amarela",
    //"": "Hortênsia Amarela",
    //"": "Hortênsia Azul",
    //"": "Petúnia Branca",
    //"": "Petúnia Azul",
    芦荟: "Aloe Vera",
    "鼠尾草 * 5": "Sábio * 5",
    "鼠尾草 * 8": "Sábio * 8",
    桔梗: "Campânula",
    金银花: "Madressilva",
    "金银花 * 3": "Madressilva * 3",
    "金银花 * 4": "Madressilva * 4",
    藏红花: "Açafrão",
    血菖蒲: "Cálamo Escarlate",
    紫锥菊: "Coneflor",
    黄莲花: "Lótus Amarelo",
    //"": "Pimenta em grão",
    苹果: "Maçã",
    苹果树: "Macieira",
    "苹果树 * 2": "Macieira * 2",
    //"": "Cacto",
    葡萄: "Uvas",
    贝壳岩石: "Rocha Concha",
    海草岩石: "Rocha de Algas Marinhas",
    观赏性花海: "Mar de Flores",
    香蕉树: "Bananeira",
    "香蕉树 * 2": "Bananeira * 2",
    "香蕉树 * 4": "Bananeira * 4",
    "香蕉树 * 6": "Bananeira * 6",
    "香蕉树 * 7": "Bananeira * 7",
    椰子树: "Coqueiro",
    "椰子树 * 3": "Coqueiro * 3",
    巨木: "Árvore Gigante",
    "龙血树(巨木)": "Árvore Gigante",
    // Animals
    野生动物: "Animais",
    兔子窝: "Toca do Coelho",
    鹿: "Cervo",
    星蚀鹿群: "Cervo",
    星蚀雄鹿: "Cervo",
    星蚀雌鹿: "Cervo",
    野猪: "Javali",
    野猪群: "Javali",
    星蚀鳄: "Jacaré",
    羊群: "Rebanho",
    花豹: "Leopardo",
    星蚀熊窝: "Covil do Urso",
    星蚀熊: "Urso",
    肉排: "Bife",
    鳄鱼蛋: "Ovos de jacaré",
    鸟蛋: "Ovos de pássaros",
    // Oil Wells
    原油油井: "Poço de petróleo",
    // Echo Stone - 回响石
    // has no individual names
    // Hints - 留言
    别靠近箱子: "Imitar",
    地堡门禁卡: "Cartão de acesso ao bunker",
    吓人箱子: "Imitar",
    空间异动: "Anomalia Espacial",
    地下入口: "Entrada subterrânea",
    电话亭: "Cabine telefônica",
    拟态怪储物箱: "Imitar",
    拟态宝箱怪: "Imitar",
    "密码: 5897": "Senha: 5897",
    "密码: 325": "Senha: 325",
    地下通道入口: "Entrada subterrânea",
    地下通道最近入口: "Entrada subterrânea",
    地窖入口: "Entrada subterrânea",
    山洞入口: "Entrada da Caverna",
    溶洞入口: "Entrada da caverna",
    镜女: "Inimigo Espelho",
    拟态储物箱别开: "Imitar",
    "电梯：负一层": "Elevador: Subterrâneo Nível 1",
    拟态宝箱怪别开: "Imitar",
    空间异常: "Anomalia Espacial",
    "5层楼梯": "5 escadas",
    箱子怪别开: "Imitar",
    下楼电梯: "Elevador",
    下楼电梯位置: "Elevador",
    隐藏宝箱最后位置: "Baú do Tesouro",
    抽屉柜: "Gavetas",
    混合矿场: "Mineração Mista",
    // Side Quests - 隐藏任务
    //"": "Uma perseguição milagrosa",
    隐藏的宝箱: "Tutorial de caixa mórfica", //
    //"异常档案": "",//Abnormal Files?
    //"": "O Farol Sombreado",
    玩具小熊: "O Chamado da Infância",
    "急救！急救！": "Hospital Dayton",
    //'"玩具熊"女孩': "", //Teddy Bear Girl?
    //"": "Época de colheita",
    //"": "A senhora perdida",
    //"": "Especialista em Desvio",
    //"": "Casa de Deus Marcial",
    信徒的藏宝图: "Perdido na Loucura - Ponto de Partida",
    信徒的财产箱: "Lost In Madness - Localização do Tesouro",
    //"": "Infiltração de poeira estelar",
    //"": "Um ato de roubo",
    检测点见闻: "Esboço de um ponto de inspeção",
    //"": "Linha de abastecimento",
    //"": "Onde o gato e os ratos brincam",
    红与黑: "Carnaval da Perdição",
    //"": "O Tesouro Infinito",
    //"": "Amor tristeza",
    //"": "Rock Estrangeiro",
    //"": "Expedição Inacabada",
    //"": "Distintivo Efemérida",
    //"": "Sabores Secretos",
    //"": "Salve Meta-Humano",
    //"": "Bem-vindo!",
    //"": "Garoto só quer se divertir",
    //"": "Para Sara",
    //"": "Um presente atrasado",
    //"": "Material Experimental",
    //"女儿的问候": "", //Greetings from my daughter?
    //"": "Na loucura",
    //"": "Catador Resmungando",
    //"": "Salvar ou não salvar",
    //"寻找记忆": "", //Searching for memories?
    //"": "Salve Meta-Humano",
    被丢弃的玩偶: "Os brinquedos da Anna",
    //"": "Encontro casual: bem-vindo a bordo",
    艺术家的钥匙: "Encontro de Cultistas - Ponto de Partida",
    信徒的宝箱: "Reunião de Cultistas – Localização do Tesouro",
    特别关系: "Um relacionamento especial",
    //"嘉莲": "",
    生日快乐: "Feliz aniversário",
    //"": "Lojinha da Bondade",
    招财猫开始点: "Gato da Sorte - Ponto de Partida",
    招财猫1号: "Gato da sorte nº 1",
    招财猫2号: "Gato da Sorte #2",
    招财猫3号: "Gato da Sorte #3",
    招财猫给予的宝箱: "Gato da Sorte - Localização do Tesouro",
    好消息坏消息: "Sobre Alegria e Tristeza - Ponto de Partida",
    神婆的宝箱: "Sobre Alegria e Tristeza - Localização do Tesouro",
    //"成就：一览众山小": "",//Achievement: A view of the world?
    农庄惊魂: "Terror na fazenda",
    限定版牛奶: "Edição Limitada",
    考古学家的馈赠: "Seja verdadeiro até a morte",
    遗留财产: "Um legado familiar",
    悲伤画像: "Retrato doloroso",
    //"罗塞塔保险箱": "", //Rosetta Safe?
    "密码：9274": "Senha: 9274", //Really a Side Quest?
    秘密配方: "Receita", //Really a Side Quest?
    // Merchant - 商人
    韦伯: "Weber",
    赵金潭: "Zhao Jintan",
    //"": "Jônatas",
    //"": "Emma Potter",
    拟态体商店: "Severin VII-S2041 (Comerciante SIRA)",
    //"": "Nisa (comerciante de couve)",
    鱼饵商人: "Margerie (comerciante de peixe)",
    "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie【Plantas de Peixe】",
    // Livable Location - 宜居地点
    // Livable Location are the recommended places to live with subjective opinions, These are usually large flat areas with rich resources and close to water sources.
    // has no individual names
    // Not sure where/if the following are used.
    异常点: "Objeto Anormal",
    稀有: "Cru",
    持续刷新: "Atualização Contínua",
    碧湖山庄: "Colina do Lago Verde",
    检测点91: "Ponto de Inspeção 91",
    戴维思角: "Ponto Davis",
    检测点24: "Ponto de Inspeção 24",
    翻车鱼岛旅客中心: "Centro de Visitantes da Ilha Mola",
    治炼厂污染点: "Plano de Poluição da Refinaria",
    检测点3711: "Ponto de Inspeção 3711",
    // 2024/08/17
    翠湖山镇: "Colina do Lago Verde",
    无蘑菇: "Sem cogumelo",
    果蔬箱土豆: "Batata",
    油田区域: "Área do campo petrolífero",
    抽水泵采集: "Bombear",
    洞穴内: "Dentro da Caverna",
    便携式燃油: "Combustível portátil",
    腐化熊: "Urso",
    水豚: "Capivara",
    狼: "Lobo",
    鳄鱼: "Crocodilo",
    长嘴海鸥: "Gaivota de bico longo",
    海龟: "Tartaruga Marinha",
    鹈鹕: "Pelicano",
    兔子: "Coelho",
    鳄龟: "Tartaruga agarradora",
    狐狸: "Raposa",
    浣熊: "Guaxinim",
    火烈鸟: "Flamingo",
    腐化鳄: "Crocodilo Corrompido",
    腐化狼: "Lobo Corrompido",
    白斑狗鱼钓鱼点: "Lúcio do Norte",
    白斑狗鱼: "Lúcio do Norte",
    海鲈鱼: "Badejo",
    神仙鱼: "Peixe-anjo",
    长吻雀鳝: "Gar Nariz Comprido",
    黑鲈: "Baixo Preto",
    孔雀鱼: "Guppy",
    鲤鱼: "Carpa",
    图丽鱼: "Astronoto Ocellatus",
    太阳鱼: "Em Lepom",
    锦鲤: "Koi",
    龙鱼: "Aruanã",
    鳙鱼: "Carpa Cabeçuda",
    沙丁鱼: "Sardinha",
    梭鱼: "Barracuda",
    鲭鱼: "Cavalinha",
    罗非鱼: "Tilápia",
    虹鳟: "Truta arco-íris",
    鲑鱼: "Salmão",
    鲳鲹: "Pompano",
    松鼠: "Esquilo",
    亚口鱼: "Otário",
    // Scenario
    "PvE-天空之触": "Manibus PvE",
    "PvP-分歧之路": "Chamada da evolução PvP",

    "PvP-逆位战争": "Confronto PvP-Prismverse", // 10/19/24
    "PvE-雪国人生": "PvE-Caminho do Inverno", // 10/19/24
    // map
    玩家: "Jogador",

    私有收容仓: "Unidade de Segurança Privada",
    出生点: "Ponto de Spawn",
    //维纳峡湾
    "观景点：雪崩巨楔": "Mirante: Monólito Avalanche",
    "观景点：菲斯库尔港": "Mirante: Porto do Peixe",
    "观景点：熊栖雪场": "Mirante: Cova do Urso",
    "观景点：母巢": "Mirante: Hiverail",
    "观景点：白崖黑域": "Mirante: Setor Negro do Penhasco Branco",
    "观景点：心愿奇境西园": "Mirante: Wish Land - Oeste",
    "观景点：荒原巨骨": "Mirante: Crânio de Wasteland",
    "观景点：冻火湾": "Mirante: Forst Forge",
    "观景点：巨岩": "Mirante: Boulder",
    "观景点：鲸骨乡": "Mirante: Osso de Baleia",
    //玛瑙冻原
    "观景点：“大河”收容场": "Mirante: Centro de Contenção TAIGA",
    "观景点：搁浅船只": "ViewPoint: navio encalhado",
    "观景点：慕斯市食品厂": "Mirante: Fábrica de Doces Mousseville",
    "观景点：冻原巨楔": "Mirante: Monólito da Tundra",
    "观景点：慕斯市": "Mirante: Mousseville",
    "观景点：心愿奇境东园": "Mirante: Wish Land Eastern Park",
    "观景点：黑石要塞": "Mirante: Forte Obsidian",
    "观景点：绚烂花海": "ViewPoint: Campos de Flores",
    "观景点：冰屋营地": "Mirante: Camp Igloo",
    //余烬滩
    "观景点：炎神实验室": "ViewPoint: Centro de Pesquisa Fire God",
    "观景点：不落号坠落点": "ViewPoint: Acidentes terrestres",
    "观景点：收容井塔乌": "ViewPoint: Silo de Segurança Taurus",
    "观景点：火喉下城": "Mirante: Fortaleza da Garganta de Fogo",
    "观景点：炽尘巨楔": "Ponto de vista: Monólito Emberdust",
    "观景点：火喉圣域": "Mirante: Santuário da Garganta de Fogo",
    "观景点：月牙湖": "Mirante: Lago Crescente",
    "观景点：灰落": "Mirante: Ashenton",
    "观景点：影日洞穴": "Mirante: Caverna Sunshroud",
    "观景点：遗忘之地": "Ponto de Vista: Esquecimento",

    //Way of Winter - 10        "荒废农庄": "",/21/24

    "空间锚点·废弃矿洞二层": "Âncora de Rift - Mina Abandonada, Piso 2",
    "收容井-德尔塔": "Silo de Segurança - Delta",
    电梯: "elevador",
    乖乖兔: "Coelhinho buscar muito",
    "食谱：黄油松茸": "Receita: Cogumelos Manteiga Matsutake",
    "食谱：硬邦邦姜糖": "Receita: GingerDrop",
    "食谱：蜜蛋弹弹乐": "Receita: Poppers de Gengibre",
    "食谱：雪茸蛋炒饭": "Receita: Arroz Frito com Cogumelo da Neve",
    "食谱：水果派": "Receita: Torta Mista de Frutas",
    "食谱：噼里啪啦南瓜汤": "Receita: Sopa de Abóbora Espumante",
    "食谱：炙热炖肉火锅": "Receita: Ensopado de Carne Farto",
    "食谱：鲜肉咖喱饭": "Receita: Curry e Arroz",
    "食谱：砰砰爆米花": "Receita: Pipoca",
    "食谱：水果蛋糕": "Receita: Bolo de Frutas",
    "食谱：炙热烈焰蛋挞": "Receita: Torta de Ovos Flamejante",
    "食谱：麻辣兔丁罐头": "Receita: Dados de Coelho Picantes Enlatados",
    "食谱：清凉薄荷肉罐头": "Receita: Carne Hortelã Enlatada",

    宝箱怪位置待定: "Localização simulada a ser determinada",
    "气球异常：轻量化红点瞄具": "Anomalia do Balão: Mira Red Dot Leve",
    "玩偶异常：戍卫前握把": "Anomalia da boneca: Punho frontal da proteção",
    "凝石异常：斜切握把": "Anomalia de condensação: aderência chanfrada",
    "凝石异常：远射补偿器": "Anomalia de Condensação: Compensador de Longo Alcance",
    "凝石异常：小型补偿器": "Anormalidade de condensação: pequeno compensador",
    "冰块宝箱：轻型光学瞄具": "Baú de Cubos de Gelo: Visão Óptica Leve",
    "冰块宝箱：手枪加长型弹匣": "Baú de Cubos de Gelo: Revista Estendida de Pistola",
    "冰块宝箱：步枪扩容弹匣": "Baú de Cubo de Gelo: Revista de Rifle Expandida",
    "凝石异常：轻型握把": "Anomalia de condensação: aderência leve",
    "冰块宝箱：冲锋枪加重型弹匣": "Baú de Cubos de Gelo: Revista Pesada de Submetralhadora",
    "凝石异常：隐秘抑制器": "Anomalia de Pedra: Supressor Furtivo",
    "冰块宝箱：轻机枪大型弹鼓": "Baú de tesouro de cubo de gelo: tambor grande de metralhadora leve",
    "凝石异常：一体式消焰器": "Anormalidade da pedra condensada: supressor de chama integrado",
    "冰块宝箱：手枪战术型弹匣": "Baú de Cubo de Gelo: Revista Tática de Pistola",
    "凝石异常：冲锋枪战术型弹匣": "Anormalidade da Pedra Condensada: Revista Tática de Submetralhadora",
    "凝石异常：奇袭制退器": "Anomalia de pedra: freio de ataque surpresa",
    "凝石异常：步枪轻量化弹匣": "Anormalidade de condensação: revista leve de rifle",
    "凝石异常：密封型反射式瞄具": "Anomalia de condensação: visão reflexa selada",
    "气球异常：消焰器": "Anomalia do balão: corta-chamas",
    "气球异常：小型制退器": "Anomalia do balão: freio de boca pequeno",
    "冰块宝箱：狙击枪战术弹匣": "Baú de Cubo de Gelo: Revista Tática de Rifle de Sniper",
    "脚印异常：精准步枪瞄具": "Pegadas anormais: mira de rifle de precisão",
    "气球异常：狙击枪改良弹匣": "Anomalia de Balão: Carregador Melhorado para Rifles de Precisão",
    "气球异常：小型红外指示器": "Anomalia de balão: pequeno indicador infravermelho",
    "气球异常：垂直握把": "Anomalia do balão: aderência vertical",
    "松鼠异常：棕熊反射式瞄具": "Anomalia do esquilo: visão reflexa do urso pardo",
    观景台: "Miradouro Cénico",
    气球异常: "anomalia do balão",
    玩偶异常: "anomalia da boneca",
    冰块宝箱: "baú de gelo",
    冷晶矿: "Minério de cristal frio",
    冰晶矿: "Minério de cristal frio",
    热岩矿: "Minério de rocha quente",
    寒冰瓜: "Melão Gelado",
    乌鸦蛋: "Ovo de corvo",
    极地椒: "Pimenta Polar",
    "极地椒 * 3": "Pimenta Polar * 3",
    驯鹿: "Rena",
    野牛: "Bisão",
    海豹: "Selo",
    母羊: "Ovelha",
    公羊: "Cabra",
    北极狐: "Raposa",
    北极熊: "Urso polar",
    熊: "Urso",

    // 2025-04-04
    预兆宝箱: "Caixas Oráculo Lunar",
    代顿检测点传送塔: "Torre de teletransporte do ponto de inspeção de Dayton",
    内海传送塔: "Torre de Teletransporte do Mar Interior",
    "金银花*8": "Madressilva*8",
    上位者的影响使星尘污染浓度上升: "Área poluída",
    这里的星尘污染浓度似乎很高: "Área poluída",
    黑湖中不断溢出星尘污染: "Área poluída",
    矿井内似乎不断溢出星尘污染: "Área poluída",
    溢出的污染不断侵蚀着这片土地: "Área poluída",
    狂信者的祝祷召唤出肆虐的污染: "Área poluída",
    源质挥发使星尘污染浓度上升: "Área poluída",
    山壁内源源不断渗出星尘污染: "Área poluída",
    鳄龟蛋: "Quebrando Ovos De Tartaruga",
    "PvE-无尽长梦": "Sonho sem fim PvE",
    无尽长梦: "Sonho sem fim",
    "PvP-禁区": "PvP-RaidZone",
    "七日世界：禁区": "OnceHuman: RaidZone",
    异常物纪元: "Era dos Desvios",
    "PvE-异常物纪元": "PvE-Era dos Desvios",
    贸易区: "Mercado de Jogadores",
    月之幽影: "Sombra da Lua",
    月兆精英怪: "Monstro de Elite do Signo Lunar",
    豹子: "Leopardo",
    龙血树: "Árvore Sangue de Dragão",
    古老者的试炼: "O Julgamento do Ancião",
    超异常体: "Superanomalia",
    星临宝箱: "Caixa Starfall",
    不稳定聚合体: "Agregado instável",
    引力异化精英怪: "Elite da Queda Estelar",
    剧情笔记: "Notas de enredo",
    金色垃圾: "Lixo Dourado",
    浅眠记录: "Escavadora",
    深眠记录: "Dorminhoco",
    永眠记录: "Dormente",
    噩梦记录: "Tubo de pesadelo",
    梦域商人: "Senhorita memória",
    梦域追迹箱: "Caixa de rastreamento da zona dos sonhos",
    清醒时钟: "Relógio acordado",
    野生装备台: "Bancada de engrenagens",
    野生工艺台: "Bancada de suprimentos",
    野生车辆: "Ruínas de veículos",
    野生商人: "Comerciante",
    矿石: "Minerais",
    植物: "Plantas",
    动物: "Animais",
    蔬菜: "Vegetais",
    草药: "Ervas",
    油田: "Campo de Petróleo",

    // "Deviation: Survive"
    非正常收容: "Desvio: Sobreviver",
    竞技场: "Arena",
    野生收容物: "Desvio Selvagem",
    斗技馆: "Academia",
    许愿者雕像: "Estátua Estranha",
    新绿竞技场: "Arena Verdejante",
    热泉竞技场: "Arena Fontes Termais",
    冬灵竞技场: "Arena Snowsprite",
    心愿竞技场: "Arena dos Desejos",
    "远归之蝶 (15级)": "Emissário da Borboleta (lv.15)",
    "远归之蝶 (22级)": "Emissário da Borboleta (lv.22)",
    "远归之蝶 (28级)": "Emissário da Borboleta (lv.28)",
    "远归之蝶 (37级)": "Emissário da Borboleta (lv.37)",
    "元素小子 (B级)": "O menino Digby (В)",
    "元素小子 (5级)": "O Garoto Digby (lv.5)",
    "元素小子 (15级)": "O Garoto Digby (lv.15)",
    "元素小子 (22级)": "O Garoto Digby (lv.22)",
    "元素小子 (25级)": "O Garoto Digby (lv.25)",
    "元素小子 (28级)": "O Garoto Digby (lv.28)",
    "元素小子 (43级)": "O Garoto Digby (lv.43)",
    "元素小子 (43级)": "O Garoto Digby (lv.43)",
    "元素小子 (45级)": "O Garoto Digby (lv.45)",
    "夺命兔 (B)": "Coelho Letal (B)",
    "夺命兔 (15级)": "Coelho Letal (lv.15)",
    "夺命兔 (40级)": "Coelho Letal (lv.40)",
    "夺命兔 (45级)": "Coelho Letal (lv.45)",
    "乖乖兔 (B)": "Coelhinho Fetch-A-Lot (B)",
    "永恒烈阳 (A)": "Sol Invencível (А)",
    "派对猴 (B)": "Macaco festeiro (B)",
    "庞然大菇 (5级)": "Cogumelo de crescimento (lv.5)",
    "庞然大菇 (22级)": "Cogumelo de crescimento (lv.22)",
    "庞然大菇(22级)": "Cogumelo de crescimento (lv.22)",
    "庞然大菇 (40级)": "Cogumelo de crescimento (lv.40)",
    "庞然大菇 (43级)": "Cogumelo de crescimento (lv.43)",
    "庞然大菇 (45级)": "Cogumelo de crescimento (lv.45)",
    "量子蜗牛 (5级)": "Caracol Atômico (lv.5)",
    "量子蜗牛 (15级)": "Caracol Atômico (lv.15)",
    "量子蜗牛 (22级)": "Caracol Atômico (lv.22)",
    "量子蜗牛 (28级)": "Caracol Atômico (lv.28)",
    "量子蜗牛 (35级)": "Caracol Atômico (lv.35)",
    "低语孤狼 (5级)": "Sussurro do Lobo Solitário (lv.5)",
    "低语孤狼 (15级)": "Sussurro do Lobo Solitário (lv.15)",
    "低语孤狼 (22级)": "Sussurro do Lobo Solitário (lv.22)",
    "低语孤狼 (28级)": "Sussurro do Lobo Solitário (lv.28)",
    "蜂团团 (5级)": "Abelha Buzzy (lv.5)",
    "蜂团团 (22级)": "Abelha Buzzy (lv.22)",
    "蜂团团 (43级)": "Abelha Buzzy (lv.43)",
    "蜂团团 (45级)": "Abelha Buzzy (lv.45)",
    "永恒烈阳 (27级)": "Sol Invencível (lv.27)",
    "迪斯科球  (27级)": "Bola de discoteca (lv.27)",
    "迪斯科球(27级)": "Bola de discoteca (lv.27)",
    "迪斯科球 (B)": "Bola de discoteca (B)",
    "电鳗  (27级)": "Enguia Elétrica (lv.27)",
    "电鳗 (B)": "Enguia Elétrica (B)",
    "活性凝胶 (B)": "Gel Purulento (B)",
    "活性凝胶 (25级)": "Gel Purulento (lv.25)",
    "小纸人 (B)": "Boneca de Papel (B)",
    "核子打火机 (A)": "Isqueiro Atômico (A)",
    "捕梦网 (B)": "Apanhador de Sonhos (B)",
    "熊医生 (A)": "Dr.",
    "工号37 (A)": "H37 (A)",
    "雨人 (15级)": "Homem da Chuva (lv.15)",
    "雨人 (28级)": "Homem da Chuva (lv.28)",
    "雨人 (37级)": "Homem da Chuva (lv.37)",
    "雨人 (40级)": "Homem da Chuva (lv.40)",
    "雨人 (45级)": "Homem da Chuva (lv.45)",
    "气球狗 (A)": "Amigo Filhote (A)",
    "发条青蛙 (5级)": "Sapo, o Saltador (lv.5)",
    "发条青蛙 (22级)": "Sapo, o Saltador (lv.22)",
    "发条青蛙 (28级)": "Sapo, o Saltador (lv.28)",
    "发条青蛙 (43级)": "Sapo, o Saltador (lv.43)",
    "恶咒娃娃 (A)": "Boneca Vodu (A)",
    "破碎少女 (B)": "Donzela Despedaçada (B)",
    "空间魔方 (A)": "Vira Espaço (A)",
    "联合体 (B)": "Pirâmide Maçônica (B)",
    "木工河狸 (B)": "Castor madeireiro (В)",
    "木工河狸 (15级)": "Castor madeireiro (lv.15)",
    "木工河狸 (22级)": "Castor madeireiro (lv.22)",
    "木工河狸 (28级)": "Castor madeireiro (lv.28)",
    "木工河狸 (45级)": "Castor madeireiro (lv.45)",
    "庞然大菇 (28级)": "Cogumelo de crescimento (lv.28)",
    "炎之精 (22级)": "Essência da Chama (lv.22)",
    "炎之精 (25级)": "Essência da Chama (lv.25)",
    "炎之精 (28级)": "Essência da Chama (lv.28)",
    "空之子 (22级)": "Pelo Vento (lv.22)",
    "空之子 (43级)": "Pelo Vento (lv.43)",
    "极寒水母 (22级)": "Geléia Polar (lv.22)",
    "极寒水母 (37级)": "Geléia Polar (lv.37)",
    "极寒水母 (40级)": "Geléia Polar (lv.40)",
    "极寒水母 (43级)": "Geléia Polar (lv.43)",
    "极寒水母 (45级)": "Geléia Polar (lv.45)",
    "胡桃夹子 (A)": "Quebra-nozes (А)",
    "雪景球 (B)": "Globo de Neve (B)",
    "雪景球 (35级)": "Globo de Neve (lv.35)",
    "姜饼屋 (A)": "Casa de Pão de Gengibre (А)",
    "快照 (A)": "ZapCam (А)",
    "冰之瓶 (B)": "Pote de gelo (В)",
    "门扉 (S)": "Porta Estranha (S)",
    "鱼航员 (43级)": "Peixe Hidronauta (lv.43)",
    "鱼航员 (45级)": "Peixe Hidronauta (lv.45)",
    "鲸狗 (5级)": "Filhote de baleia (lv.5)",
    "鲸狗 (22级)": "Filhote de baleia (lv.22)",
    "鲸狗 (28级)": "Filhote de baleia (lv.28)",
    "狐主任 (15级)": "Diretor Fox (lv.15)",
    "狐主任 (22级)": "Diretor Fox (lv.22)",
    "狐主任 (28级)": "Diretor Fox (lv.28)",
    "狐主任 (37级)": "Diretor Fox (lv.37)",
    "狐主任 (45级)": "Diretor Fox (lv.45)",
    "焦油布丁 (22级)": "Pudim de Alcatrão (lv.22)",
    "唤生灵 (37级)": "Invocador de Almas (lv.37)",
    三角原传送塔: "Torre de Teletransporte",
    油田北部传送塔: "Torre de Teletransporte",
    秽水工业区: "Zona Industrial de Águas Cinzentas",

    // 乐园岛
    乐园岛: "Ilha Paraíso",
    金宝箱: "Caixa de saque de ouro",
    银宝箱: "Caixas de saque de prata",

    //DOLLA
    污染区: "Zonas Contaminadas",
    幻境地带: "Zona Espelhada",
    蛮荒地带: "Zona Selvagem",
    虚实地带: "Zona Reino Virtual",
    金属抽屉柜: "Cômoda  de Metal",
    垃圾箱: "Lixeira",
    车后备箱: "Porta Mala de Carro",
    囤积者巢穴: "Covil de Acumuladores",
    文明遗产: "Herança da Civilização",
    畸变宝箱: "Sementes de Origem Mutante",
    恶咒娃娃: "Boneca Voodoo",
    鼠尾草: "Sálvia",
    香蕉: "Banana"
  },
};