export default {
    "buttons": {
        "filter": "Фильтр",
        "select_all": "Показать все",
        "deselect_all": "Скрыть все",
        "close": "Закрыть",
        "move_left": "Сдвинуть влево",
        "move_right": "Сдвинуть вправо"
    },
    "tabs": {
        "by_category": "Категория",
        "by_item": "Предмет",
        "by_search": "Поиск",
        "resource_list": "Ресурсы",
        "setting": "Настройки",
        "user_data": "Данные пользователя",
        "quick_setting": "Быстрые настройки",
        "quick_setting_fuel_loot": "Добыча топлива",
        "quick_setting_resource": "Ресурсы",
        "quick_setting_bus_route": "Автобус монстр",
        "quick_setting_show_players": "Show Players",
        "quick_setting_pollution": "Pollution",
        "quick_setting_popup_coordinate": "Coordinate Follow Pointer",
        "area": "Области",
        "treasure": "Сокровища",
        "monster": "Исследовать",
        "collection": "Коллекция",
        "hint": "Подсказка",
        "logged": "Данные",
        "guest": "Логин",
        "oneclick_delete_enable": "Удаление щелчком",
        "oneclick_delete_disable": "Выключен",
        "oneclick_delete_badge": "В ОднинКлик моде",
        "oneclick_delete_hint1": "После включения этой функции щелчок по маркеру больше не будет отображать всплывающее окно, а приведет к непосредственному удалению или отмене маркера.",
        "oneclick_delete_enable_hint": "Режим удаления одним щелчком мыши включен",
        "oneclick_delete_disable_hint": "Режим удаления одним щелчком мыши отключен",
        "oneclick_delete_dialog_title": "Внимание",
        "oneclick_delete_dialog_content": "После включения режима удаления одним щелчком мыши при нажатии на маркер на карте не будет появляться всплывающее окно. Вместо этого маркер будет удаляться или отменяться напрямую. Хотите продолжить включение?",
        "oneclick_delete_dialog_close": "Закрыть",
        "oneclick_delete_dialog_confirm": "Подтверите",
        "batch_editing_enable": "Пргресс",
        "batch_editing_disable": "Выход",
        "batch_editing_hint": "Вы можете пакетно удалять или отменять удаление всех маркеров одной категории. Чтобы воспользоваться этой функцией, необходимо войти в систему.",
        "setting_btn_hint": "Настройки, относящиеся к карте",
        "login_btn_hint": "Управление данными",
        "back_to_categories": "Назад к категориям",
        "display_area": "Фильтр зон",
        "select_item_category": "Выбрать",
        "related_items": "Связанные предметы",
        "locate_item": "Нажмите на элемент чтобы найти его",
        "search_resources": "Поиск ресурсов",
        "input_resource_name": "Введите имя",
        "locate": "Локация",
        // Miscellaneous UI strings
        "any_name": "Поддерживается только на Китайском",
        "locations": "Локации",
        "locate_point": "Нажмите, чтобы отцентрировать местоположение",
        "input_item": "Пожалуйста, введите название местоположения",
        "related_item": "Товары",
        "related_makers": "Маркеры",
        "locate_marker": "Нажмите, чтобы отцентрировать маркер",
        "input_marker": "Пожалуйста, введите имя маркера",
        "related_resources": "Ресурсы",
        "locate_resource": "Нажмите, чтобы отцентрировать ресурсы",
        "input_resource_for_searching": "Пожалуйста, введите имя ресурса",
        "follow_xingchuan": "Подпишитесь на Xingchuan",
        "bilibili": "BiliBili",
        "tiktok": "TikTok",
        "ad": "AD",
        "ad2": "AD",
        "jd": "Реклама недоступна в Русской версии",
        "daigan": "Реклама недоступна в Русской версии",
        "login_warring": "Пожалуйста, сначала получите текст от бота сервера Discord.",
        "delete_all": "Удалить все",
        "resume_all": "Восстановить",
        "exit_management_mode": "Выход",
        "select_scenario": "Scenario"
    },
    "floor_text": {
        "roof": "( Крыша )",
        "at_floor": "( Пол {floor} )",
        "underground": "( Этаж {floor} Подземный )",
        "level": "( Lv. {уровень} )"
    },
    "settings": {
        "has_video": "Видеомаркер",
        "deleted_marker": "Удаленный маркер",
        "map_area_style": "Стиль зоны",
        "monster_bus_route": "Маршрут монстра автобуса",
        "marker_text": "Текст маркера",
        "resource_area": "Область ресурсов",
        "last_updated_datetime": "Время обновления маркера",
        "icon_drawing_method": "Метод рисования иконок (рекомендуется использовать холст, если иконка сломана)",
        "dark_mode": "Тёмный режим",
        "language": "Язык",
        "auto_query": "Запрос о смене категорий",
        "auto_draw_marker_after_search": "Отображение результатов поиска на карте",
        "show": "Показать",
        "hide": "Скрыть",
        "line_style": "Стиль линии",
        "area_style": "Стиль заполнения",
        "wasm": "Wasm (Лучшее представление)",
        "canvas": "Холст (Лучшая совместимость)",
        "on": "Вкл",
        "off": "Выкл",
        "draw_text_mode": "Стиль текста маркера",
        "draw_text_mode_1": "Успешно",
        "draw_text_mode_2": "Упрощенный",
        "deleted_marker_style": "Удалить стиль маркера",
        "deleted_marker_style_1": "Крест",
        "deleted_marker_style_2": "Полупрозрачный",
        "deleted_marker_style_3": "Скрыть",
    },
    "user_data": {
        "local_storage": "Местные данные",
        "count": "нет записей | {count} записей | {count} записей",
        "local_storage_tutorial": "Учебное пособие",
        "backup": "Резервное копирование & восстановление",
        "local_storage_text": "Вы можете удалить любой маркер, не входя в систему. Но данные будут храниться только в текущем браузере. Вы можете создать резервную копию данных и перенести их в другой браузер.",
        "backup_placeholder": "Дата",
        "backup_button": "Резервное копирование",
        "restore_button": "Восстановить",
        "cloud_storage": "Облачные данные",
        "clear_all_data": "Удалить все данные",
        "restore_hint": "Совет: При выполнении этой операции локальные данные будут объединены с импортированными. Если вы вошли в систему, данные также будут синхронизированы с облаком. Вы хотите продолжить?",
        "delete_hint": "Вы уверены, что хотите удалить все данные? Если вы уже вошли в систему, облачные данные также будут удалены. Вы хотите продолжить?",
        "wechat_login": "Wechat",
        "wechat_mp_login": "Wechat2",
        "discord_login": "Discord",
        "login_tutorial": "Учебное пособие",
        "login_tutorial_text": "После входа в систему локальные и облачные данные будут автоматически синхронизированы, и вы сможете продолжать использовать ее в любом браузере и на любом устройстве. Вы также можете использовать его в обычном режиме, не входя в систему, но данные будут храниться только в локальном браузере.",
        "not_login": "Не вошел в систему",
        "login_success": "Вы успешно вошли в систему",
        "data_is_syncing": "Данные синхронизируются",
        "last_syncing_time": "Время последней синхронизации: ",
        "logout": "Выйти из системы",
    },
    "marker_dialog": {
        "no_marker_img": "Нет картинки",
        "delete_markder": "Удалить маркер",
        "undelete": "Отменить удаление",
        "delete_only": "Только удалить",
        "hide_category": "Скрыть {категорию}",
        "no_update_time": "Время обновления не указано",
        "rewards": "Награды",
        "close": "Закрыть",
        "detail": "Детали",
        "operation": "Операция",
        "timer_title": "Сброс таймера",
        "timer_title_not_login": "(Необходимо войти) Сброс таймера",
        "deviant_timer_title": "Таймер сброса девиантов",
        "to_login": "Войти в систему для разблокировки функции таймера",
        "comment": "Комментарии",
        "auto_set_timer": "Автоматическая установка таймера",
        "auto_set_timer_not_login": "(Необходимо войти) Таймер автоматической установки",
        "timer_tutorial": "Самоучитель по таймеру",
        "sharing": "Поделиться",
        "session_script": "В настоящее время доступен в: ",
        "hint": "[ Подсказка ]",
        "sharing_hint": "Общая ссылка будет автоматически отображать маркер при открытии.",
        "download_qr_code": "Скачать",
        "sharing_link": "Ссылка",
        "copy": "Скопировать",
        "update": "Обновленный",
        "guide": "Путеводитель",
        "donate": "Поддержка",
        "auto_reset_help_title": "Помощь",
        "auto_reset_help_text": "Ящики с оружием обновляются в 00:00:00 и так каждые 4 часа. Если вы все еще не можете открыть ящики по истечении времени обновления, просто войдите в игру снова.",
        "auto_reset_help_ok": "OK",
        "click_to_copy": "Нажмите для копирования",
        "copied_successfully": "Скопировано",
        "common_hint": "Советы"
    },
    "donate": {
        "payment": "Пожалуйста сканироуйте QR code",
        "text": "Ваша поддержка поможет сайту продолжать работу и обновлять новые функции",
        "warning": "Несовершеннолетним запрещено донатить"
    },
    "scenario": {
        "not_available": "Not Available",
        "current": "Current",
        "available": "Available",
        "coming": "Coming",
        "scenarios": "Scenarios"
    },
    "categories": {
        // Areas
        "传送塔": "Телепорт",
        "巨楔": "Монолит",
        "主城": "Поселение",
        "研究所": "Лаборатрия",
        "大型资源点": "Башня",
        "小型资源点": "Деревня",
        "收容井": "Securement Silo",
        "位面锚": "Rift Anchor",
        "空间锚点": "Rift Anchor",
        // Treasures
        "神秘宝藏": "Мистический сундук",
        "神秘宝箱": "Мистический сундук",
        "武器箱": "Оружейный сундук",
        "装备箱": "Сундук снаряжения",
        "隐藏宝箱": "Скрытый сундук",
        "秘藏宝箱": "Скрытый сундук",
        "宝箱怪": "Живые сундуки",
        "储物箱": "Простые сундуки",
        // Explore
        "精英怪": "Элитный",
        "迷雾区域": "Туманное событие",
        "防守工坊": "Мастерская",
        "移动房屋": "Дом на руках",
        "限时事件": "Красное событие",
        // Collection
        "武器配件": "Дополнение", // "Weapon Attachments" is too long and breaks the UI
        "食谱": "Рецепт",
        "收容物": "Девиант",
        "诡谲画作": "Таинственная картина",
        "矿物点": "Минерал",
        "采集点": "Материал",
        "种子箱": "Сундук с семенами",
        "调味料箱": "Сундук для специй",
        "种子香料": "Семена и специи",
        "饮料机": "Питьевой автомат",
        "随机素材箱": "Случайный сундук",
        "抗菌剂箱": "Медицинский сундук",
        // PvP
        "回响石": "Камень Эхо",
        // Hint
        "留言": "Подсказка",
        "隐藏任务": "Побочный квест",
        "支线任务": "Побочный квест",
        "商人": "Торговец",
        "宜居地点": "Удобное расположение",
        // Regions
        "代顿湿地": "Dayton Wetlands",
        "破碎三角洲": "Broken Delta",
        "垩峰山": "Chalk Peak",
        "铁锈河": "Iron River",
        "孤狼荒原": "Red Sands",
        "黑心地带": "Blackheart",
        // Routes
        // No need to translate the fuel count number.
        "怪物巴士路线": "Автобус монстр",
        "便携混合燃油": "Портативное топливо",
        // Areas
        "污染区": "Загрязненная территория",
        // Teleporters - 传送塔
        "猎犬岛传送塔": "Телепортационная башня",
        "望岛镇传送塔": "Телепортационная башня",
        "离岸广场传送塔": "Телепортационная башня",
        "临溪东部传送塔": "Телепортационная башня",
        "贪欲巨楔传送塔": "Monolith of Greed телепортационная башня",
        "代顿检查点传送塔": "Телепортационная башня",
        "高岸南部传送塔": "Телепортационная башня",
        "西格玛传送塔": "Телепортационная башня",
        "暖阳中部传送塔": "Телепортационная башня",
        "三角洲南部传送塔": "Телепортационная башня",
        "盖亚山区传送塔": "Телепортационная башня",
        "盖亚巨楔传送塔": "Gaia Cliff Monolith телепортационная башня",
        "代顿北部传送塔": "Телепортационная башня",
        "高地西部传送塔": "Телепортационная башня",
        "盖亚西部传送塔": "Телепортационная башня",
        "朽鞍镇传送塔": "Телепортационная башня",
        "银滩北部传送塔": "Телепортационная башня",
        "翠湖南部传送塔": "Телепортационная башня",
        "翠湖北部传送塔": "Телепортационная башня",
        "阿尔法传送塔": "Телепортационная башня",
        "月湖传送塔": "Телепортационная башня",
        "庄园东部传送塔": "Телепортационная башня",
        "尖牙巨楔传送塔": "Monolith of Thirst телепортационная башня",
        "蜿蜒山区传送塔": "Телепортационная башня",
        "波光北部传送塔": "Телепортационная башня",
        "黯梦巨楔传送塔": "Mirage Monolith телепортационная башня",
        "风角边境传送塔": "Телепортационная башня",
        "谷地南部传送塔": "Телепортационная башня",
        "西塔传送塔": "Телепортационная башня",
        "黑原中部传送塔": "Телепортационная башня",
        "遗忘巨楔传送塔": "Forsaken Monolith телепортационная башня",
        "悬巢北部传送塔": "Телепортационная башня",
        "悬巢南部传送塔": "Телепортационная башня",
        "内部传送塔": "Телепортационная башня",
        "巨人阶梯传送塔": "Телепортационная башня",
        "黑心内弯传送塔": "Blackheart's Bay телепортационная башня",
        // Monoliths - 巨楔
        "贪欲巨楔": "Monolith of Greed",
        "盖亚巨楔": "Gaia Cliff Monolith",
        "黯梦巨楔": "Mirage Monolith",
        "尖牙巨楔": "Monolith of Thirst",
        "遗忘巨楔": "Forsaken Monolith",
        // Settlements - 主城
        "旅人营地": "Deadsville",
        "迈尔集市": "Meyer's Market",
        "秽水营地": "Greywater Camp",
        "深草旅店": "Tall Grass Inn",
        "黑原镇": "Blackfell",
        // Labs - 研究所
        "生命进化研究所": "HP Evolution Institute",
        // Towns - 大型资源点
        "中途镇": "Throughville",
        "腐烂庄园": "Rotten Manor",
        "橘子镇": "Citrus County",
        "望岛镇": "Overlook Town",
        "苏德兰果园": "Sutherland Family Orchard",
        "离岸广场": "Coastside Plaza",
        "临溪": "Brookham",
        "代顿医院": "Dayton Hospital",
        "贪欲巨楔警戒区": "Monolith of Greed Danger Zone",
        "赫斯特工业": "Hearst Industries",
        "海港镇": "Harborside",
        "猎犬岛哨站": "Wild Dog Isle Outpost",
        "暖阳中学": "Sunbury Middle School",
        "暖阳镇": "Sunbury",
        "苏德兰化工厂": "Sutherland Chemical Plant",
        "高岸镇": "High Banks",
        "废弃货场": "Junkyard",
        "盖亚研究所遗址": "Gaia Research Center Ruins",
        "东部铁路枢纽": "Eastern Railway Junction",
        "盖亚巨楔警戒区": "Gaia Cliff Monolith Danger Zone",
        "高地": "Highland",
        "冶炼厂污染点": "Refinery Pollution Plant",
        "秽水工业区": "Greywater Industrial Zone",
        "阿卡尔克镇": "Alkirk",
        "东黑原枢纽": "East Blackfell Junction",
        "波光镇": "Rippleby",
        "里奇收容点": "Ricci Securement Point",
        "黯梦巨楔警戒区": "Mirage Monolith Danger Zone",
        "盖亚军事基地": "Gaia Military Base",
        "朽鞍镇": "Rotten Saddle",
        "银滩度假区": "Silvershore Resort",
        "碧湖山镇": "Greenlake Hill",
        "霍特镇": "Holt Town",
        "熔炉巢穴": "Furnace Lair",
        "常青藤酒庄": "Evergreen Vineyard",
        "阿尔法研究所": "Alpha Institute",
        "尖牙巨楔警戒区": "Monolith of Thirst Danger Zone",
        "交错现实研究所": "Alternative Reality Research Institute",
        "黑原油田": "Blackfell Oil Fields",
        "黑原陷落区": "Blackfell Fallen Zone",
        "绿荫镇": "Evergreen",
        "悬巢": "Fort Eyrie",
        "73号源质分离点": "73 Source Extraction Point",
        "太阳农场": "Sunshine Farm",
        "白崖基地": "White Cliff",
        // Villages
        "中途镇变电站": "Throughville Substation",
        "检测点3771": "Inspection Point 3771",
        "翻车鱼岛游客中心": "Mola Island Visitor Center",
        "海岬庄园": "Cape Manor",
        "小码头": "Petit Harbor",
        "艾尔汽修店": "Aiden's Auto Repair",
        "艾尔的隐蔽所": "Aiden's Hideout",
        "检测点7802": "Inspection Point 7802",
        "临溪警戒所": "Brookham Guardhouse",
        "代顿货栈": "Dayton Warehouse",
        "崖下营地": "Cliffside Camp",
        "北岸营地": "North Shore Camp",
        "赫斯特": "Hearst",
        "赫斯特滩涂": "Hearst Mudflats",
        "湖心野营地": "Lakeheart Camp",
        "迈尔": "Meyer",
        "高岸巢穴": "Highbank Nest",
        "废弃隐蔽所": "Abandoned Hideout",
        "骑士修车店": "Knight Vehicle Repairs",
        "山脊中转站": "Ridge Transfer Station",
        "山脊营地": "Ridge Camp",
        "暖阳农庄": "Sunbury Farm",
        "瀑布广场": "Waterfall Plaza",
        "沉船坟场": "Ship Graveyard",
        "沉没宅院": "Sunken House",
        "检测点024": "Inspection Point 024",
        "检测点9043": "Inspection Point 9043",
        "TAB-6A营地": "Tab-6A Camp",
        "高地居住区": "Highland Residential Zone",
        "洗劫一空的营地": "Ransacked Camp",
        "远眺伐木场": "Overlook Lumberyard",
        "污染检测点77": "Pollution Inspection Point 77",
        "河心码头": "Riverhart Harbor",
        "河畔纪念品店": "Riverside Souvenirs",
        "枯竭油井": "Depleted Oil Well",
        "蜿蜒山种植园": "Winding Ridge Farmland",
        "浅滩公园": "Shoal Park",
        "波光镇集市": "Rippleby Market",
        "风车阵列": "Wind Farm",
        "秘港": "Secret Harbor",
        "检测点023": "Inspection Point 023",
        "克里夫顿": "Clifton",
        "海风疗养地": "Breezy Shores Resort",
        "诺顿农场": "Norton Farm",
        "高岸检测点": "Highbank Inspection Point",
        "私酿庄园": "Brewery Estate",
        "老大的乐园": "The Boss's Playground",
        "霍特电站": "Holt Power Station",
        "帕斯利广场": "Paisley Plaza",
        "山麓别墅": "Hilly Homestead",
        "盖亚通讯阵列": "Gaia Communication Array",
        "检测点266": "Inspection Point 266",
        "狂热信徒聚落": "Believer Colony",
        "戴维斯角": "Davis Point",
        "鞍前营地": "Saddlefront Camp",
        "渔人码头": "Fisherman Wharf",
        "格尔峰电站": "Mount Guel Power",
        "检测点091": "Inspection Point 091",
        "妮娜奶奶的水果餐吧": "Grandma Nina's Diner",
        "检测点384": "Inspection Point 384",
        "矿镇": "Mining Town",
        "翠湖游客中心": "Greenlake Visitor Center",
        // Securement Silos - 收容井
        "收容井-西格玛": "Securement Silo - Sigma",
        "收容井-斐": "Securement Silo - Phi",
        "收容井-暗狱": "Securement Silo EX1",
        "收容井-阿尔法": "Securement Silo - Alpha",
        "收容井-寒境": "Securement Silo - Psi",
        "收容井-西塔": "Securement Silo - Theta",
        // Rift Anchors - 位面锚
            // has no individual names yet in chinese
        // Mysterious Chests - 神秘宝藏
            // has no individual names
        // Weapon Crates - 武器箱
            // has no individual names
        "武器箱【剧情箱子】": "Weapon Crate【Story】",
        // Gear Crates - 装备箱
            // has no individual names
        // Hidden Crates - 隐藏宝箱
            // has no individual names
        // Morphic Crates - 宝箱怪
            // has no individual names
        // Storage Crates - 储物箱
            // has no individual names
        // Elites - 精英怪
        "暴食狂": "Glutton",
        "屠夫": "Arbiter",
        "裁决者": "Arbiter",
        "星尘簇": "Star Walker",
        "门徒": "Disciple",
        "雨壳": "Rainfall Reaper",
        "腐坏眼虫": "Claw Machine", // Chagas Weevil
        "娃娃机": "Claw Machine", // Chagas Weevil
        "抓娃娃机": "Claw Machine", // Chagas Weevil
        "唤生之母": "Mother of Life",
        "唤生水母": "Mother of Life",
        "熔烛": "Molton Candle",
        "乐园向导": "Balloon Boy",
        "夜魇": "Cervitaur",
        "天气预报": "Weather Forecast",
        "罪人守望": "Sinner Sentry", 
        //"”教练“ 【清剿目标】": "", //removed?
        //'"龙脊" 科利·兰根': "", //removed?
        "罗塞塔防暴员": "Rosetta Bruiser",
        "罗塞塔机械师": "Rosetta Mechanic",
        "罗塞塔重装员": "Rosetta Heavy",
        // Fog Events - 迷雾区域
            // has no individual names
        // Workshops - 防守工坊
            // has no individual names
        // Moving Houses - 移动房屋
            // has no individual names
        // Red Events - 限时事件
        "这里没有迪斯科": "Where Does Disco Go?",
        "湖之暗面": "The Dark Side",
        //"": "Cargo Scramble"
        "挖通地狱": "Dig to Hell",
        "腐乐园": "Paradise Lost",
        "喀戎行动": "Operation Chiron",
        // Accessories - 武器配件
        // Weapon Attachments - 武器配件
        // Optics - 瞄具配件
        "轻量化红点瞄具": "Light Reflex Sight",
        "战斗侦查瞄具": "Recon Combat Optic",
        "反射式瞄具": "Reflex Sight",
        "精准步枪瞄具": "Precision Rifle Scope",
        "战术全像瞄准镜": "Tactical Holographic Sight",
        "精准光学瞄具": "Precision Optic",
        "战术步枪瞄具": "Tactical Rifle Scope",
        "轻型光学瞄具": "Light Optic",
        "中距离战术瞄具": "Mid-Range Optic",
        "密封型反射式瞄具": "Sealed Reflex Sight",
        "紧凑型反射式瞄具": "Compact Reflex Sight",
        "棱镜式瞄具": "Prismatic Sight",
        "远距离战术瞄具": "Long-Range Tactical Sight",
        "大型光学瞄具": "Large Optic Sight",
        "紧固型微型红点瞄具": "Fastened Mini Reflex Sight",
        "微型红点瞄具": "Mini Reflex Sight",
        "先进战斗光学瞄具": "Advanced Combat Optic",
        "全像瞄准镜": "Holographic Sight",
        // Muzzle Attachments - 枪口配件
        "鱼鹰抑制器": "Osprey Suppressor",
        "集成型补偿器": "Integrated Compensator",
        "多用途霰弹枪抑制器": "Multi-Use Shotgun Suppressor",
        "锤头型补偿器": "Hammer Compensator",
        "短型抑制器": "Short Suppressor",
        "战术消焰器": "Tactical Flash Hider",
        "小型补偿器": "Small Compensator",
        "加长型制退器": "Extended Brake",
        "一体式抑制器": "Integrated Suppressor",
        "小型制退器": "Small Muzzle Brake",
        "一体式消焰器": "Integrated Flash Hider",
        //"多孔式消焰器": "", // Multi-Hole Flash Hider
        "伪装用抑制器": "Camouflage Suppressor",
        "大型抑制器": "Large Suppressor",
        "大型枪口制退器": "Large Brake",
        "前向消焰器": "Forward Flash Hider",
        "消焰器": "Flash Hider",
        "轻量化制退器": "Light Brake",
        "基础抑制器": "Basic Suppressor",
        "紧凑型制退器": "Compact Brake",
        "霰弹枪制退器": "Shotgun Brake",
        // Tactial Attachments - 战术配件
        "小型红外指示器": "Mini Reflex Sight, Small Infrared",
        "前护手握把": "Front Guard Grip",
        "后护手握把": "Back Guard Grip",
        "大型激光指示器": "Large Laser Sight",
        "集成型激光指示器": "Integrated Laser Sight",
        "角型握把": "Triangle Grip",
        "战术激光指示器": "Tactical Laser Sight",
        "小型激光指示器": "Small Laser Sight",
        "轻质前握把": "Light Front Grip",
        "轻质水平握把": "Light Horizontal Grip",
        "战术手电筒": "Tactical Flashlight",
        "红外指示器": "Infrared Indicator",
        "紧凑型红外指示器": "Compact Infrared Indicator",
        "战术组合握把": "Tactical Combine Grip",
        "眼镜蛇握把": "Cobra Grip",
        "垂直握把": "Vertical Grip",
        "紧凑型手电筒": "Compact Flashlight",
        "激光指示器": "Laser Sight",
        "折叠脚架": "Folding Bipod",
        // Magazines - 弹匣配件
        "狙击枪战术弹匣": "Tactical SR магазин",
        "轻机枪校准弹鼓": "Calibrated LMG Drum Магазин",
        "狙击枪改良弹匣": "Amended SR Магазин",
        "步枪轻量化弹匣": "Light Rifle Магазин",
        "冲锋枪加重型弹匣": "Weighted SMG Магазин",
        "轻机枪大型弹鼓": "Large LMG Drum Магазин",
        "手枪战术型弹匣": "Tactical Pistol Магазин",
        "冲锋枪战术型弹匣": "Tactical SMG Магазин",
        "步枪扩容弹匣": "Extended Rifle Магазин",
        "手枪加长型弹匣": "Extended Pistol Магазин",
        "手枪改良弹匣": "Amended Pistol Магазин",
        "冲锋枪改良弹匣": "Amended SMG Магазин",
        "步枪改良弹匣": "Amended Rifle Магазин",
        // Puzzle Types
        "异常门扉": "Door Puzzle",
        "异常路牌": "Broken Billboard",
        "广告牌异常": "Broken Billboard",
        "破碎山石异常": "Breakable Rock",
        "异常电话亭": "Phone Booth",
        "异常雕像": "Statue Puzzle",
        "黑水相机": "Camera Emote",
        //"": "Compact Brake (нужно Таинственная картина)",
        "诡谲画作: 小型制退器": "Small Muzzle Brake (нужно Таинственная картина)",
        "诡谲画作: 轻型光学瞄具": "Light Optic (нужно Таинственная картина)",
        "诡谲画作: 小型激光指示器": "Small Laser Sight (нужно Таинственная картина)",
        "诡谲画作: 战术步枪瞄具": "Tacticle Rifle Scope (нужно Таинственная картина)",
        "诡谲画作: 前向消焰器": "Forward Flash Hider (нужно Таинственная картина)",
        // Attachment Dupes with Spelling differences
        "战斗侦察瞄具": "Recon Combat Optic",
        "眼镜蛇握把": "Cobra Grip",
        "反射式瞄具·黑色": "Reflex Sight",
        "角形握把": "Triangle Grip",
        "霰弹枪式制动器": "Shotgun Brake",
        "密封型反射瞄具": "Sealed Reflex Sight",
        "多用途霰弹枪抑制器(6226,-588)": "Multi-Use Shotgun Suppressor (6226,-588)", // Сохраняйте координаты, если они доступны
        "大型光学瞄具,黑心地带(3039,990)": "Large Optic Sight (3039,990)",
        "大型光学瞄具,黑心地带(3037,-979)": "Large Optic Sight (3037,-979)",
        "手枪加强型弹匣": "Extended Pistol Магазин",
        "诡谲画作：小型制退器": "Small Muzzle Brake (нужно Таинственная картина)",
        "诡谲画作：轻型光学瞄具": "Light Optic (нужно Таинственная картина)",
        "诡谲画作：小型激光指示器": "Small Laser Sight (нужно Таинственная картина)",
        "诡谲画作：战术步枪瞄具": "Tacticle Rifle Scope (нужно Таинственная картина)",
        "诡谲画作：前向消焰器": "Forward Flash Hider (нужно Таинственная картина)",
        "诡谲画作:战术步枪瞄具": "Tacticle Rifle Scope (нужно Таинственная картина)",
        // Item Categories - 手枪
        "手枪": "Пистолеты",
        "霰弹枪": "Дробовики",
        "冲锋枪": "SMGs", // Submachine Guns
        "步枪": "Винтовки",
        "狙击枪": "Снайперские винтовки",
        "轻机枪": "LMGs", // Light Machine Guns
        "弓弩": "Арбалеты",
        "重型火器": "Тяжелое оружие",
        "刀剑": "Оружие ближнего боя",
        "头盔": "Шлемы",
        "面部": "Маски", // Лицо
        "上身": "Жилеты", // Top
        "下身": "Штаны", // Bottom
        "手套": "Перчатки",
        "鞋子": "Обувь",
        "瞄具配件": "Оптика",
        "枪口配件": "Насадки на дуло",
        "战术配件": "Тактические приспособления",
        "弹匣配件": "Магазины",
        "碎弹模组": "Моды на шрапнель",
        "霜寒模组": "Моды Frost Vortex",
        "爆弹模组": "Unstable Bomber Моды",
        "电涌模组": "Power Surge Моды",
        "标记模组": "The Bull's Eye Моды",
        "弹射模组": "Bounce Моды",
        "快枪手模组": "Fast Gunner Моды",
        "灼烧模组": "Burn Моды",
        "阵地模组": "Моды для Fortress Warfare",
        "武器通用": "Weapon Compatible", // ?
        "头盔模组": "Модификации для шлемов",
        "面部模组": "Моды для масок", // Face mods
        "上身模组": "Модификации для жилетов", // Top mods
        "下身模组": "Моды для штанов", // Bottom Mods
        "手套模组": "Моды для перчаток",
        "鞋子模组": "Моды для обуви",
        "防具通用": "Совместимость с броней", // ?
        "近战通用": "Melee General", // ?
        "流派效果": "Genre Effect", // ?
        "模组后缀": "Module Suffixes", // ?
        "元素伤害": "Элементарный урон", // ?
        "特殊子弹": "Специальные пули", // ?
        "套装碎片": "Фрагменты набора",
        "素材": "Материалы",
        "近战蓝图": "Чертежи оружия ближнего боя",
        "手枪蓝图": "Чертежи пистолета",
        "霰弹枪蓝图": "Чертежи дробовика",
        "冲锋枪蓝图": "SMG Чертежи", // Submachine Gun Blueprints
        "步枪蓝图": "Чертежи винтовки",
        "狙击枪蓝图": "Чертежи снайперской винтовки",
        "轻机枪蓝图": "LMG Чертежи", // Light Machine Gun Blueprints
        "弓弩蓝图": "Чертежи арбалета",
        "家具配方": "Чертежи мебели",
        "肉类": "Мясо",
        "鱼类": "Рыба",
        "药草": "Травы",
        // Recipes - 食谱
        "食谱：熏肉罗宋汤": "Рецепт: Borscht Deluxe",
        "食谱：畸变塔可卷": "Рецепт: Taco", // In World item says Herbal Tea
        "食谱：星尘茶": "Рецепт: Stardust Tea",
        "食谱：培根肉排汉堡": "Рецепт: Bacon Burger",
        "食谱：南瓜星空派": "Рецепт: Stargazy Pie",
        "食谱：消脂果汁": "Рецепт: Fat-Burning Juice",
        "食谱：安全三明治": "Рецепт: Safety Sandwich",
        "食谱：星尘水果罐头": "Рецепт: Assorted Canned Food",
        "食谱：星尘通心粉罐头": "Рецепт: Stardust Italian Soup Can",
        "食谱：奇迹茶": "Рецепт: Miracle Tea",
        "食谱：碎裂面包": "Рецепт: Shattered Bread",
        "食谱：星尘南瓜泥沙拉": "Рецепт: Stardust Pumpkin Salad",
        "食谱：幽光蘑菇罐头": "Рецепт: Spectral Canned Mushroom",
        "食谱：星尘炸肉": "Рецепт: Mixed Fried Hot Dog",
        "食谱：元宝饺子": "Рецепт: Yuanbao Dumplings",
        "食谱：深海鱼片披萨": "Рецепт: Stargazy pizza",
        "食谱：炸薯条": "Рецепт: French Fries",
        "食谱：反重力奶昔": "Рецепт: Anti-gravity Milkshake",
        "食谱：金钱饼": "Рецепт: Croquette",
        "食谱：特调冰酿": "Рецепт: Signature Ice Brew",
        "食谱:奇思妙想饮": "Рецепт: Whimsical Drink",
        "食谱：炸鱼薯条": "Рецепт: Fish & Chips",
        "食谱：幽灵饼干": "Рецепт: Ghost Cookies",
        "食谱：畸变带骨香肠": "Рецепт: Bone-in Deviated Sausage",
        "食谱：捕获之汤": "Рецепт: Securement Soup",
        "食谱：蜜酿炖肉": "Рецепт: Honey Glaced Meat",
        // Deviants - 收容物
        "远归之蝶": "Butterfly's Emissary",
        "活体凝胶": "Festering Gel",
        "荣枯种子": "Harveseed",
        "捕梦网": "Dreamcatcher",
        "低语亡骨": "Canine Skull",
        "电鳗": "Electric Eel",
        "迪斯科球": "Disco Ball",
        "发条青蛙": "Frog the Leaper",
        "极寒水母": "Polar Jelly",
        "青龙": "Chefosaurus",
        "蜂团团": "Buzzy Bee",
        "工号37": "H37",
        //"": "Fetch-A-Lot Bunny",
        "姜饼屋": "Gingerbread House",
        //"": "Atomic Lighter",
        "凝视的黑猫": "Enchanted Void",
        "木工河狸": "Logging Beaver",
        "空间魔方": "Space Turner",
        "元素小子": "Digby Boy",
        //"": "Snow Globe",
        //"": "Growshroom",
        "皆斩": "Zeno-Purifier",
        "门扉": "Strange Door",
        //"": "Party Monkey",
        "巫毒娃娃": "Voodoo Doll",
        "炎之精": "Flame Essence",
        "破碎少女": "Shattered Maiden",
        //"": "Mini Wonder",
        "异维大猫": "Extradimensional Cat",
        "球状闪电": "Orb Lightning",
        "迷你黄衣": "Mini Feaster",
        "小纸人": "Paper Doll",
        //"": "Lethal Rabit",
        //"": "Artisan's Touch",
        "愿望先生": "Mr Wish",
        "红龙": "Pyro Dino",
        //"": "Dr. Teddy",
        "恶臭球根": "Grumpy Bulb",
        "空之子": "By-The-Wind",
        //"": "Lava Fox",
        "胡桃夹子": "Nutcracker",
        //"": "Wish Machine",
        "蝶之梦": "Rebecca",
        "气球狗": "Pup Buddy",
        "一碗美味": "Hug-In-A-Bowl",
        //"": "Masonic Pyramid",
        // Mysterious Painting - 诡谲画作
        "诡谲画作·代顿湿地": "Таинственная картина · Dayton Wetlands",
        "诡谲画作·破碎三角洲": "Таинственная картина · Broken Delta",
        "诡谲画作·铁锈河": "Таинственная картина · Iron River",
        "诡谲画作·垩峰山": "Таинственная картина · Chalk Peak",
        "诡谲画作·孤狼荒原": "Таинственная картина · Red Sands",
        "诡谲画作·黑心地带": "Таинственная картина · Blackheart",
        // Ores
        //"": "Камень",
        "硫磺": "Sulfur",
        "铜矿": "Copper руда",
        "锡矿": "Tin руда",
        "锡矿富集区": "Зона Tin руды",
        "铁矿": "Iron руда",
        "铝矿": "Aluminum руда",
        "钨矿": "Tungsten руда",
        "银矿": "Silver руда",
        "银矿区域": "Зона серебрянной руды",
        "银矿(稀有)": "Серебрянная руда (Случайно)",
        "银矿 (稀有)": "Серебрянная руда (Случайно)",
        "金矿": "Золотая руда",
        "金矿区域": "Золотая руда Area",
        "金矿(稀有)": "Золотая руда (Случайно)",
        "金矿 (稀有)": "Золотая руда (Случайно)",
        "金矿（先锋服)": "Золотая шахта",
        "星尘矿": "Stardust руда",
        "星尘矿石": "Stardust руда",
        "星尘矿区": "Зона Stradust руды",
        "星尘矿区域": "Зона Stradust руды",
        "星尘矿(稀有)": "Stardust руда (Случайно)",
        "星尘矿 (稀有)": "Stardust руда (Случайно)",
        // Plants
        "橘子": "Апельсины",
        "果蔬篮橘子": "Апельсины",
        "小麦": "Пшено",
        "果蔬篮小麦": "Пшено",
        "红色浆果": "Ягоды боярышника",
        "卷心菜": "Капуста",
        "果蔬篮卷心菜": "Капуста",
        "甜菜": "Свекла",
        "果蔬篮甜菜": "Свекла",
        "蓝莓": "Черника",
        "南瓜": "Тыква",
        "果蔬篮南瓜": "Тыква",
        "玉米": "Кукуруза",
        "果蔬篮玉米": "Кукуруза",
        "土豆": "Картофель",
        "果蔬篮土豆": "Картофель",
        "蘑菇": "Грибы",
        "果蔬篮蘑菇": "Грибы",
        //"": "Cucumber",
        //"": "Tomato",
        //"": "Red Tulip",
        //"": "Yellow Tulip",
        //"": "Yellow Hydrangea",
        //"": "Blue Hydrangea",
        //"": "White Petunia",
        //"": "Blue Petunia",
        "芦荟": "Aloe Vera",
        "鼠尾草 * 5": "Sage * 5",
        "鼠尾草 * 8": "Sage * 8",
        "桔梗": "Bellflower",
        "金银花": "Honeysuckle",
        "金银花 * 3": "Honeysuckle * 3",
        "金银花 * 4": "Honeysuckle * 4",
        "藏红花": "Saffron",
        "血菖蒲": "Scarlet Calamus",
        "紫锥菊": "Coneflower",
        "黄莲花": "Желтый лотос",
        //"": "Перчинка",
        "苹果": "Яблоко",
        "苹果树": "Яблочное дерево",
        "苹果树 * 2": "Яблочное дерево * 2",
        //"": "Cactus",
        "葡萄": "Виноград",
        "贝壳岩石": "Ракушечный камень",
        "海草岩石": "Камень из морских водорослей",
        "观赏性花海": "Море цветов",
        "香蕉树": "Банановое дерево",
        "香蕉树 * 2": "Банановое дерево * 2",
        "香蕉树 * 4": "Банановое дерево * 4",
        "香蕉树 * 6": "Банановое дерево * 6",
        "香蕉树 * 7": "Банановое дерево * 7",
        "椰子树": "Кокосовое дерево",
        "椰子树 * 3": "Кокосовое дерево * 3",
        "巨木": "Гигантское дерево",
        "龙血树(巨木)": "Гигантское дерево",
        // Animals
        "野生动物": "Животные",
        "兔子窝": "Кроличья нора",
        "鹿": "Олень",
        "星蚀鹿群": "Олень",
        "星蚀雄鹿": "Олень",
        "星蚀雌鹿": "Олень",
        "野猪": "Кабан",
        "野猪群": "Кабан",
        "星蚀鳄": "Аллигатор",
        "羊群": "Флок",
        "花豹": "Leopard",
        "星蚀熊窝": "Bear's Den",
        "星蚀熊": "Медведь",
        "肉排": "Стейк",
        "鳄鱼蛋": "Яйца аллигатора",
        "鸟蛋": "Яйца птиц",
        // Oil Wells
        "原油油井": "Нефтяная скважина",
        // Echo Stone - 回响石
            // has no individual names
        // Hints - 留言
        "别靠近箱子": "Мимик",
        "地堡门禁卡": "Карта доступа в бункер",
        "吓人箱子": "Мимик",
        "空间异动": "Космическая аномалия",
        "地下入口": "Подземный вход",
        "电话亭": "Телефонная будка",
        "拟态怪储物箱": "Мимик",
        "拟态宝箱怪": "Мимик",
        "密码: 5897": "Пароль: 5897",
        "密码: 325": "Пароль: 325",
        "地下通道入口": "Подземный вход",
        "地下通道最近入口": "Подземный вход",
        "地窖入口": "Подземный вход",
        "山洞入口": "Вход в пещеру",
        "溶洞入口": "Вход в пещеру",
        "镜女": "Зеркальный враг",
        "拟态储物箱别开": "Мимик",
        "电梯：负一层": "Лифт: Подземный уровень 1",
        "拟态宝箱怪别开": "Мимик",
        "空间异常": "Космическая аномалия",
        "5层楼梯": "5 Stairs",
        "箱子怪别开": "Мимик",
        "下楼电梯": "Лифт",
        "下楼电梯位置": "Лифт",
        "隐藏宝箱最后位置": "Сундук с сокровищами",
        "抽屉柜": "Ящики",
        // Side Quests - 隐藏任务
        //"": "A Miracle Chase",
        "隐藏的宝箱": "Morphic Crate Туториал", //
        //"异常档案": "",//Abnormal Files?
        //"": "The Shadowed Lighthouse",
        "玩具小熊": "The Call of Childhood",
        "急救！急救！": "Dayton Hospital",
        //'"玩具熊"女孩': "", //Teddy Bear Girl?
        //"": "Harvest Season",
        //"": "The Lost Lady",
        //"": "Deviation Expert",
        //"": "Martial God's Home",
        "信徒的藏宝图": "Lost In Madness - Отправная точка",
        "信徒的财产箱": "Lost In Madness - Местонахождение сокровищ",
        //"": "Stardust Infiltration",
        //"": "An Act of Theft",
        "检测点见闻": "Sketch of an Inspection Point",
        //"": "Supply Line",
        //"": "Where the Cat and Mice Play",
        "红与黑": "Carnival of Doom",
        //"": "The Treasure Infinite",
        //"": "Love Sorrow",
        //"": "Foreign Rock",
        //"": "Unfinished Expedition",
        //"": "Mayfly Badge",
        //"": "Secret Flavors",
        //"": "Save Meta-Human",
        //"": "Welcome!",
        //"": "Boy Just Wanna Have Fun",
        //"": "For Sarah",
        //"": "A Gift Overdue",
        //"": "Experimental Material",
        //"女儿的问候": "", //Greetings from my daughter?
        //"": "Into the Madness",
        //"": "Grumbling Scavenger",
        //"": "To Save or Not to Save",
        //"寻找记忆": "", //Searching for memories?
        //"": "Save Meta-Human",
        "被丢弃的玩偶": "Anna's Toys",
        //"": "Chance Encounter: Welcome Aboard",
        "艺术家的钥匙": "Cultist Meeting - Отправная точка",
        "信徒的宝箱": "Cultist Meeting - Местонахождение сокровищ",
        "特别关系": "A Special Relationship",
        //"嘉莲": "",
        "生日快乐": "Happy Birthday",
        //"": "Little Shop of Kindness",
        "招财猫开始点": "Lucky Cat - Отправная точка",
        "招财猫1号": "Lucky Cat #1",
        "招财猫2号": "Lucky Cat #2",
        "招财猫3号": "Lucky Cat #3",
        "招财猫给予的宝箱": "Lucky Cat - Местонахождение сокровищ",
        "好消息坏消息": "On Joy and Sorrow - Отправная точка",
        "神婆的宝箱": "On Joy and Sorrow - Местонахождение сокровищ",
        //"成就：一览众山小": "",//Achievement: A view of the world?
        "农庄惊魂": "Ужас на ферме",
        "限定版牛奶": "Ограниченное издание",
        "考古学家的馈赠": "Be True 'Til Death",
        "遗留财产": "A Family Legacy",
        "悲伤画像": "Sorrowful Portrait",
        //"罗塞塔保险箱": "", //Rosetta Safe?
        "密码：9274": "Пароль: 9274", //Really a Side Quest?
        "秘密配方": "Рецепт", //Really a Side Quest?
        // Merchant - 商人
        "韦伯": "Weber",
        "赵金潭": "Zhao Jintan",
        //"": "Jonathan",
        //"": "Emma Potter",
        "拟态体商店": "Severin VII-S2041 (Торговец SIRA)",
        //"": "Nisa (Sproutlet Trader)",
        "鱼饵商人": "Margerie (Торговец рыбой)",
        "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie【Чертежи рыб】",
        // Livable Location - 宜居地点
        // Livable Location are the recommended places to live with subjective opinions, These are usually large flat areas with rich resources and close to water sources.
            // has no individual names
        // Not sure where/if the following are used.
        "异常点": "Аномальный объект",
        "稀有": "Редко",
        "持续刷新": "Continuous Refresh",
        "碧湖山庄": "Greenlake Hill",
        "检测点91": "Inspection Point 91",
        "戴维思角": "Davis Point",
        "检测点24": "Inspection Point 24",
        "翻车鱼岛旅客中心": "Mola Island Visitor Center",
        "治炼厂污染点": "Refinery Pollution Plan",
        "检测点3711": "Inspection Point 3711",
        // 2024/08/17
        "翠湖山镇": "Greenlake Hill",
        "无蘑菇": "Грибов нет",
        "果蔬箱土豆": "Potato",
        "油田区域": "Oilfield Area",
        "抽水泵采集": "Pump",
        "洞穴内": "Внутри пещеры",
        "便携式燃油": "Portable Fuel",
        "腐化熊": "Bear",
        "水豚": "Capybara",
        "狼": "Wolf",
        "鳄鱼": "Crocodile",
        "长嘴海鸥": "Long-Billed Seagull",
        "海龟": "Sea Turtle",
        "鹈鹕": "Pelican",
        "兔子": "Rabbit",
        "鳄龟": "Snapping Turtle",
        "狐狸": "Fox",
        "浣熊": "Raccoon",
        "火烈鸟": "Flamingo",
        "腐化鳄": "Corrupted Crocodile",
        "腐化狼": "Corrupted Wolf",
        "白斑狗鱼钓鱼点": "Northern Pike",
        "白斑狗鱼": "Northern Pike",
        "海鲈鱼": "Sea Bass",
        "神仙鱼": "Angelfish",
        "长吻雀鳝": "Longnose Gar",
        "黑鲈": "Black Bass",
        "孔雀鱼": "Guppy",
        "鲤鱼": "Carp",
        "图丽鱼": "Astronotus Ocellatus",
        "太阳鱼": "Lepomis",
        "锦鲤": "Koi",
        "龙鱼": "Arowana",
        "鳙鱼": "Bighead Carp",
        "沙丁鱼": "Sardine",
        "梭鱼": "Barracuda",
        "鲭鱼": "Mackerel",
        "罗非鱼": "Tilapia",
        "虹鳟": "Rainbow Trout",
        "鲑鱼": "Salmon",
        "鲳鲹": "Pompano",
        "松鼠": "Squirrel",
        "亚口鱼": "Sucker",
        // scenario
        "PvE-天空之触": "PvE-MANIBUS",
        "PvP-分歧之路": "PvP-Evolution's Call",
        // map
        "玩家": "Player"
    }
}
