export default {
  buttons: {
    filter: "Filtrele",
    select_all: "Hepsini Seç",
    deselect_all: "Seçimi Kaldır",
    close: "",
    move_left: "",
    move_right: "",
    edit: "Düzenle",
    quit: "Çık",
    apply: "Evet", //Onayla
    cancel: "Hayır", //İptal
    heatmap: "Kaynak Isı Haritası",
  },
  edit: {
    mode_switch: "Düzenleme moduna girilsin mi/çıkılsın mı?", 
  },
  tabs: {
    by_category: "Kategori",
    by_item: "Eşya",
    by_search: "Ara",
    resource_list: "Kaynaklar",
    setting: "Ayarlar",
    user_data: "Kullanıcı Verileri",
    quick_setting: "Hızlı Ayarlar",
    quick_setting_fuel_loot: "Yakıt Yağması",
    quick_setting_resource: "Kaynak",
    quick_setting_bus_route: "Canavar Otobüsü",
    quick_setting_show_players: "Oyuncuları Göster",
    quick_setting_pollution: "Kirlilik",
    quick_setting_popup_coordinate: "İmleci Takip Eden Koordinat",
    quick_setting_disaster_area: "Chaos Weaver Felaket Bölgesi",
    area: "Bölgeler",
    treasure: "Hazineler",
    monster: "Keşif",
    collection: "Koleksiyon",
    hint: "İpucu",
    logged: "Veri",
    guest: "Giriş Yap",
    oneclick_delete_enable: "Tek Tıkla Sil",
    oneclick_delete_disable: "Devre Dışı",
    oneclick_delete_badge: "Tek Tıkla Silme Modunda",
    oneclick_delete_hint1:
      "Bu mod açıldığında, bir işarete tıklamak artık açılır pencere göstermez; doğrudan işareti siler veya silme işlemini geri alır.",
    oneclick_delete_enable_hint: "Tek tıkla silme modu etkinleştirildi",
    oneclick_delete_disable_hint: "Tek tıkla silme modu devre dışı bırakıldı",
    oneclick_delete_dialog_title: "Uyarı",
    oneclick_delete_dialog_content:
      "Tek tıkla silme modunu açtıktan sonra, haritada bir işarete tıkladığınızda açılır pencere görünmeyecektir. Bunun yerine işaret doğrudan silinecek veya silinmesi geri alınacaktır. Devam etmek istiyor musunuz?",
    oneclick_delete_dialog_close: "Kapat",
    oneclick_delete_dialog_confirm: "Onayla",
    batch_editing_enable: "İlerleme",
    batch_editing_disable: "Çıkış",
    batch_editing_hint:
      "Bir kategorideki tüm işaretleri toplu olarak silebilir veya silinmesini geri alabilirsiniz. Kullanmak için giriş yapmanız gerekir.",
    setting_btn_hint: "Harita ile ilgili ayarlar",
    login_btn_hint: "Verilerimi yönet",
    back_to_categories: "Kategorilere Geri Dön",
    display_area: "Bölge Filtresi",
    select_item_category: "Seç",
    related_items: "İlgili Eşyalar",
    locate_item: "Konumlandırmak için eşyaya tıklayın",
    search_resources: "Kaynakları Ara",
    input_resource_name: "İsim girin",
    locate: "Konumlandır",
    // Çeşitli Arayüz Metinleri
    any_name: "Herhangi Bir Kelime",
    keyword: "Anahtar Kelime",
    locations: "Konumlar",
    locate_point: "Konumu ortalamak için tıklayın",
    input_item: "Lütfen bir Konum Adı girin",
    related_item: "Eşyalar",
    related_makers: "İşaretçiler",
    locate_marker: "İşaretçiyi ortalamak için tıklayın",
    input_marker: "Lütfen bir İşaretçi Adı girin",
    related_resources: "Kaynaklar",
    locate_resource: "Kaynağı ortalamak için tıklayın",
    input_resource_for_searching: "Lütfen bir Kaynak Adı girin",
    follow_xingchuan: "Xingchuan'ı Takip Et",
    bilibili: "BiliBili",
    tiktok: "TikTok",
    ad: "Reklam",
    ad2: "Reklam",
    jd: "Reklam bu sürümde mevcut değil",
    daigan: "Reklam bu sürümde mevcut değil",
    login_warring: "Lütfen önce Discord Sunucusu botundan metni alın.",
    delete_all: "Hepsini Sil",
    resume_all: "Geri Yükle",
    exit_management_mode: "Çıkış",
    select_scenario: "Senaryo",
    show_unreviewed_markers: "İncelememiş İşaretçiler",
    show_unreviewed_areas: "İncelememiş Bölgeler",
    地点区域: "Konumlar",
    宝箱秘藏: "Sırlar",
    事件怪物: "Canavarlar",
    收集要素: "Koleksiyonlar",
    异象轮盘: "Yanılsama Çarkı",
    地图提示: "İpuçları",
    无尽长梦: "Sonsuz Rüya",
    "七日世界：禁区": "OnceHuman: Baskın Bölgesi",
    非正常收容: "Sapma: Hayatta Kalma",
    乐园岛: "Cennet Adası",
    污染区: "Kirlilik Bölgeleri",
    tool_box: "Araç Kutusu",
    about_website: "Hakkında"
  },
  floor_text: {
    roof: "( Çatı )",
    at_floor: "( Kat {floor} )",
    underground: "( Kat {floor} Yer Altı )",
    level: "( Seviye {level} )",
  },
  settings: {
    has_video: "Video İşaretçisi",
    deleted_marker: "Silinen İşaretçi",
    map_area_style: "Harita Alan Stili",
    monster_bus_route: "Canavar Otobüsü Rotası",
    marker_text: "İşaretçi Metni",
    resource_area: "Kaynak Alanı",
    last_updated_datetime: "İşaretçi Güncellenme Zamanı",
    icon_drawing_method:
      "Simge Çizim Yöntemi (Simgeler bozuk görünüyorsa Canvas/Tuval önerilir)",
    dark_mode: "Karanlık Mod",
    language: "Dil",
    auto_query: "Kategoriler Değiştiğinde Sorgula",
    auto_draw_marker_after_search: "Arama Sonucunu Haritada Göster",
    show: "Göster",
    hide: "Gizle",
    line_style: "Çizgi Stili",
    area_style: "Dolgu Stili",
    wasm: "Wasm (En İyi Performans)",
    canvas: "Canvas (En İyi Uyumluluk)",
    on: "Açık",
    off: "Kapalı",
    draw_text_mode: "İşaretçi Metin Stili",
    draw_text_mode_1: "Tam",
    draw_text_mode_2: "Basitleştirilmiş",
    deleted_marker_style: "Silinen İşaretçi Stili",
    deleted_marker_style_1: "Çarpı",
    deleted_marker_style_2: "Yarı Saydam",
    deleted_marker_style_3: "Gizle",
  },
  user_data: {
    local_storage: "Yerel Veri",
    count: "kayıt yok | {count} kayıt | {count} kayıt",
    local_storage_tutorial: "Eğitim",
    backup: "Yedekle & Geri Yükle",
    local_storage_text:
      "Giriş yapmadan da işaretçileri silebilirsiniz. Ancak veriler yalnızca mevcut tarayıcıda saklanır. Verilerinizi yedekleyip başka bir tarayıcıya aktarabilirsiniz.",
    backup_placeholder: "Veriler",
    backup_button: "Yedekle",
    restore_button: "Geri Yükle",
    cloud_storage: "Bulut Verisi",
    clear_all_data: "Tüm Verileri Sil",
    restore_hint:
      "İpucu: Bu işlem yerel verileri içe aktarılan verilerle birleştirecektir. Giriş yaptıysanız veriler bulutla da senkronize edilir. Devam etmek istiyor musunuz?",
    delete_hint:
      "Tüm verileri silmek istediğinizden emin misiniz? Giriş yaptıysanız bulut verileri de temizlenecektir. Devam etmek istiyor musunuz?",
    wechat_login: "Wechat",
    wechat_mp_login: "Wechat2",
    discord_login: "Discord",
    login_tutorial: "Eğitim",
    login_tutorial_text:
      "Giriş yaptıktan sonra yerel ve bulut verileriniz otomatik olarak senkronize edilir; böylece haritayı herhangi bir cihaz veya tarayıcıda kullanmaya devam edebilirsiniz. Giriş yapmadan da normal şekilde kullanabilirsiniz ancak verileriniz yalnızca yerel tarayıcıda saklanır.",
    not_login: "Giriş yapılmadı",
    login_success: "Başarıyla giriş yaptınız",
    data_is_syncing: "Veriler Senkronize Ediliyor",
    last_syncing_time: "Son Senkronizasyon Zamanı: ",
    logout: "Çıkış Yap",
  },
  marker_dialog: {
    no_marker_img: "Görsel Yok",
    delete_markder: "İşaretçiyi Sil",
    undelete: "Silmeyi Geri Al",
    delete_only: "Sadece Sil",
    hide_category: "{category} Gizle",
    no_update_time: "Güncelleme zamanı yok",
    rewards: "Ödüller",
    close: "Kapat",
    detail: "Detay",
    operation: "İşlem",
    timer_title: "Kasa Sıfırlanma Zamanlayıcısı",
    timer_title_not_login: "(Giriş Gerekli) Kasa Sıfırlanma Zamanlayıcısı",
    deviant_timer_title: "Sapma Sıfırlanma Zamanlayıcısı",
    to_login: "Zamanlayıcı Özelliğini Açmak İçin Giriş Yapın",
    comment: "Yorumlar",
    auto_set_timer: "Otomatik Zamanlayıcı Ayarla",
    auto_set_timer_not_login: "(Giriş Gerekli) Otomatik Zamanlayıcı Ayarla",
    timer_tutorial: "Zamanlayıcı Eğitimi",
    sharing: "Paylaşım",
    session_script: "Şu anda şurada mevcut: ",
    hint: "[ İpucu ]",
    sharing_hint:
      "Paylaşılan bağlantı açıldığında harita otomatik olarak bu işaretçiyi gösterecektir.",
    download_qr_code: "İndir",
    sharing_link: "Bağlantı",
    copy: "Kopyala",
    update: "Güncellendi",
    guide: "Rehber",
    donate: "Bağış Yap",
    auto_reset_help_title: "Yardım",
    auto_reset_help_text:
      "Silah ve teçhizat kasalarının sabit yenilenme süresi 00:00:00'da başlar ve her 4 saatte bir tam saatte sıfırlanır. Sıfırlanma saati gelmesine rağmen kasaları açamıyorsanız oyuna tekrar giriş yapmanız yeterlidir.",
    auto_reset_help_ok: "Tamam",
    click_to_copy: "Kopyalamak için Tıkla",
    copied_successfully: "Başarıyla Kopyalandı",
    common_hint: "Genel İpuçları",
    batch_import: "Toplu İçe Aktar",
    navigation_settings: "Navigasyon Ayarları",
    contributors: "Katkıda Bulunanlar",
  },
  donate: {
    payment: "Lütfen WeChat kullanarak QR kodunu taratın",
    text: "Desteğiniz web sitesinin çalışmaya devam etmesine ve yeni özellikler eklenmesine yardımcı olur",
    warning: "Reşit olmayanların bağış yapması yasaktır",
  },
  scenario: {
    not_available: "Mevcut Değil",
    current: "Mevcut",
    available: "Erişilebilir",
    coming: "Yakında",
    scenarios: "Haritalar",
  },
  languages: {
    dialog_title: "Dil Seçin",
    dialog_close: "Kapat",
    contributors: "Katkıda Bulunanlar",
    help_1: "Aradığınız dili bulamadınız mı?",
    help_2: "Çevirileri geliştirmeye yardımcı olmak için buraya tıklayın.",
    default: "Varsayılan",
  },
  path_planning: {
    path_planning: "Rota Planlama",
    start: "Başlangıç Noktası",
    end: "Bitiş Noktası",
    select_start: "Başlangıç Noktası Seç",
    select_end: "Bitiş Noktası Seç",
    tips: "İpucu: Noktaları hızlıca ayarlamak için haritaya sağ tıklayabilirsiniz",
    clear: "Rotayı Temizle",
    submit: "Rotayı Sorgula",
    cancel: "Temizle",
    placeholder: "Haritadan seçin",
  },
  heatmap: {
    no_data: "Veri Yok",
    hint: "Isı haritası rengi ne kadar koyuysa, o kadar fazla kaynak var demektir",
    clear: "Isı Haritasını Temizle",
  },
  categories: {
    // Alanlar
    传送塔: "Işınlanma Kulesi",
    巨楔: "Monolit",
    主城: "Yerleşke",
    研究所: "Laboratuvar",
    大型资源点: "Kasaba",
    小型资源点: "Köy",
    收容井: "Tecrit Silosu",
    位面锚: "Yarık Çıpası",
    空间锚点: "Yarık Çıpası",
    观景点: "Manzara Noktası",
    // Hazineler
    神秘宝藏: "Mistik Kasa", 
    神秘宝箱: "Mistik Kasa", 
    武器箱: "Silah Kasası",
    装备箱: "Teçhizat Kasası",
    隐藏宝箱: "Gizli Kasa",
    秘藏宝箱: "Gizli Zula Kasası",
    宝箱怪: "Morfik Kasa",
    储物箱: "Depolama Kasası",
    // Keşif
    精英怪: "Seçkin Canavar",
    迷雾区域: "Sis Etkinliği",
    防守工坊: "Atölye",
    移动房屋: "Yürüyen Ev",
    限时事件: "Kırmızı Etkinlik",
    灭绝者: "Chaos Weaver",
    "灭绝者(二阶段)": "Chaos Weaver (Aşama 2)",
    "灭绝者(三阶段)": "Chaos Weaver (Aşama 3)",
    "冰灭绝者(一阶段)": "Buz Chaos Weaver (Aşama 1)",
    "冰灭绝者(二阶段)": "Buz Chaos Weaver (Aşama 2)",
    "冰灭绝者(三阶段)": "Buz Chaos Weaver (Aşama 3)",
    "冰灭绝者(二/三阶段)": "Buz Chaos Weaver (Aşama 2/3)",
    "冰灭绝者(一/四阶段)": "Buz Chaos Weaver (Aşama 1/4)",
    "冰灭绝者(二/四阶段)": "Buz Chaos Weaver (Aşama 2/4)",
    "冰灭绝者(三/四阶段)": "Buz Chaos Weaver (Aşama 3/4)",
    "冰灭绝者(二/三/四阶段)": "Buz Chaos Weaver (Aşama 2/3/4)",
    "冰灭绝者(四阶段)": "Buz Chaos Weaver (Aşama 4)",
    "火灭绝者(二阶段)": "Ateş Chaos Weaver (Aşama 2)",
    "火灭绝者(三阶段)": "Ateş Chaos Weaver (Aşama 3)",
    "火灭绝者(四阶段)": "Ateş Chaos Weaver (Aşama 4)",
    "火灭绝者(one/四阶段)": "Ateş Chaos Weaver (Aşama 1/4)",
    "火灭绝者(二/四阶段)": "Ateş Chaos Weaver (Aşama 2/4)",
    "火灭绝者(三/四阶段)": "Ateş Chaos Weaver (Aşama 3/4)",
    "火灭绝者(二/三/四阶段)": "Ateş Chaos Weaver (Aşama 2/3/4)",
    // Koleksiyon
    武器配件: "Eklenti", 
    食谱: "Tarif",
    收容物: "Sapma",
    诡谲画作: "Gizemli Tablo",
    矿物点: "Maden",
    采集点: "Malzeme",
    种子箱: "Tohum Sandığı",
    调味料箱: "Baharat Sandığı",
    种子香料: "Tohum & Baharat",
    飲料机: "İçecek Otomatı",
    随机素材箱: "Rastgele Sandık",
    抗菌剂箱: "Medikal Sandık",
    // PvP
    回响石: "Yankı Taşı",
    // İpuçları
    留言: "İpucu",
    隐藏任务: "Yan Görev",
    支线任务: "Yan Görev",
    商人: "Tüccar",
    宜居地点: "Yaşanabilir Konum",
    // Bölgeler
    代顿湿地: "Dayton Sulak Alanları",
    破碎三角洲: "Kırık Delta",
    垩峰山: "Chalk Zirvesi",
    铁锈河: "Paslı Nehir",
    孤狼荒原: "Kızıl Kumlar",
    黑心地带: "Kara Kalp",
    玛瑙冻原: "Oniks Tundrası",
    维纳峡湾: "Vena Fiyordu",
    余烬滩: "Köz Sahili",
    // Rotalar
    怪物巴士路线: "Canavar Otobüsü",
    便携混合燃油: "Taşınabilir Karışık Yakıt",
    // Alan Özellikleri
    污染区: "Kirli Bölge",
    污染值: "Kirlilik Değeri",
    建筑无法幸存: "Yapı ayakta kalamaz",
    建筑会受损: "Yapı hasar görür",
    被发现范围: "Tehlike Menzili",
    // Işınlanma Kuleleri - 传送塔
    猎犬岛传送塔: "Işınlanma Kulesi",
    望岛镇传送塔: "Işınlanma Kulesi",
    离岸广场传送塔: "Işınlanma Kulesi",
    临溪东部传送塔: "Işınlanma Kulesi",
    贪欲巨楔传送塔: "Açgözlülük Monoliti Işınlanma Kulesi",
    代顿检查点传送塔: "Işınlanma Kulesi",
    高岸南部传送塔: "Işınlanma Kulesi",
    西格玛传送塔: "Işınlanma Kulesi",
    暖阳中部传送塔: "Işınlanma Kulesi",
    三角洲南部传送塔: "Işınlanma Kulesi",
    盖亚山区传送塔: "Işınlanma Kulesi",
    盖亚巨楔传送塔: "Gaia Kayalığı Monoliti Işınlanma Kulesi",
    代顿北部传送塔: "Işınlanma Kulesi",
    高地西部传送塔: "Işınlanma Kulesi",
    盖亚西部传送塔: "Işınlanma Kulesi",
    朽鞍镇传送塔: "Işınlanma Kulesi",
    银滩北部传送塔: "Işınlanma Kulesi",
    翠湖南部传送塔: "Işınlanma Kulesi",
    翠湖北部传送塔: "Işınlanma Kulesi",
    阿尔法传送塔: "Işınlanma Kulesi",
    月湖传送塔: "Işınlanma Kulesi",
    庄园东部传送塔: "Işınlanma Kulesi",
    尖牙巨楔传送塔: "Susuzluk Monoliti Işınlanma Kulesi",
    蜿蜒山区传送塔: "Işınlanma Kulesi",
    波光北部传送塔: "Işınlanma Kulesi",
    黯梦巨楔传送塔: "Serap Monoliti Işınlanma Kulesi",
    风角边境传送塔: "Işınlanma Kulesi",
    谷地南部传送塔: "Işınlanma Kulesi",
    西塔传送塔: "Işınlanma Kulesi",
    黑原中部传送塔: "Işınlanma Kulesi",
    遗忘巨楔传送塔: "Terk Edilmiş Monolit Işınlanma Kulesi",
    悬巢北部传送塔: "Işınlanma Kulesi",
    悬巢南部传送塔: "Işınlanma Kulesi",
    内部传送塔: "Işınlanma Kulesi",
    巨人阶梯传送塔: "Işınlanma Kulesi",
    黑心内弯传送塔: "Kara Kalp Koyu Işınlanma Kulesi",
    // Way of Winter - 雪国人生
    冻火湾传送塔: "Donmuş Ocak Koyu Işınlanma Kulesi", 
    冻火北部传送塔: "Kuzey Donmuş Ocak Işınlanma Kulesi", 
    鲸骨湾传送塔: "Balina Kemiği Koyu Işınlanma Kulesi", 
    山阴传送塔: "Dağ Gölgesi Işınlanma Kulesi", 
    水畔传送塔: "Su Kenarı Işınlanma Kulesi", 
    港区传送塔: "Liman Bölgesi Işınlanma Kulesi", 
    绿野传送塔: "Yeşil Alan Işınlanma Kulesi", 
    乐园传送塔: "Dilek Diyarı Işınlanma Kulesi", 
    望海传送塔: "Deniz Manzarası Işınlanma Kulesi", 
    林场传送塔: "Orman Çiftliği Işınlanma Kulesi", 
    慕斯市传送塔: "Moose Şehri Işınlanma Kulesi", 
    潮间地传送塔: "Gelgit Alanı Işınlanma Kulesi", 
    黑石东部传送塔: "Doğu Karataş Işınlanma Kulesi", 
    黑石北部传送塔: "Kuzey Karataş Işınlanma Kulesi", 
    冻原中部传送塔: "Merkezi Tundra Işınlanma Kulesi", 
    大河警戒区传送塔: "Tayga Yasak Bölgesi Işınlanma Kulesi", 
    母巢巨穴传送塔: "Hiverail Mağarası Işınlanma Kulesi", 
    破碎岩礁传送塔: "Kırık Resifler Işınlanma Kulesi", 
    雪崩巨楔传送塔: "Çığ Monoliti Işınlanma Kulesi", 
    雪崖传送塔: "Kar Uçurumu Işınlanma Kulesi", 
    冻火西部传送塔: "Batı Donmuş Ocak Işınlanma Kulesi", 
    烟袋群岛传送塔: "Pipo Adası Işınlanma Kulesi", 
    蛇眼山口传送塔: "Yılan Gözü Geçidi Işınlanma Kulesi",
    蛇腹传送塔: "Yılan Karnı Işınlanma Kulesi",
    蛇尾传送塔: "Yılan Kuyruğu Işınlanma Kulesi",
    熟土区传送塔: "Olgun Topraklar Işınlanma Kulesi",
    火喉北部传送塔: "Kuzey Ateş Boğazı Işınlanma Kulesi",
    火喉东部传送塔: "Doğu Ateş Boğazı Işınlanma Kulesi",
    火喉飞升传送塔: "Ateş Boğazı Yükselişi Işınlanma Kulesi",
    火喉根基传送塔: "Ateş Boğazı Üssü Işınlanma Kulesi",
    灰落传送塔: "Kül Kasabası Işınlanma Kulesi",
    寂火传送塔: "Sessiz Ateş Işınlanma Kulesi",
    灼风传送塔: "Alevli Rüzgar Işınlanma Kulesi",
    硫磺池传送塔: "Kükürt Havuzu Işınlanma Kulesi",
    炽尘巨楔传送塔: "Ateş Tozu Işınlanma Kulesi",

    // Monolitler - 巨楔
    贪欲巨楔: "Açgözlülük Monoliti",
    盖亚巨楔: "Gaia Kayalığı Monoliti",
    黯梦巨楔: "Serap Monoliti",
    尖牙巨楔: "Susuzluk Monoliti",
    遗忘巨楔: "Terk Edilmiş Monolit",
    冻原巨楔: "Tundra Monoliti", 
    雪崩巨楔: "Çığ Monoliti", 
    炽尘巨楔: "Ateş Tozu Monoliti",
    // Ana Şehirler/Yerleşkeler - 主城
    旅人营地: "Deadsville (Ölüler Kasabası)",
    迈尔集市: "Meyer Pazarı",
    秽水营地: "Bulanık Su Kampı",
    深草旅店: "Uzun Ot Hanı",
    黑原镇: "Blackfell (Kara Kasaba)",
    遗忘之地: "Oblivion (Unutulmuş Topraklar)", 
    熊栖雪场: "Ayı İni", 
    鲸骨乡: "Balina Kemiği", 
    冰屋营地: "İglo Kampı", 
    不落号坠落点: "Unfallen Enkaz Alanı",

    // Laboratuvarlar - 研究所
    生命进化研究所: "Evrim Enstitüsü",
    ”黑域“之门: "Pus Bölgesi Girişi", 

    // Kasabalar / Büyük Kaynak Noktaları - 大型资源点
    中途镇: "Throughville",
    腐烂庄园: "Çürük Malikane",
    橘子镇: "Citrus Bölgesi",
    望岛镇: "Overlook Kasabası",
    苏德兰果园: "Sutherland Aile Bostanı",
    离岸广场: "Sahil Meydanı",
    临溪: "Brookham",
    代顿医院: "Dayton Hastanesi",
    贪欲巨楔警戒区: "Açgözlülük Monoliti Tehlike Bölgesi",
    赫斯特工业: "Hearst Endüstrileri",
    海港镇: "Harborside (Liman Kenarı)",
    猎犬岛哨站: "Vahşi Köpek Adası Karakolu",
    暖阳中学: "Sunbury Ortaokulu",
    暖阳镇: "Sunbury",
    苏德兰化工厂: "Sutherland Kimya Fabrikası",
    高岸镇: "High Banks (Yüksek Kıyılar)",
    废弃货场: "Hurdalık",
    盖亚研究所遗址: "Gaia Araştırma Merkezi Kalıntıları",
    东部铁路枢纽: "Doğu Demiryolu Kavşağı",
    盖亚巨楔警戒区: "Gaia Kayalığı Monoliti Tehlike Bölgesi",
    高地: "Highland (Yüksek Bölge)",
    冶炼厂污染点: "Rafineri Kirlilik Tesisi",
    秽水工业区: "Bulanık Su Endüstri Bölgesi",
    阿卡尔克镇: "Alkirk",
    东黑原枢纽: "Doğu Blackfell Kavşağı",
    波光镇: "Rippleby",
    里奇收容点: "Ricci Güvenli Noktası",
    黯梦巨楔警戒区: "Serap Monoliti Tehlike Bölgesi",
    盖亚军事基地: "Gaia Askeri Üssü",
    朽鞍镇: "Rotten Saddle",
    银滩度假区: "Silvershore Tatil Köyü",
    碧湖山镇: "Greenlake Tepesi",
    霍特镇: "Holt Kasabası",
    熔炉巢穴: "Eritme Ocağı İni",
    常青藤酒庄: "Evergreen Bağı",
    阿尔法研究所: "Alpha Enstitüsü",
    尖牙巨楔警戒区: "Susuzluk Monoliti Tehlike Bölgesi",
    交错现实研究所: "Alternatif Gerçeklik Araştırma Enstitüsü",
    黑原油田: "Blackfell Petrol Sahaları",
    黑原陷落区: "Blackfell Çöküş Bölgesi",
    绿荫镇: "Evergreen",
    悬巢: "Fort Eyrie",
    "73号源质分离点": "73 Kaynak Çıkarma Noktası",
    太阳农场: "Sunshine Çiftliği",
    白崖基地: "White Cliff Üssü",
    // Way of Winter - 雪国人生
    灼风气象站: "Scorchwind Gözlemevi", 
    炎神研究所: "Ateş Tanrısı Araştırma Merkezi", 
    圣城前哨: "Firethroat Yakınları", 
    火喉下城: "Firethroat Kalesi", 
    灰落车站: "Ashenton İstasyonu", 
    熟土农庄: "Olgun Topraklar Çiftliği", 
    蛇尾滑索营地: "Yılan Kuyruğu Zipline Kampı", 
    火喉弃民街: "Firethroat Gecekonduları", 
    燃尽之地: "Kavrulmuş Çorak Topraklar", 
    废弃提炼厂: "Terk Edilmiş Rafineri", 
    攀火祭祀场: "Ateş Sunağı", 
    望火港: "Firewatch Limanı", 
    烟袋度假区: "Tütün Tatil Köyü", 
    黑石灯塔: "Obsidyen Deniz Feneri", 
    异火码头: "Pyro Limanı", 
    无明港: "Işıksız Liman", 
    蛇眼瞭望点: "Yılangözü Gözetleme Noktası", 
    蛇腹洞穴: "Yılankarnı Mağarası", 
    纵队巡逻点: "Gerilla Devriye Noktası", 
    硫磺池采伐区: "Kükürt Ocağı", 
    温泉民宿: "Kaplıca Hanı", 
    火喉圣域: "Firethroat Kutsal Alanı", 
    冻火湾: "Frost Forge (Donmuş Ocak)", 
    避火者地堡: "Alev Sığınağı", 
    炽尘巨楔警戒区: "Ateş Tozu Monoliti Tehlike Bölgesi", 
    "“母巢”收容保护区": "Hiverail Yasak Bölgesi", 
    雪崩巨楔警戒区: "Çığ Monoliti Tehlike Bölgesi", 
    雪原气象站: "Kar Alanı Kontrol Noktası", 
    悬空哨卡: "Asılı Kontrol Noktası", 
    冻原巨楔警戒区: "Tundra Monoliti Tehlike Bölgesi", 
    检测点653: "Muayene Noktası 653", 
    "“大河”收容场": "Tayga Tecrit Alanı", 
    罗塞塔巡逻站: "Rosetta Devriye İstasyonu", 
    慕斯市食品厂: "Moose Şehri Gıda Fabrikası", 
    慕斯市: "Moose Şehri", 
    慕斯市郊废屋: "Moose Şehri Banliyösündeki Terk Edilmiş Ev", 
    栖木岭观景台: "Tüneme Ağacı Manzara Terası", 
    栖木缆车站: "Tüneme Ağacı Teleferik İstasyonu", 
    藏火岩洞: "Gizli Ateş Mağarası", 
    黑石要塞: "Karataş Kalesi", 
    "“心愿奇境”西园区": "Wishland (Dilek Diyarı) Batı", 
    "“心愿奇境”东园区": "Wishland (Dilek Diyarı) Doğu", 
    乐园东入口: "Wishland Doğu Girişi", 
    乐园西入口: "Wishland Batı Girişi", 
    滑索洞穴营地: "Zipline Mağara Kampı", 
    融冰港: "Eriyen Buz Limanı", 
    菲斯库尔港: "Fiskur Limanı", 
    影日洞穴: "Güneş Siperi Mağarası", 
    灰落市: "Ashenton (Kül Kasabası)", 

    // Köyler / Küçük Kaynak Noktaları
    中途镇变电站: "Throughville Trafosu",
    检测点3771: "Muayene Noktası 3771",
    翻车鱼岛游客中心: "Mola Adası Ziyaretçi Merkezi",
    海岬庄园: "Burun Malikanesi",
    小码头: "Küçük Liman",
    艾尔汽修店: "Aiden's Oto Tamir",
    艾尔的隐蔽所: "Aiden's Sığınağı",
    检测点7802: "Muayene Noktası 7802",
    临溪警戒所: "Brookham Karakolu",
    代顿货栈: "Dayton Deposu",
    崖下营地: "Uçurum Kenarı Kampı",
    北岸营地: "Kuzey Sahili Kampı",
    赫斯特: "Hearst",
    赫斯特滩涂: "Hearst Çamur Düzlükleri",
    湖心野营地: "Göl Kalbi Kampı",
    迈尔: "Meyer",
    高岸巢穴: "Highbank Yuvası",
    废弃隐蔽所: "Terk Edilmiş Sığınak",
    骑士修车店: "Şövalye Araç Tamiri",
    山脊中转站: "Sırt Aktarma İstasyonu",
    山脊营地: "Sırt Kampı",
    暖阳农庄: "Sunbury Çiftliği",
    瀑布广场: "Şelale Meydanı",
    沉船坟场: "Gemi Mezarlığı",
    沉没宅院: "Batık Ev",
    检测点024: "Muayene Noktası 024",
    检测点9043: "Muayene Noktası 9043",
    "TAB-6A营地": "Tab-6A Kampı",
    高地居住区: "Highland Yerleşim Alanı",
    洗劫一空的营地: "Yağmalanmış Kamp",
    远眺伐木场: "Manzaralı Kereste Fabrikası",
    污染检测点77: "Kirlilik Muayene Noktası 77",
    河心码头: "Nehir Kalbi Limanı",
    河畔纪念品店: "Nehir Kenarı Hediyelik Eşya",
    枯竭油井: "Tükenmiş Petrol Kuyusu",
    蜿蜒山种植园: "Kıvrımlı Sırt Tarım Alanı",
    浅滩公园: "Sığlık Parkı",
    波光镇集市: "Rippleby Pazarı",
    风车阵列: "Rüzgar Çiftliği",
    秘港: "Gizli Liman",
    检测点023: "Muayene Noktası 023",
    克里夫顿: "Clifton",
    海风疗养地: "Meltem Sahili Tatil Köyü",
    诺顿农场: "Norton Çiftliği",
    高岸检测点: "Highbank Denetim Noktası",
    私酿庄园: "Kaçak İçki Malikanesi",
    老大的乐园: "Patronun Oyun Alanı",
    霍特电站: "Holt Güç İstasyonu",
    帕斯利广场: "Paisley Meydanı",
    山麓别墅: "Dağ Eteği Çiftliği",
    盖亚通讯阵列: "Gaia İletişim İstasyonu",
    检测点266: "Muayene Noktası 266",
    狂热信徒聚落: "Mürit Kolonisi",
    戴维斯角: "Davis Noktası",
    鞍前营地: "Eyer Önü Kampı",
    渔人码头: "Balıkçı İskelesi",
    格尔峰电站: "Guel Dağı Güç İstasyonu",
    检测点091: "Muayene Noktası 091",
    妮娜奶奶的水果餐吧: "Nina Ninenin Lokantası",
    检测点384: "Muayene Noktası 384",
    矿镇: "Madenci Kasabası",
    翠湖游客中心: "Greenlake Ziyaretçi Merkezi",
    // Way of Winter - 雪国人生
    搁浅滩涂: "Karaya Oturmuş Çamurluklar", 
    海边旧屋: "Deniz Kenarı Kulübesi", 
    洞口营地: "Mağara Ağzı Kampı", 
    破败码头: "Metruk İskele", 
    幽谷民居: "Vadi Konutları", 
    废弃水塔: "Terk Edilmiş Su Kulesi", 
    瞭望处: "Gözetleme Yeri", 
    松林猎场: "Çam Av Sahası", 
    纵队前哨: "Gerilla Karakolu", 
    废弃避难所: "Terk Edilmiş Sığınak", 
    干涸码头: "Kurumuş Liman", 
    林场: "Orman", 
    潮间地农场: "Gelgit Bölgesi Çiftliği", 
    食品厂货栈: "Şeker Fabrikası Deposu", 
    悬索营地: "Kablolu Kamp", 
    栈道木屋: "Ahşap İskele Kulübesi", 
    废弃探险营地: "Terk Edilmiş Keşif Kampı", 
    悬索货栈: "Kablolu Depo", 
    荒废农庄: "Metruk Çiftlik", 
    鲸骨遗迹: "Balina Kemiği Kalıntıları", 
    瞭望点: "Gözetleme Noktası", 
    路边野餐: "Yol Kenarı Piknik Alanı", 
    古船农场: "Antik Gemi Çiftliği", 
    临时 investigation 营地: "Geçici Araştırma Kampı", 
    倒挂遗迹: "Ters Dönmüş Kalıntılar", 
    幽灵渔村: "Hayalet Koyu", 
    悬船冰洞: "Asılı Tekne Mağarası", 
    断桥: "Yıkık Köprü", 
    暖火营地: "Sıcak Ateş Kampı", 
    雪松小屋: "Sedir Kulübesi", 

    // Tecrit Siloları - 收容井
    "收容井-西格玛": "Tecrit Silosu - Sigma",
    "收容井-斐": "Tecrit Silosu - Phi",
    "收容井-暗狱": "Tecrit Silosu - EX1",
    "收容井-阿尔法": "Tecrit Silosu - Alpha",
    "收容井-寒境": "Tecrit Silosu - Psi",
    "收容井-西塔": "Tecrit Silosu - Theta",
    "收容井·塔乌": "Tecrit Silosu - 08",

    // Yarık Çıpaları - 位面锚 / 空间锚点
    // Way of Winter - 雪国人生
    "空间锚点·断桥": "Yarık Çıpası - Yıkık Köprü", 
    "空间锚点·“心愿奇境”": "Yarık Çıpası - Wishland Batı", 
    "空间锚点·慕斯市食品厂": "Yarık Çıpası - Moose Kasabası Şeker Fabrikası", 
    "空间锚点·慕斯市": "Yarık Çıpası - Moose Şehri", 
    "空间锚点·搁浅滩涂": "Yarık Çıpası - Karaya Oturmuş Bataklık", 
    "空间锚点·烟袋度假区": "Yarık Çıpası - Tütün Tatil Köyü", 
    "空间锚点·悬船冰洞": "Yarık Çıpası - Asılı Tekne Mağarası", 
    "空间锚点·菲斯库尔港": "Yarık Çıpası - Fiskur Limanı", 
    "空间锚点·“母巢”收容保护区": "Yarık Çıpası - Hiverail Yasak Bölgesi", 
    "空间锚点·黑石要塞": "Yarık Çıpası - Obsidyen Kampı", 
    "空间锚点·“大河”收容场": "Yarık Çıpası - Tayga Tecrit Merkezi", 
    "空间锚点·冻火湾": "Yarık Çıpası - Frost Forge (Donmuş Ocak)", 
    "空间锚点·“黑域”之门": "Yarık Çıpası - Pus Bölgesi Girişi", 
    "空间锚点·致命信号": "Yarık Çıpası - Ölümcül Sinyal", 
    "空间锚点·蛇腹洞穴": "Yarık Çıpası - Serap Mağarası",
    "空间锚点·蛇尾滑索营地": "Yarık Çıpası - Yılan Kuyruğu Zipline Kampı",
    "空间锚点·燃尽之地": "Yarık Çıpası - Kavrulmuş Çorak Topraklar",
    "空间锚点·废弃提炼厂": "Yarık Çıpası - Terk Edilmiş Rafineri",
    "空间锚点·火喉下城": "Yarık Çıpası - Firethroat Kalesi",
    "空间锚点·灰落市1": "Yarık Çıpası - Ashenton 1",
    "空间锚点·灰落市2": "Yarık Çıpası - Ashenton 2",
    "空间锚点·炎神研究所": "Yarık Çıpası - Ateş Tanrısı Araştırma Merkezi",
    "空间锚点·温泉民宿": "Yarık Çıpası - Kaplıca Hanı",
    "空间锚点·塔乌": "Yarık Çıpası - Tecrit Silosu 08",

    "武器箱【剧情箱子】": "Silah Kasası 【Hikaye】",

    // Seçkin Canavarlar - 精英怪
    暴食狂: "Glutton (Obur)",
    屠夫: "Arbiter (Yargıç)",
    裁决者: "Arbiter (Yargıç)",
    星尘簇: "Star Walker (Yıldız Gezgini)",
    门徒: "Disciple (Mürit)",
    雨壳: "Rainfall Reaper (Yağmur Azraili)",
    腐坏眼虫: "Claw Machine (Pençe Makinesi)", 
    娃娃机: "Claw Machine (Pençe Makinesi)", 
    抓娃娃机: "Claw Machine (Pençe Makinesi)", 
    唤生之母: "Mother of Life (Yaşam Anası)",
    唤生水母: "Mother of Life (Yaşam Anası)",
    熔烛: "Molten Candle (Eriyen Mum)",
    乐园向导: "Balloon Boy (Balonlu Çocuk)",
    夜魇: "Cervitaur",
    天气预报: "Weather Forecast (Hava Durumu Tahmini)",
    罪人守望: "Sinner Sentry (Günahkar Gözcüsü)",
    罗塞塔防暴员: "Rosetta Bruiser (Rosetta Fedaisi)",
    罗塞塔机械师: "Rosetta Mechanic (Rosetta Tamircisi)",
    罗塞塔重装员: "Rosetta Heavy (Ağır Rosetta Askeri)",
    // Sınırlı Süreli Etkinlikler
    这里没有迪斯科: "Disko Nereye Gitti?",
    湖之暗面: "Karanlık Yüz",
    挖通地狱: "Cehenneme Doğru Kaz",
    腐乐园: "Kayıp Cennet",
    喀戎行动: "Chiron Operasyonu",
    // Nişangahlar - 瞄具配件
    轻量化红点瞄具: "Hafif Kırmızı Nokta Nişangahı",
    战斗侦查瞄具: "Keşif Savaş Nişangahı",
    反射式瞄具: "Refleks Nişangahı",
    精准步枪瞄具: "Hassas Tüfek Dürbünü",
    战术全像瞄准镜: "Taktik Holografik Nişangah",
    精准光学瞄具: "Hassas Optik Nişangah",
    战术步枪瞄具: "Taktik Tüfek Dürbünü",
    轻型光学瞄具: "Hafif Optik Nişangah",
    中距离战术瞄具: "Orta Menzilli Taktik Nişangah",
    密封型反射式瞄具: "Sızdırmaz Refleks Nişangah",
    紧凑型反射式瞄具: "Kompakt Refleks Nişangah",
    棱镜式瞄具: "Prizmatik Nişangah",
    远距离战术瞄具: "Uzun Menzilli Taktik Nişangah",
    大型光学瞄具: "Büyük Optik Nişangah",
    紧固型微型红点瞄具: "Sabit Mini Refleks Nişangahı",
    微型红点瞄具: "Mini Kırmızı Nokta Nişangahı",
    先进战斗光学瞄具: "Gelişmiş Savaş Optik Dürbünü",
    全像瞄准镜: "Holografik Nişangah",
    // Namlu Parçaları - 枪口配件
    鱼鹰抑制器: "Osprey Susturucusu",
    集成型补偿器: "Entegre Kompanzatör",
    多用途霰弹枪抑制器: "Çok Amaçlı Pompalı Susturucusu",
    锤头型补偿器: "Çekiç Kafalı Kompanzatör",
    短型抑制器: "Kısa Susturucu",
    战术消焰器: "Taktik Alev Gizleyen",
    小型补偿器: "Küçük Kompanzatör",
    加长型制退器: "Uzatılmış Namlu Freni",
    一体式抑制器: "Entegre Susturucu",
    小型制退器: "Küçük Namlu Freni",
    一体式消焰器: "Entegre Alev Gizleyen",
    伪装用抑制器: "Kamuflaj Susturucusu",
    大型抑制器: "Büyük Susturucu",
    大型枪口制退器: "Büyük Namlu Freni",
    前向消焰器: "İleri Yönlü Alev Gizleyen",
    消焰器: "Alev Gizleyen",
    轻量化制退器: "Hafif Namlu Freni",
    基础抑制器: "Temel Susturucu",
    紧凑型制退器: "Kompakt Namlu Freni",
    霰弹枪制退器: "Pompalı Tüfek Freni",
    // Taktik Aksesuarlar - 战术配件
    小型红外指示器: "Mini Refleks, Küçük Kızılötesi Lazer",
    前护手握把: "Ön Koruyucu Kabza",
    后护手握把: "Arka Koruyucu Kabza",
    大型激光指示器: "Büyük Lazer Nişangahı",
    集成型激光指示器: "Entegre Lazer Nişangahı",
    角型握把: "Açılı Kabza",
    战术激光指示器: "Taktik Lazer Nişangahı",
    小型激光指示器: "Küçük Lazer Nişangahı",
    轻质前握把: "Hafif Ön Kabza",
    轻质水平握把: "Hafif Yatay Kabza",
    战术手电筒: "Taktik El Feneri",
    红外指示器: "Kızılötesi Gösterge",
    紧凑型红外指示器: "Kompakt Kızılötesi Gösterge",
    战术组合握把: "Taktik Kombinasyon Kabzası",
    眼镜蛇握把: "Kobra Kabza",
    垂直握把: "Dikey Kabza",
    紧凑型手电筒: "Kompakt El Feneri",
    激光指示器: "Lazer Nişangahı",
    折叠脚架: "Katlanır Çatal Ayak",
    // Şarjörler - 弹匣配件
    狙击枪战术弹匣: "Keskin Nişancı Taktik Şarjörü",
    轻机枪校准弹鼓: "LMG Kalibre Edilmiş Tambur Şarjörü",
    狙击枪改良弹匣: "Geliştirilmiş Keskin Nişancı Şarjörü",
    步枪轻量化弹匣: "Hafif Piyade Tüfeği Şarjörü",
    冲锋枪加重型弹匣: "Ağırlaştırılmış SMG Şarjörü",
    轻机枪大型弹鼓: "Büyük LMG Tambur Şarjörü",
    手枪战术型弹匣: "Taktik Tabanca Şarjörü",
    冲锋枪战术型弹匣: "Taktik SMG Şarjörü",
    步枪扩容弹匣: "Genişletilmiş Piyade Tüfeği Şarjörü",
    手枪加长型弹匣: "Uzatılmış Tabanca Şarjörü",
    手枪改良弹匣: "Geliştirilmiş Tabanca Şarjörü",
    冲锋枪改良弹匣: "Geliştirilmiş SMG Şarjörü",
    步枪改良弹匣: "Geliştirilmiş Piyade Tüfeği Şarjörü",
    // Bulmaca Türleri
    异常门扉: "Kapı Bulmacası",
    异常路牌: "Kırık Tabela Bulmacası",
    广告牌异常: "Kırık Tabela Bulmacası",
    破碎山石异常: "Kırılabilir Kaya",
    异常电话亭: "Telefon Kulübesi",
    异常雕像: "Heykel Bulmacası",
    黑水相机: "Kamera İfadesi Bulmacası",
    "诡谲画作: 小型制退器": "Küçük Namlu Freni (Gizemli Tablo gerekir)",
    "诡谲画作: 轻型光学瞄具": "Hafif Optik Nişangah (Gizemli Tablo gerekir)",
    "诡谲画作: 小型激光指示器": "Küçük Lazer Nişangahı (Gizemli Tablo gerekir)",
    "诡谲画作: 战术步枪瞄具": "Taktik Tüfek Dürbünü (Gizemli Tablo gerekir)",
    "诡谲画作: 前向消焰器": "İleri Yönlü Alev Gizleyen (Gizemli Tablo gerekir)",
    // Benzer İsimli Eklentiler
    战斗侦察瞄具: "Keşif Savaş Nişangahı",
    "反射式瞄具·黑色": "Refleks Nişangahı",
    角形握把: "Açılı Kabza",
    霰弹枪式制动器: "Pompalı Tüfek Freni",
    密封型反射瞄具: "Sızdırmaz Refleks Nişangah",
    "多用途霰弹枪抑制器(6226,-588)": "Çok Amaçlı Pompalı Susturucusu (6226,-588)", 
    "大型光学瞄具,黑心地带(3039,990)": "Büyük Optik Nişangah (3039,990)",
    "大型光学瞄具,黑心地带(3037,-979)": "Büyük Optik Nişangah (3037,-979)",
    手枪加强型弹匣: "Uzatılmış Tabanca Şarjörü",
    "诡谲画作：小型制退器": "Küçük Namlu Freni (Gizemli Tablo gerekir)",
    "诡谲画作：轻型光学瞄具": "Hafif Optik Nişangah (Gizemli Tablo gerekir)",
    "诡谲画作：小型激光指示器": "Küçük Lazer Nişangahı (Gizemli Tablo gerekir)",
    "诡谲画作：战术步枪瞄具": "Taktik Tüfek Dürbünü (Gizemli Tablo gerekir)",
    "诡谲画作：前向消焰器": "İleri Yönlü Alev Gizleyen (Gizemli Tablo gerekir)",
    "诡谲画作:战术步枪瞄具": "Taktik Tüfek Dürbünü (Gizemli Tablo gerekir)",
    // Eşya Kategorileri
    手枪: "Tabancalar",
    霰弹枪: "Pompalı Tüfekler",
    冲锋枪: "SMG'ler (Hafif Makineli Tüfekler)", 
    步枪: "Piyade Tüfekleri",
    狙击枪: "Keskin Nişancı Tüfekleri",
    轻机枪: "LMG'ler (Hafif Makineli Tüfekler)", 
    弓弩: "Arbaletler",
    重型火器: "Ağır Silahlar",
    刀剑: "Yakın Dövüş Silahları",
    头盔: "Kasklar",
    面部: "Maskeler", 
    上身: "Yelekler", 
    下身: "Pantolonlar", 
    手套: "Eldivenler",
    鞋子: "Ayakkabılar",
    瞄具配件: "Optikler",
    枪口配件: "Namlu Parçaları",
    战术配件: "Taktik Parçalar",
    弹匣配件: "Şarjörler",
    碎弹模组: "Parçalanma Modları",
    霜寒模组: "Donmuş Girdap Modları",
    爆弹模组: "İstikrarsız Bombacı Modları",
    电涌模组: "Aşırı Gerilim Modları",
    标记模组: "Boğa Gözü Modları",
    弹射模组: "Sekme Modları",
    快枪手模组: "Hızlı Silahşor Modları",
    灼烧模组: "Yanma Modları",
    阵地模组: "Kale Savaşı Modları",
    武器通用: "Silah Uyumlu Modlar", 
    头盔模组: "Kask Modları",
    面部模组: "Maske Modları", 
    上身模组: "Yelek Modları", 
    下身模组: "Pantolon Modları", 
    手套模组: "Eldiven Modları",
    鞋子模组: "Ayakkabı Modları",
    防具通用: "Zırh Uyumlu Modlar", 
    近战通用: "Yakın Dövüş Genel", 
    流派效果: "Tarz Etkisi", 
    模组后缀: "Mod Sonekleri", 
    元素伤害: "Elementel Hasar", 
    特殊子弹: "Özel Mermiler", 
    套装碎片: "Set Parçaları",
    素材: "Materyaller",
    近战蓝图: "Yakın Dövüş Silahı Şemaları",
    手枪蓝图: "Tabanca Şemaları",
    霰弹枪蓝图: "Pompalı Tüfek Şemaları",
    冲锋枪蓝图: "SMG Şemaları", 
    步枪蓝图: "Piyade Tüfeği Şemaları",
    狙击枪蓝图: "Keskin Nişancı Şemaları",
    轻机枪蓝图: "LMG Şemaları", 
    弓弩蓝图: "Arbalet Şemaları",
    家具配方: "Mobilya Şemaları",
    肉类: "Et",
    鱼类: "Balık",
    药草: "Şifalı Otlar",
    // Tarifler - 食谱
    "食谱：熏肉罗宋汤": "Tarif: Lüks Borç Çorbası",
    "食谱：畸变塔可卷": "Tarif: Tako", 
    "食谱：星尘茶": "Tarif: Yıldız Tozu Çayı",
    "食谱：培根肉排汉堡": "Tarif: Pastırmalı Burger",
    "食谱：南瓜星空派": "Tarif: Stargazy Turta",
    "食谱：消脂果汁": "Tarif: Yağ Yakıcı Meyve Suyu",
    "食谱：安全三明治": "Tarif: Güvenli Sandviç",
    "食谱：星尘水果罐头": "Tarif: Karışık Meyve Konservesi",
    "食谱：星尘通心粉罐头": "Tarif: Yıldız Tozu İtalyan Çorbası Konservesi",
    "食谱：奇迹茶": "Tarif: Mucize Çay",
    "食谱：碎裂面包": "Tarif: Parçalanmış Ekmek",
    "食谱：星尘南瓜泥沙拉": "Tarif: Yıldız Tozu Balkabağı Salatası",
    "食谱：幽光蘑菇罐头": "Tarif: Spektral Mantar Konservesi",
    "食谱：星尘炸肉": "Tarif: Karışık Kızarmış Sosis",
    "食谱：元宝饺子": "Tarif: Yuanbao Mantısı",
    "食谱：深海鱼片披萨": "Tarif: Stargazy Pizza",
    "食谱：炸薯条": "Tarif: Patates Kızartması",
    "食谱：反重力奶昔": "Tarif: Anti-Yerçekimi Milkshake",
    "食谱：金钱饼": "Tarif: Kroket",
    "食谱：特调冰酿": "Tarif: Özel Soğuk Kahve",
    "食谱:奇思妙想饮": "Tarif: İlginç Karışım",
    "食谱：炸鱼薯条": "Tarif: Fish & Chips",
    "食谱：幽灵饼干": "Tarif: Hayalet Kurabiye",
    "食谱：畸变带骨香肠": "Tarif: Kemikli Sapma Sosisi",
    "食谱：捕获之汤": "Tarif: Tecrit Çorbası",
    "食谱：蜜酿炖肉": "Tarif: Ballı Et Sote",
    // Sapmalar (Deviants) - 收容物
    远归之蝶: "Butterfly's Emissary (Kelebeğin Elçisi)",
    活体凝胶: "Festering Gel (Çürüyen Jel)",
    荣枯种子: "Harveseed (Hasat Tohumu)",
    捕梦网: "Dreamcatcher (Düş Kapanı)",
    低语亡骨: "Canine Skull (Köpek Kafatası)",
    电鳗: "Electric Eel (Elektrikli Yılan Balığı)",
    迪斯科球: "Disco Ball (Disko Topu)",
    发条青蛙: "Frog the Leaper (Zıpzıp Kurbağa)",
    极寒水母: "Polar Jelly (Kutup Denizanası)",
    青龙: "Chefosaurus",
    蜂团团: "Buzzy Bee (Çalışkan Arı)",
    工号37: "H37",
    姜饼屋: "Gingerbread House (Zencefilli Ev)",
    核子打火机: "Atomic Lighter (Atomik Çakmak)",
    凝视的黑猫: "Enchanted Void (Büyülü Boşluk)",
    木工河狸: "Logging Beaver (Oduncu Kunduz)",
    空间魔方: "Space Turner (Uzay Döndürücü)",
    元素小子: "Digby Boy (Madenci Çocuk)",
    雪景球: "Snow Globe (Kar Küresi)",
    上界之卵: "Upper World Spawn (Üst Dünya Yumurtası)",
    庞然大菇: "Growshroom (Büyük Mantar)",
    皆斩: "Zeno-Purifier",
    门扉: "Strange Door (Tuhaf Kapı)",
    巫毒娃娃: "Voodoo Doll (Voodoo Bebeği)",
    炎之精: "Flame Essence (Ateş Özü)",
    破碎少女: "Shattered Maiden (Kırık Kız)",
    迷你奇点: "Mini Wonder (Küçük Mucize)",
    异维大猫: "Extradimensional Cat (Boyutlararası Kedi)",
    球状闪电: "Orb Lightning (Küre Yıldırım)",
    迷你黄衣: "Mini Feaster",
    小纸人: "Paper Doll (Kağıt Bebek)",
    愿望先生: "Mr. Wish",
    红龙: "Pyro Dino",
    熊医生: "Dr. Teddy",
    恶臭球根: "Grumpy Bulb (Aksi Yumru)",
    空之子: "By-The-Wind (Rüzgarla Gelen)",
    胡桃夹子: "Nutcracker (Fındıkkıran)",
    蝶之梦: "Rebecca",
    气球狗: "Pup Buddy (Balon Köpek)",
    一碗美味: "Hug-In-A-Bowl (Kasedeki Lezzet)",
    // Gizemli Tablolar
    "诡谲画作·代顿湿地": "Gizemli Tablo · Dayton Sulak Alanları",
    "诡谲画作·破碎三角洲": "Gizemli Tablo · Kırık Delta",
    "诡谲画作·铁锈河": "Gizemli Tablo · Paslı Nehir",
    "诡谲画作·垩峰山": "Gizemli Tablo · Chalk Zirvesi",
    "诡谲画作·孤狼荒原": "Gizemli Tablo · Kızıl Kumlar",
    "诡谲画作·黑心地带": "Gizemli Tablo · Kara Kalp",
    // Madenler
    硫磺: "Kükürt",
    铜矿: "Bakır Cevheri",
    锡矿: "Kalay Cevheri",
    锡矿富集区: "Yoğun Kalay Bölgesi",
    铁矿: "Demir Cevheri",
    铝矿: "Alüminyum Cevheri",
    钨矿: "Tungsten Cevheri",
    银矿: "Gümüş Cevheri",
    银矿区域: "Gümüş Maden Alanı",
    "银矿(稀有)": "Gümüş Cevheri (Rastgele)",
    "银矿 (稀有)": "Gümüş Cevheri (Rastgele)",
    金矿: "Altın Cevheri",
    金矿区域: "Altın Maden Alanı",
    "金矿(稀有)": "Altın Cevheri (Rastgele)",
    "金矿 (稀有)": "Altın Cevheri (Rastgele)",
    "金矿（先锋服)": "Altın Madeni",
    星尘矿: "Yıldız Tozu Cevheri",
    星尘矿石: "Yıldız Tozu Cevheri",
    星尘矿区: "Yıldız Tozu Maden Alanı",
    星尘矿区域: "Yıldız Tozu Maden Alanı",
    "星尘矿(稀有)": "Yıldız Tozu Cevheri (Rastgele)",
    "星尘矿 (稀有)": "Yıldız Tozu Cevheri (Rastgele)",
    // Bitkiler / Meyve / Sebze
    橘子: "Portakal",
    果蔬篮橘子: "Sepetteki Portakallar",
    小麦: "Buğday",
    果蔬篮小麦: "Sepetteki Buğdaylar",
    红色浆果: "Alıç Meyvesi",
    卷心菜: "Lahana",
    果蔬篮卷心菜: "Sepetteki Lahanalar",
    甜菜: "Pancar",
    果蔬篮甜菜: "Sepetteki Pancarlar",
    蓝莓: "Yaban Mersini",
    南瓜: "Balkabağı",
    果蔬篮南瓜: "Sepetteki Balkabakları",
    玉米: "Mısır",
    果蔬篮玉米: "Sepetteki Mısırlar",
    土豆: "Patates",
    果蔬篮土豆: "Sepetteki Patatesler",
    蘑菇: "Mantar",
    果蔬篮蘑菇: "Sepetteki Mantarlar",
    火刺果: "Spikemato", 
    阳姜: "Sunny Ginger", 
    薄荷: "Nane", 
    雪茸: "Snow Fungus (Kar Mantarı)", 
    芦荟: "Aloe Vera",
    "鼠尾草 * 5": "Adaçayı * 5",
    "鼠尾草 * 8": "Adaçayı * 8",
    实时: "Çan Çiçeği",
    金银花: "Hanımeli",
    "金银花 * 3": "Hanımeli * 3",
    "金银花 * 4": "Hanımeli * 4",
    藏红花: "Safran",
    血菖蒲: "Kızıl Eğir Otu",
    紫锥菊: "Ekinezya",
    黄莲花: "Sarı Nilüfer",
    苹果: "Elma",
    苹果树: "Elma Ağacı",
    "苹果树 * 2": "Elma Ağacı * 2",
    葡萄: "Üzüm",
    贝壳岩石: "Kabuklu Kaya",
    海草岩石: "Yosunlu Kaya",
    观赏性花海: "Çiçek Denizi",
    香蕉树: "Muz Ağacı",
    "香蕉树 * 2": "Muz Ağacı * 2",
    "香蕉树 * 4": "Muz Ağacı * 4",
    "香蕉树 * 6": "Muz Ağacı * 6",
    "香蕉树 * 7": "Muz Ağacı * 7",
    椰子树: "Hindistan Cevizi Ağacı",
    "椰子树 * 3": "Hindistan Cevizi Ağacı * 3",
    巨木: "Dev Ağaç",
    "龙血树(巨木)": "Dev Ejder Ağacı",
    // Hayvanlar
    野生动物: "Yaban Hayatı",
    兔子窝: "Tavşan Yuvası",
    鹿: "Geyik",
    星蚀鹿群: "Geyik Sürüsü",
    星蚀雄鹿: "Erkek Geyik",
    星蚀雌鹿: "Dişi Geyik",
    野猪: "Yaban Domuzu",
    野猪群: "Yaban Domuzu Sürüsü",
    星蚀鳄: "Aligatör",
    羊群: "Koyun Sürüsü",
    花豹: "Leopar",
    星蚀熊窝: "Ayı İni",
    星蚀熊: "Ayı",
    肉排: "Biftek",
    鳄鱼蛋: "Timsah Yumurtası",
    鸟蛋: "Kuş Yumurtası",
    // Petrol Kuyuları
    原油油井: "Ham Petrol Kuyusu",
    // Harita İpuçları
    别靠近箱子: "Taklitçi Kasa (Mimic)",
    地堡门禁卡: "Sığınak Erişim Kartı",
    吓人箱子: "Taklitçi Kasa (Mimic)",
    空间异动: "Uzay Anomalisi",
    地下入口: "Yer Altı Girişi",
    电话亭: "Telefon Kulübesi",
    拟态怪储物箱: "Taklitçi Depo",
    拟态宝箱怪: "Taklitçi Kasa (Mimic)",
    "密码: 5897": "Şifre: 5897",
    "密码: 325": "Şifre: 325",
    地下通道入口: "Yer Altı Geçidi Girişi",
    地下通道最近入口: "En Yakın Yer Altı Geçidi Girişi",
    地窖入口: "Mahzen Girişi",
    山洞入口: "Mağara Girişi",
    溶洞入口: "Karstik Mağara Girişi",
    镜女: "Ayna Düşmanı",
    拟态储物箱别开: "Açma! Taklitçi Depo",
    "电梯：负一层": "Asansör: Yer Altı Kat 1",
    拟态宝箱怪别开: "Açma! Taklitçi Kasa",
    空间异常: "Uzay Anomalisi",
    "5层楼梯": "5. Kat Merdivenleri",
    箱子怪别开: "Açma! Taklitçi Kasa",
    下楼电梯: "Aşağı İnen Asansör",
    下楼电梯位置: "Aşağı İnen Asansör Konumu",
    隐藏宝箱最后位置: "Gizli Kasa Son Konumu",
    抽屉柜: "Çekmeceli Dolap",
    混合矿场: "Karışık Maden Alanı",
    // Gizli ve Yan Görevler
    隐藏的宝箱: "Morfik Kasa Eğitimi", 
    玩具小熊: "Çocukluğun Çağrısı",
    "急救！急救！": "Dayton Hastanesi Acil",
    信徒的藏宝图: "Delilikte Kaybolmak - Başlangıç",
    信徒的财产箱: "Delilikte Kaybolmak - Hazine Konumu",
    检测点见闻: "Bir Muayene Noktasının Taslağı",
    红与黑: "Kıyamet Karnavalı",
    被丢弃的玩偶: "Anna'nın Oyuncakları",
    艺术家的钥匙: "Kült Toplantısı - Başlangıç",
    信徒的宝箱: "Kült Toplantısı - Hazine Konumu",
    特别关系: "Özel Bir İlişki",
    生日快乐: "Doğum Günün Kutlu Olsun",
    农庄惊魂: "Çiftlik Korkusu",
    限定版牛奶: "Sınırlı Üretim Süt",
    考古学家的馈赠: "Ölüme Kadar Sadık",
    遗留财产: "Bir Aile Mirası",
    悲伤画像: "Kederli Portre",
    "密码：9274": "Şifre: 9274", 
    秘密配方: "Gizli Tarif", 
    // Tüccarlar
    韦伯: "Weber",
    赵金潭: "Zhao Jintan",
    拟态体商店: "Severin VII-S2041 (SIRA Tüccarı)",
    鱼饵商人: "Margerie (Balık Tüccarı)",
    "鱼饵商人【霜之白班钩鱼蓝图兑换处】": "Margerie 【Balık Şemaları】",
    // Yaşanabilir Alan Bilgileri
    异常点: "Anormal Nesne",
    稀有: "Nadir",
    持续刷新: "Sürekli Yenilenir",
    碧湖山庄: "Greenlake Villaları",
    检测点91: "Muayene Noktası 91",
    戴维思角: "Davis Noktası",
    检测点24: "Muayene Noktası 24",
    翻车鱼岛游客中心: "Mola Adası Ziyaretçi Merkezi",
    治炼厂污染点: "Rafineri Kirlilik Alanı",
    检测点3711: "Muayene Noktası 3711",
    翠湖山镇: "Greenlake Tepesi Kasabası",
    无蘑菇: "Mantar Yok",
    果蔬箱土豆: "Patates",
    油田区域: "Petrol Sahası Bölgesi",
    抽水泵采集: "Su Pompası",
    洞穴内: "Mağara İçi",
    便携式燃油: "Taşınabilir Yakıt",
    腐化熊: "Yozlaşmış Ayı",
    水豚: "Kapibara",
    狼: "Kurt",
    鳄鱼: "Timsah",
    长嘴海鸥: "Uzun Gagalı Martı",
    海龟: "Deniz Kaplumbağası",
    鹈鹕: "Pelikan",
    兔子: "Tavşan",
    鳄龟: "Kapan Kaplumbağası",
    狐狸: "Tilki",
    浣熊: "Rakun",
    火烈鸟: "Flama",
    腐化鳄: "Yozlaşmış Timsah",
    腐化狼: "Yozlaşmış Kurt",
    白斑狗鱼钓鱼点: "Turna Balığı Av Noktası",
    白斑狗鱼: "Turna Balığı",
    海鲈鱼: "Deniz Levreği",
    神仙鱼: "Melek Balığı",
    长吻雀鳝: "Kemikli Turna",
    黑鲈: "Kara Levrek",
    孔雀鱼: "Lepistes",
    鲤鱼: "Sazan",
    图丽鱼: "Astronot Balığı",
    太阳鱼: "Güneş Balığı",
    锦鲤: "Koi Balığı",
    龙鱼: "Arowana (Ejder Balığı)",
    鳙鱼: "Koca kafa Sazan",
    沙丁鱼: "Sardalya",
    梭鱼: "Barakuda",
    鲭鱼: "Uskumru",
    罗非鱼: "Tilapya",
    虹鳟: "Gökkuşağı Alabalığı",
    鲑鱼: "Somon",
    鲳鲹: "Pompano",
    松鼠: "Sincap",
    亚口鱼: "Yalancı Sazan",
    // Senaryolar
    "PvE-天空之触": "PvE - MANIBUS (Gökyüzünün Dokunuşu)",
    "PvP-分歧之路": "PvP - Evolution's Call (Evrimin Çağrısı)",
    "PvP-逆位战争": "PvP - Prismverse's Clash (Prizma Savaşı)", 
    "PvE-雪国人生": "PvE - Way of Winter (Kışın Yolu)", 
    // Harita Genel
    玩家: "Oyuncu",
    私有收容仓: "Kişisel Tecrit Ünitesi",
    出生点: "Doğuş Noktası",
    "观景点：雪崩巨楔": "Manzara Noktası: Çığ Monoliti",
    "观景点：菲斯库尔港": "Manzara Noktası: Fiskur Limanı",
    "观景点：熊栖雪场": "Manzara Noktası: Ayı İni",
    "观景点：母巢": "Manzara Noktası: Hiverail",
    "观景点：白崖黑域": "Manzara Noktası: Beyaz Uçurum Kara Sektörü",
    "观景点：心愿奇境西园": "Manzara Noktası: Wishland - Batı",
    "观景点：荒原巨骨": "Manzara Noktası: Çorak Toprak Kafatası",
    "观景点：冻火湾": "Manzara Noktası: Donmuş Ocak Koyu",
    "观景点：巨岩": "Manzara Noktası: Dev Kaya",
    "观景点：鲸骨乡": "Manzara Noktası: Balina Kemiği",
    "观景点：“大河”收容场": "Manzara Noktası: TAYGA Tecrit Merkezi",
    "观景点：搁浅船只": "Manzara Noktası: Karaya Oturmuş Gemi",
    "观景点：慕斯市食品厂": "Manzara Noktası: Moose Kasabası Şeker Fabrikası",
    "观景点：冻原巨楔": "Manzara Noktası: Tundra Monoliti",
    "观景点：慕斯市": "Manzara Noktası: Moose Şehri",
    "观景点：心愿奇境东园": "Manzara Noktası: Wishland Doğu Parkı",
    "观景点：黑石要塞": "Manzara Noktası: Karataş Kalesi",
    "观景点：绚烂花海": "Manzara Noktası: Çiçek Bahçeleri",
    "观景点：冰屋营地": "Manzara Noktası: İglo Kampı",
    "观景点：炎神实验室": "Manzara Noktası: Ateş Tanrısı Araştırma Merkezi",
    "观景点：不落号坠落点": "Manzara Noktası: Unfallen Enkaz Alanı",
    "观景点：收容井塔乌": "Manzara Noktası: Tecrit Silosu Taurus",
    "观景点：火喉下城": "Manzara Noktası: Firethroat Kalesi",
    "观景点：炽尘巨楔": "Manzara Noktası: Köz Tozu Monoliti",
    "观景点：火喉圣域": "Manzara Noktası: Firethroat Kutsal Alanı",
    "观景点：月牙湖": "Manzara Noktası: Hilal Gölü",
    "观景点：灰落": "Manzara Noktası: Ashenton (Kül Kasabası)",
    "观景点：影日洞穴": "Manzara Noktası: Günes Siperi Mağarası",
    "观景点：遗忘之地": "Manzara Noktası: Unutulmuş Topraklar",
    "荒废农庄": "Metruk Çiftlik",
    "空间锚点·废弃矿洞二层": "Yarık Çıpası - Terk Edilmiş Maden Kat 2",
    "收容井-德尔塔": "Tecrit Silosu - Delta",
    电梯: "Asansör",
    乖乖兔: "Fetch-A-Lot Bunny (Uysal Tavşan)",
    "食谱：黄油松茸": "Tarif: Tereyağlı Matsutake Mantarı",
    "食谱：硬邦邦姜糖": "Tarif: Zencefil Şekeri",
    "食谱：蜜蛋弹弹乐": "Tarif: Zencefilli Atıştırmalık",
    "食谱：雪茸蛋炒饭": "Tarif: Kar Mantarlı Yumurtalı Pilav",
    "食谱：水果派": "Tarif: Karışık Meyveli Turta",
    "食谱：噼里啪啦南瓜汤": "Tarif: Patlayan Balkabağı Çorbası",
    "食谱：炙热炖肉火锅": "Tarif: Doyurucu Et Güveç",
    "食谱：鲜肉咖喱饭": "Tarif: Köri ve Pilav",
    "食谱：砰砰爆米花": "Tarif: Patlamış Mısır",
    "食谱：水果蛋糕": "Tarif: Meyveli Pasta",
    "食谱：炙热烈焰蛋挞": "Tarif: Alevli Yumurtalı Tart",
    "食谱：麻辣兔丁罐头": "Tarif: Acılı Tavşan Eti Konservesi",
    "食谱：清凉薄荷肉罐头": "Tarif: Naneli Et Konservesi",
    宝箱怪位置待定: "Morfik Kasa Konumu Belirlenmedi",
    "气球异常：轻量化红点瞄具": "Balon Anomalisi: Hafif Kırmızı Nokta Nişangahı",
    "玩偶异常：戍卫前握把": "Oyuncak Anomalisi: Muhafız Ön Kabzası",
    "凝石异常：斜切握把": "Taş Anomalisi: Açılı Kabza",
    "凝石异常：远射补偿器": "Taş Anomalisi: Uzun Menzilli Kompanzatör",
    "凝石异常：小型补偿器": "Taş Anomalisi: Küçük Kompanzatör",
    "冰块宝箱：轻型光学瞄具": "Buz Kasası: Hafif Optik Nişangah",
    "冰块宝箱：手枪加长型弹匣": "Buz Kasası: Uzatılmış Tabanca Şarjörü",
    "冰块宝箱：步枪扩容弹匣": "Buz Kasası: Genişletilmiş Piyade Tüfeği Şarjörü",
    "凝石异常：轻型握把": "Taş Anomalisi: Hafif Kabza",
    "冰块宝箱：冲锋枪加重型弹匣": "Buz Kasası: Ağırlaştırılmış SMG Şarjörü",
    "凝石异常：隐秘抑制器": "Taş Anomalisi: Gizli Susturucu",
    "冰块宝箱：轻机枪大型弹鼓": "Buz Kasası: Büyük LMG Şarjör Tamburu",
    "凝石异常：一体式消焰器": "Taş Anomalisi: Entegre Alev Gizleyen",
    "冰块宝箱：手枪战术型弹匣": "Buz Kasası: Taktik Tabanca Şarjörü",
    "凝石异常：冲锋枪战术型弹匣": "Taş Anomalisi: Taktik SMG Şarjörü",
    "凝石异常：奇袭制退器": "Taş Anomalisi: Baskın Namlu Freni",
    "凝石异常：步枪轻量化弹匣": "Taş Anomalisi: Hafif Piyade Tüfeği Şarjörü",
    "凝石异常：密封型反射式瞄具": "Taş Anomalisi: Sızdırmaz Refleks Nişangah",
    "气球异常：消焰器": "Balon Anomalisi: Alev Gizleyen",
    "气球异常：小型制退器": "Balon Anomalisi: Küçük Namlu Freni",
    "冰块宝箱：狙击枪战术弹匣": "Buz Kasası: Taktik Keskin Nişancı Şarjörü",
    "脚印异常：精准步枪瞄具": "Ayak İzi Anomalisi: Hassas Tüfek Dürbünü",
    "气球异常：狙击枪改良弹匣": "Balon Anomalisi: Geliştirilmiş Keskin Nişancı Şarjörü",
    "气球异常：小型红外指示器": "Balon Anomalisi: Küçük Kızılötesi Lazer",
    "气球异常：垂直握把": "Balon Anomalisi: Dikey Kabza",
    "松鼠异常：棕熊反射式瞄具": "Sincap Anomalisi: Bozayı Refleks Nişangahı",
    观景台: "Seyir Terası",
    气球异常: "Balon Anomalisi",
    玩偶异常: "Oyuncak Anomalisi",
    冰块宝箱: "Buz Kasası",
    冷晶矿: "Soğuk Kristal Cevheri",
    冰晶矿: "Soğuk Kristal Cevheri",
    热岩矿: "Sıcak Kaya Cevheri",
    寒冰瓜: "Buz Kavunu",
    乌鸦蛋: "Karga Yumurtası",
    极地椒: "Kutup Biberi",
    "极地椒 * 3": "Kutup Biberi * 3",
    驯鹿: "Ren Geyiği",
    野牛: "Bizon",
    海豹: "Mühür",
    母羊: "Dişi Koyun",
    公羊: "Koç",
    北极狐: "Kutup Tilkisi",
    北极熊: "Kutup Ayısı",
    熊: "Ayı",
    预兆宝箱: "Ay Kehaneti Kasaları",
    代顿检测点传送塔: "Dayton Denetim Noktası Işınlanma Kulesi",
    内海传送塔: "İç Deniz Işınlanma Kulesi",
    "金银花*8": "Hanımeli*8",
    上位者的影响使星尘污染浓度上升: "Kirli Bölge (Üstün Varlık Etkisi)",
    这里的星尘污染浓度似乎很高: "Kirli Bölge (Yüksek Yıldız Tozu Yoğunluğu)",
    黑湖中不断溢出星尘污染: "Kirli Bölge (Kara Göl Sızıntısı)",
    矿井内似乎不断溢出星尘污染: "Kirli Bölge (Maden Ocağı Sızıntısı)",
    溢出的污染不断侵蚀着这片土地: "Kirli Bölge (Yayılan Kirlilik)",
    狂信者的祝祷召唤出肆虐的污染: "Kirli Bölge (Mürit Ayini Yoğunluğu)",
    源质挥发使星尘污染浓度上升: "Kirli Bölge (Uçucu Element Etkisi)",
    山壁内源源不断渗出星尘污染: "Kirli Bölge (Kaya Sızıntısı)",
    鳄龟蛋: "Kapan Kaplumbağası Yumurtası",
    "PvE-无尽长梦": "PvE - Endless Dream (Sonsuz Rüya)",
    无尽长梦: "Sonsuz Rüya",
    "PvP-禁区": "PvP - RaidZone (Baskın Bölgesi)",
    "七日世界：禁区": "OnceHuman: Baskın Bölgesi",
    异常物纪元: "Sapma Çağı",
    "PvE-异常物纪元": "PvE - Era of Deviations (Sapma Çağı)",
    贸易区: "Oyuncu Pazarı",
    月之幽影: "Ay Gölgesi",
    月兆精英怪: "Ay Kehaneti Seçkin Canavarı",
    豹子: "Leopar",
    龙血树: "Ejder Ağacı",
    古老者的试炼: "Kadim Olanın Sınavı",
    超异常体: "Süper Anomali",
    星临宝箱: "Yıldız Düşüşü Kasası",
    不稳定聚合体: "İstikrarsız Kümeleşme",
    引力异化精英怪: "Yıldız Düşüşü Seçkin Canavarı",
    剧情笔记: "Hikaye Notları",
    金色垃圾: "Altın Çöp",
    浅眠记录: "Hafif Uyku Kaydı",
    深眠记录: "Derin Uyku Kaydı",
    永眠记录: "Ebedi Uyku Kaydı",
    噩梦记录: "Kabus Tüpü",
    梦域商人: "Bayan Hafıza (Miss Memory)",
    梦域追迹箱: "Rüya Bölgesi Takip Kutusu",
    清醒时钟: "Uyanıklık Saati",
    野生装备台: "Doğal Teçhizat Tezgahı",
    野生工艺台: "Doğal Üretim Tezgahı",
    野生车辆: "Araç Enkazı",
    野生商人: "Gezgin Tüccar",
    矿石: "Madenler",
    植物: "Bitkiler",
    动物: "Hayvanlar",
    蔬菜: "Sebzeler",
    草药: "Şifalı Otlar",
    油田: "Petrol Sahası",
    "远归之蝶 (15级)": "Kelebeğin Elçisi (Sev. 15)",
    "远归之蝶 (22级)": "Kelebeğin Elçisi (Sev. 22)",
    "远归之蝶 (28级)": "Kelebeğin Elçisi (Sev. 28)",
    "远归之蝶 (37级)": "Kelebeğin Elçisi (Sev. 37)",
    "元素小子 (B级)": "Madenci Çocuk (B)",
    "元素小子 (5级)": "Madenci Çocuk (Sev. 5)",
    "元素小子 (15级)": "Madenci Çocuk (Sev. 15)",
    "元素小子 (22级)": "Madenci Çocuk (Sev. 22)",
    "元素小子 (25级)": "Madenci Çocuk (Sev. 25)",
    "元素小子 (28级)": "Madenci Çocuk (Sev. 28)",
    "元素小子 (43级)": "Madenci Çocuk (Sev. 43)",
    "元素小子 (45级)": "Madenci Çocuk (Sev. 45)",
    "夺命兔 (B)": "Ölümcül Tavşan (B)",
    "夺命兔 (15级)": "Ölümcül Tavşan (Sev. 15)",
    "夺命兔 (40级)": "Ölümcül Tavşan (Sev. 40)",
    "夺命兔 (45级)": "Ölümcül Tavşan (Sev. 45)",
    "乖乖兔 (B)": "Uysal Tavşan (B)",
    "永恒烈阳 (A)": "Yenilmez Güneş (A)",
    "派对猴 (B)": "Parti Maymunu (B)",
    "庞然大菇 (5级)": "Büyük Mantar (Sev. 5)",
    "庞然大菇 (22级)": "Büyük Mantar (Sev. 22)",
    "庞然大菇(22级)": "Büyük Mantar (Sev. 22)",
    "庞然大菇 (40级)": "Büyük Mantar (Sev. 40)",
    "庞然大菇 (43级)": "Büyük Mantar (Sev. 43)",
    "庞然大菇 (45级)": "Büyük Mantar (Sev. 45)",
    "量子蜗牛 (5级)": "Atomik Salyangoz (Sev. 5)",
    "量子蜗牛 (15级)": "Atomik Salyangoz (Sev. 15)",
    "量子蜗牛 (22级)": "Atomik Salyangoz (Sev. 22)",
    "量子蜗牛 (28级)": "Atomik Salyangoz (Sev. 28)",
    "量子蜗牛 (35级)": "Atomik Salyangoz (Sev. 35)",
    "低语孤狼 (5级)": "Yalnız Kurdun Fısıltısı (Sev. 5)",
    "低语孤狼 (15级)": "Yalnız Kurdun Fısıltısı (Sev. 15)",
    "低语孤狼 (22级)": "Yalnız Kurdun Fısıltısı (Sev. 22)",
    "低语孤狼 (28级)": "Yalnız Kurdun Fısıltısı (Sev. 28)",
    "蜂团团 (5级)": "Çalışkan Arı (Sev. 5)",
    "蜂团团 (22级)": "Çalışkan Arı (Sev. 22)",
    "蜂团团 (43级)": "Çalışkan Arı (Sev. 43)",
    "蜂团团 (45级)": "Çalışkan Arı (Sev. 45)",
    "永恒烈阳 (27级)": "Yenilmez Güneş (Sev. 27)",
    "迪斯科球  (27级)": "Disko Topu (Sev. 27)",
    "迪斯科球(27级)": "Disko Topu (Sev. 27)",
    "迪斯科球 (B)": "Disko Topu (B)",
    "电鳗  (27级)": "Elektrikli Yılan Balığı (Sev. 27)",
    "电鳗 (B)": "Elektrikli Yılan Balığı (B)",
    "活性凝胶 (B)": "Çürüyen Jel (B)",
    "活性凝胶 (25级)": "Çürüyen Jel (Sev. 25)",
    "小纸人 (B)": "Kağıt Bebek (B)",
    "核子打火机 (A)": "Atomik Çakmak (A)",
    "捕梦网 (B)": "Düş Kapanı (B)",
    "熊医生 (A)": "Dr. Teddy (A)",
    "工号37 (A)": "H37 (A)",
    "雨人 (15级)": "Yağmur Adam (Sev. 15)",
    "雨人 (28级)": "Yağmur Adam (Sev. 28)",
    "雨人 (37级)": "Yağmur Adam (Sev. 37)",
    "雨人 (40级)": "Yağmur Adam (Sev. 40)",
    "雨人 (45级)": "Yağmur Adam (Sev. 45)",
    "气球狗 (A)": "Balon Köpek (A)",
    "发条青蛙 (5级)": "Zıpzıp Kurbağa (Sev. 5)",
    "发条青蛙 (22级)": "Zıpzıp Kurbağa (Sev. 22)",
    "发条青蛙 (28级)": "Zıpzıp Kurbağa (Sev. 28)",
    "发条青蛙 (43级)": "Zıpzıp Kurbağa (Sev. 43)",
    "恶咒娃娃 (A)": "Voodoo Bebeği (A)",
    "破碎少女 (B)": "Kırık Kız (B)",
    "空间魔方 (A)": "Uzay Döndürücü (A)",
    "联合体 (B)": "Masonik Piramit (B)",
    "木工河狸 (B)": "Oduncu Kunduz (B)",
    "木工河狸 (15级)": "Oduncu Kunduz (Sev. 15)",
    "木工河狸 (22级)": "Oduncu Kunduz (Sev. 22)",
    "木工河狸 (28级)": "Oduncu Kunduz (Sev. 28)",
    "木工河狸 (45级)": "Oduncu Kunduz (Sev. 45)",
    "庞然大菇 (28级)": "Büyük Mantar (Sev. 28)",
    "炎之精 (22级)": "Ateş Özü (Sev. 22)",
    "炎之精 (25级)": "Ateş Özü (Sev. 25)",
    "炎之精 (28级)": "Ateş Özü (Sev. 28)",
    "空之子 (22级)": "Rüzgarla Gelen (Sev. 22)",
    "空之子 (43级)": "Rüzgarla Gelen (Sev. 43)",
    "极寒水母 (22级)": "Kutup Denizanası (Sev. 22)",
    "极寒水母 (37级)": "Kutup Denizanası (Sev. 37)",
    "极寒水母 (40级)": "Kutup Denizanası (Sev. 40)",
    "极寒水母 (43级)": "Kutup Denizanası (Sev. 43)",
    "极寒水母 (45级)": "Kutup Denizanası (Sev. 45)",
    "胡桃夹子 (A)": "Fındıkkıran (A)",
    "雪景球 (B)": "Kar Küresi (B)",
    "雪景球 (35级)": "Kar Küresi (Sev. 35)",
    "姜饼屋 (A)": "Zencefilli Ev (A)",
    "快照 (A)": "Şipşak Kamera (A)",
    "冰之瓶 (B)": "Buz Kavanozu (B)",
    "门扉 (S)": "Tuhaf Kapı (S)",
    "鱼航员 (43级)": "Balık Astronot (Sev. 43)",
    "鱼航员 (45级)": "Balık Astronot (Sev. 45)",
    "鲸狗 (5级)": "Balina Köpek (Sev. 5)",
    "鲸狗 (22级)": "Balina Köpek (Sev. 22)",
    "鲸狗 (28级)": "Balina Köpek (Sev. 28)",
    "狐主任 (15级)": "Müdür Tilki (Sev. 15)",
    "狐主任 (22级)": "Müdür Tilki (Sev. 22)",
    "狐主任 (28级)": "Müdür Tilki (Sev. 28)",
    "狐主任 (37级)": "Müdür Tilki (Sev. 37)",
    "狐主任 (45级)": "Müdür Tilki (Sev. 45)",
    "焦油布丁 (22级)": "Katran Pudingi (Sev. 22)",
    "唤生灵 (37级)": "Ruh Çağıran (Sev. 37)",
    三角原传送塔: "Işınlanma Kulesi",
    油田北部传送塔: "Işınlanma Kulesi",
    秽水工业区: "Bulanık Su Endüstri Bölgesi",
    铁锈河下游: "Paslı Nehir Aşağı Havzası",
    铁锈河上游: "Paslı Nehir Yukarı Havzası",
    黑原地区: "Blackfell Bölgesi",
    黑原北部: "Kuzey Blackfell",
    黑原西部: "Batı Blackfell",
    黑石山脉: "Karataş Dağları",
    阿克姆山脉: "Arkam Dağları",
    冰屋湾: "İglo Koyu",
    乐园腹地: "Cennet İç Bölgeleri",
    不冻港地区: "Donmayan Liman Bölgesi",
    乐园岛: "Cennet Adası",
    金宝箱: "Altın Ganimet Kasası",
    银宝箱: "Gümüş Ganimet Kasası",
    金属抽屉柜: "Metal Çekmece Dolabı",
    车后备箱: "Araba Bagajı",
    垃圾箱: "Çöp Kutusu",
    蛮荒地带: "Vahşi Sapma Bölgesi",
    幻境地带: "Yansıma Sapma Bölgesi",
    虚实地带: "Yanılsama Sapma Bölgesi",
    文明遗产: "Kültürel Eserler"
  },
};