export default {
    "buttons": {
        "filter": "筛选标记",
        "select_all": "全选",
        "deselect_all": "全不选",
        "close": "关闭",
        "move_left": "左移",
        "move_right": "右移"
    },
    "tabs": {
        "by_category": "分类",
        "by_item": "物品",
        "by_search": "搜索",
        "resource_list": "资源",
        "setting": "设置",
        "user_data": "数据管理",
        "quick_setting": "快捷设置",
        "quick_setting_resource": "资源密集区",
        "quick_setting_bus_route": "怪物巴士路线",
        "area": "地点区域",
        "treasure": "宝箱密藏",
        "monster": "事件怪物",
        "collection": "收集要素",
        "hint": "地图提示",
        "logged": "已登录",
        "guest": "未登录",
        "oneclick_delete_enable": "一键删除",
        "oneclick_delete_disable": "关闭一键",
        "oneclick_delete_badge": "已开启一键删除",
        "oneclick_delete_hint1": "开启后，点击标记不再显示弹窗，而是直接删除或恢复标记。",
        "oneclick_delete_enable_hint": "已开启一键删除模式",
        "oneclick_delete_disable_hint": "已关闭一键删除模式",
        "oneclick_delete_dialog_title": "警告",
        "oneclick_delete_dialog_content": "开启一键删除模式后，点击地图上的标记不会再出现弹窗，取而代之的是直接删除标记或者恢复标记，是否继续开启？'",
        "oneclick_delete_dialog_close": "关闭",
        "oneclick_delete_dialog_confirm": "开启",
        "batch_editing_enable": "批量管理",
        "batch_editing_disable": "退出管理",
        "batch_editing_hint": "可以批量删除或者恢复某个分类所有的标记，需要登录才能使用。",
        "setting_btn_hint": "与地图相关的设置",
        "login_btn_hint": "云端同步",
        "back_to_categories": "返回分类筛选",
        "display_area": "显示区域 (点击名字隐藏，点击图标定位)",

    },
    "floor_text": {
        "roof": "( 在楼顶 )",
        "at_floor": "( 在{floor}层 )",
        "underground": "( 在负{floor}层 )"
    },
    "settings": {
        "has_video": "专属视频攻略标记",
        "deleted_marker": "被删除的标记",
        "map_area_style": "地图区域显示样式",
        "monster_bus_route": "公交车(怪物巴士)路线",
        "marker_text": "标记文本",
        "resource_area": "资源密集区域",
        "last_updated_datetime": "标记最后更新时间",
        "icon_drawing_method": "图标预处理方法（乱码请使用）",
        "dark_mode": "夜间模式",
        "language": "语言设置 (Language)",
        "auto_query": "勾选分类自动查询",
        "auto_draw_marker_after_search": "地图自动显示物品的搜索结果",
        "show": "显示",
        "hide": "隐藏",
        "line_style": "线条",
        "area_style": "线条填充",
        "wasm": "Wasm (性能最好)",
        "canvas": "Canvas (兼容最好)",
        "on": "开启",
        "off": "关闭"
    },
    "user_data": {
        "local_storage": "本地数据",
        "count": "{count} 条数据",
        "local_storage_tutorial": "本地使用教程",
        "backup": "数据手动备份转移",
        "local_storage_text": "无需登录可以在本地储存数据。如果不保存到云端，可以使用该功能手动同步数据到其他浏览器。点击【备份数据】后，复制输入框的内容到目标浏览器的输入框，然后点击【恢复数据】即可。 ",
        "backup_placeholder": "数据内容",
        "backup_button": "备份数据",
        "restore_button": "恢复数据",
        "cloud_storage": "云端同步",
        "clear_all_data": "清空所有数据",
        "restore_hint": "提示：该操作会将本地数据与导入数据合并，如果登录了还会同步数据到云端，是否继续？",
        "delete_hint": "警告: 该操作会删除所有数据，如果已经登录还会清除云端数据，是否继续？"
    },
    "marker_dialog": {
        "no_marker_img": "暂无标记配图",
        "delete_markder": "删除标记",
        "undelete": "恢复标记",
        "delete_only": "仅删除",
        "hide_category": "隐藏{category}分类",
        "no_update_time": "更新时间尚未记录",
        "rewards": "战利品",
        "close": "关闭",
        "detail": "详情",
        "operation": "标记操作 ( 定时功能已适配固定刷新时间 )",
        "timer_title": "武器箱&装备箱定时恢复",
        "timer_title_not_login": "(需登录) 武器箱&装备箱定时恢复",
        "to_login": "前往登录以使用定时功能",
        "comment": "余音",
        "auto_set_timer": "自动设置定时恢复",
        "auto_set_timer_not_login": "(需登录) 自动设置定时恢复",
        "timer_tutorial": "定时恢复教程",
        "sharing": "分享",
        "session_script": "收容物所属赛季: ",
        "hint": "【星川提醒您】",
        "sharing_hint": "分享链接可以在打开后自动显示该标记",
        "download_qr_code": "点击下载二维码",
        "sharing_link": "专属链接",
        "copy": "复制",
        "update": "更新",
        "guide": "专属攻略",
        "donate": "打赏",
    },
    "donate": {
        "payment": "请使用微信扫码",
        "text": "您的支持可以帮助网站持续运营和更多功能更新",
        "warning": "未成年人禁止打赏"
    },
    "categories": {
        "巨楔": "巨楔",
        "主城": "主城",
        "研究所": "研究所",
        "大型资源点": "大型资源点",
        "小型资源点": "小型资源点",
        "采集点": "采集点",
        "收容井": "收容井",
        "传送塔": "传送塔",
        "武器配件": "武器配件",
        "食谱": "食谱",
        "精英怪": "精英怪",
        "收容物": "收容物",
        "异常点": "异常点",
        "宝箱怪": "宝箱怪",
        "武器箱": "武器箱",
        "装备箱": "装备箱",
        "神秘宝藏": "神秘宝藏",
        "隐藏宝箱": "隐藏宝箱",
        "留言": "留言",
        "诡谲画作": "诡谲画作",
        "商人": "商人",
        "隐藏任务": "隐藏任务",
        "迷雾区域": "迷雾区域",
        "移动房屋": "移动房屋",
        "回响石": "回响石",
        "储物箱": "储物箱",
        "位面锚": "位面锚",
        "防守工坊": "防守工坊",
        "宜居地点": "宜居地点",
        "限时事件": "限时事件",
        "矿物点": "矿物点",

        "代顿湿地": "代顿湿地",
        "破碎三角洲": "破碎三角洲",
        "垩峰山": "垩峰山",
        "铁锈河": "铁锈河",
        "孤狼荒原": "孤狼荒原",
        "黑心地带": "黑心地带",

        "怪物巴士路线": "怪物巴士路线",

        "远归之蝶": "远归之蝶",
        "活体凝胶": "活体凝胶",
        "荣枯种子": "荣枯种子",
        "捕梦网": "捕梦网",
        "迪斯科球": "迪斯科球",
        "矿石小子": "矿石小子",
        "木工河狸": "木工河狸",
        "电鳗": "电鳗",
        "愿望先生": "愿望先生",
        "姜饼屋": "姜饼屋",
        "蝶之梦": "蝶之梦",
        "一碗美味": "一碗美味",
        "极寒水母": "极寒水母",
        "工号37": "工号37",
        "低语亡骨": "低语亡骨",
        "蜂团团": "蜂团团",
        "空间魔方": "空间魔方",
        "气球狗": "气球狗",
        "凝视的黑猫": "凝视的黑猫",
        "空之子": "空之子",
        "恶臭球根": "恶臭球根",
        "胡桃夹子": "胡桃夹子",
        "青龙": "青龙",
        "发条青蛙": "发条青蛙"
    }
}