export default {
    "buttons": {
        "filter": "筛选标记",
        "select_all": "全选",
        "deselect_all": "全不选",
        "close": "关闭",
        "move_left": "左移",
        "move_right": "右移"
    },
    "tabs": {
        "by_category": "分类",
        "by_item": "物品",
        "by_search": "搜索",
        "resource_list": "资源",
        "setting": "设置",
        "user_data": "数据管理",
        "quick_setting": "快捷设置",
        "quick_setting_fuel_loot": "摸油路线",
        "quick_setting_resource": "资源密集区",
        "quick_setting_bus_route": "怪物巴士路线",
        "area": "地点区域",
        "treasure": "宝箱秘藏",
        "monster": "事件怪物",
        "collection": "收集要素",
        "hint": "地图提示",
        "logged": "已登录",
        "guest": "未登录",
        "oneclick_delete_enable": "一键删除",
        "oneclick_delete_disable": "关闭一键",
        "oneclick_delete_badge": "已开启一键删除",
        "oneclick_delete_hint1": "开启后，点击标记不再显示弹窗，而是直接删除或恢复标记。",
        "oneclick_delete_enable_hint": "已开启一键删除模式",
        "oneclick_delete_disable_hint": "已关闭一键删除模式",
        "oneclick_delete_dialog_title": "警告",
        "oneclick_delete_dialog_content": "开启一键删除模式后，点击地图上的标记不会再出现弹窗，取而代之的是直接删除标记或者恢复标记，是否继续开启？'",
        "oneclick_delete_dialog_close": "关闭",
        "oneclick_delete_dialog_confirm": "开启",
        "batch_editing_enable": "进度管理",
        "batch_editing_disable": "退出管理",
        "batch_editing_hint": "可以批量删除或者恢复某个分类所有的标记，需要登录才能使用。",
        "setting_btn_hint": "与地图相关的设置",
        "login_btn_hint": "云端同步",
        "back_to_categories": "返回分类筛选",
        "display_area": "显示区域 (点击名字隐藏，点击图标定位)",
        "select_item_category": "选择物品分类",
        "related_items": "相关物品列表",
        "locate_item": "点击物品定位地图",
        "search_resources": "筛选资源列表",
        "input_resource_name": "请输入资源名称",
        "locate": "定位地图",
        // Miscellaneous UI strings
        "any_name": "任意名称",
        "locations": "相关地点列表",
        "locate_point": "点击地点定位地图",
        "input_item": "请输入物品名称进行搜索",
        "related_item": "相关物品",
        "related_makers": "相关标记列表",
        "locate_marker": "点击标记定位地图",
        "input_marker": "请输入标记名称进行搜索",
        "related_resources": "相关资源列表",
        "locate_resource": "点击标记定位地图",
        "input_resource_for_searching": "请输入资源名称进行搜索",
        "follow_xingchuan": "关注星川",
        "bilibili": "前往B站关注",
        "tiktok": "前往抖音关注",
        "ad": "福利",
        "ad2": "代肝",
        "jd": "京东限时福利：30元通用优惠券，满30就能用",
        "daigan": "代肝微信公众号搜索： DD俱乐部",
        "login_warring": "请先输入公众号回复的内容才能进行登录",
        "delete_all": "全删",
        "resume_all": "恢复",
        "exit_management_mode": "退出管理模式"
    },
    "floor_text": {
        "roof": "( 在楼顶 )",
        "at_floor": "( 在{floor}层 )",
        "underground": "( 在负{floor}层 )",
        "level": "( {level}级 )"
    },
    "settings": {
        "has_video": "专属视频攻略标记",
        "deleted_marker": "被删除的标记",
        "map_area_style": "地图区域显示样式",
        "monster_bus_route": "公交车(怪物巴士)路线",
        "marker_text": "标记文本",
        "resource_area": "资源密集区域",
        "last_updated_datetime": "标记最后更新时间",
        "icon_drawing_method": "图标预处理方法（乱码请使用）",
        "dark_mode": "夜间模式",
        "language": "语言设置 (Language)",
        "auto_query": "勾选分类自动查询",
        "auto_draw_marker_after_search": "地图自动显示物品的搜索结果",
        "show": "显示",
        "hide": "隐藏",
        "line_style": "线条",
        "area_style": "线条填充",
        "wasm": "Wasm (性能最好)",
        "canvas": "Canvas (兼容最好)",
        "on": "开启",
        "off": "关闭",
        "draw_text_mode": "标记文本样式",
        "draw_text_mode_1": "完整",
        "draw_text_mode_2": "精简"
    },
    "user_data": {
        "local_storage": "本地数据",
        "count": "{count} 条数据",
        "local_storage_tutorial": "本地使用教程",
        "backup": "数据手动备份转移",
        "local_storage_text": "无需登录可以在本地储存数据。如果不保存到云端，可以使用该功能手动同步数据到其他浏览器。点击【备份数据】后，复制输入框的内容到目标浏览器的输入框，然后点击【恢复数据】即可。 ",
        "backup_placeholder": "数据内容",
        "backup_button": "备份数据",
        "restore_button": "恢复数据",
        "cloud_storage": "云端同步",
        "clear_all_data": "清空所有数据",
        "restore_hint": "提示：该操作会将本地数据与导入数据合并，如果登录了还会同步数据到云端，是否继续？",
        "delete_hint": "警告: 该操作会删除所有数据，如果已经登录还会清除云端数据，是否继续？",
        "wechat_login": "公众号凭证登录",
        "wechat_mp_login": "回响宝典扫码登录",
        "discord_login": "Discord 登录",
        "login_tutorial": "同步使用教程",
        "login_tutorial_text": "登录后，自动同步本地和云端的数据，可以在任意浏览器和设备继续使用。没有登录的情况下，也可以正常使用，但是数据只能储存在本地浏览器。",
        "not_login": "未登录",
        "login_success": "已与小程序同步登录",
        "data_is_syncing": "数据已在同步",
        "last_syncing_time": "上次同步时间：",
        "logout": "退出登录",

    },
    "marker_dialog": {
        "no_marker_img": "暂无标记配图",
        "delete_markder": "删除标记",
        "undelete": "恢复标记",
        "delete_only": "仅删除",
        "hide_category": "隐藏{category}分类",
        "no_update_time": "更新时间尚未记录",
        "rewards": "战利品",
        "close": "关闭",
        "detail": "详情",
        "operation": "标记操作",
        "timer_title": "武器箱&装备箱定时恢复",
        "timer_title_not_login": "(需登录) 武器箱&装备箱定时恢复",
        "to_login": "前往登录以使用定时功能",
        "comment": "余音",
        "auto_set_timer": "自动设置定时恢复",
        "auto_set_timer_not_login": "(需登录) 自动设置定时恢复",
        "timer_tutorial": "定时恢复教程",
        "sharing": "分享",
        "session_script": "收容物所属赛季: ",
        "hint": "【星川提醒您】",
        "sharing_hint": "分享链接可以在打开后自动显示该标记",
        "download_qr_code": "点击下载二维码",
        "sharing_link": "专属链接",
        "copy": "复制",
        "update": "更新",
        "guide": "专属攻略",
        "donate": "打赏",
        "auto_reset_help_title": "自动恢复功能帮助",
        "auto_reset_help_text": "武器箱和装备箱的固定刷新时间从00:00:00开始，每4小时整点刷新。如果到了刷新点还不能开箱子，重新登录一下即可。",
        "auto_reset_help_ok": "我知道了"
    },
    "donate": {
        "payment": "请使用微信扫码",
        "text": "您的支持可以帮助网站持续运营和更多功能更新",
        "warning": "未成年人禁止打赏"
    },
    "categories": {
        // The key name will be the Chinese name when Chinese translation is missing.
    }
}